export type Category =
  | 'Ancient/Medieval'
  | 'Freedom Struggle'
  | 'Sports'
  | 'PYQ'
  | 'Literary Award'
  | 'Current Affairs'

export type ExamProb = 'Hot' | 'High' | 'Medium' | 'Confirmed' | 'Recurring'

export interface BookEntry {
  id: number
  title: string
  author: string
  category: Category
  award: string
  year: string
  theme: string
  mnemonic: string
  context: string
  examProb: ExamProb
}

export interface PYQEntry {
  date: string
  shift: string
  bookOrQuestion: string
  answer: string
  category: string
}

// ─── PYQ SHIFT HISTORY ────────────────────────────────────────────────────────
export const pyqHistory: PYQEntry[] = [
  { date: '09 Sep 2024', shift: 'Shift 1', bookOrQuestion: 'Related to the play "Neel Darpan"', answer: 'Dinabandhu Mitra', category: 'Ancient/Medieval' },
  { date: '24 Jul 2023', shift: 'All Shifts', bookOrQuestion: 'International Booker Prize 2022 winner', answer: 'Geetanjali Shree — Tomb of Sand', category: 'Literary Award' },
  { date: '21 Jul 2023', shift: 'All Shifts', bookOrQuestion: 'Author of Kitab-ul-Hind', answer: 'Al-Biruni', category: 'Ancient/Medieval' },
  { date: '14 Jul 2023', shift: 'All Shifts', bookOrQuestion: 'Author of Sanskrit play Mricchakatika', answer: 'Sudraka', category: 'Ancient/Medieval' },
  { date: '02 Dec 2022', shift: 'All Shifts', bookOrQuestion: '"No Spin" is related to which sports personality?', answer: 'Shane Warne', category: 'Sports' },
  { date: '02 Dec 2022', shift: 'All Shifts', bookOrQuestion: 'Who is the author of Harsha Charita?', answer: 'Banabhatta', category: 'Ancient/Medieval' },
  { date: '01 Dec 2022', shift: 'All Shifts', bookOrQuestion: 'Who wrote "Playing It My Way"?', answer: 'Sachin Tendulkar', category: 'Sports' },
  { date: '20 Apr 2022', shift: 'Shift 1', bookOrQuestion: 'Author of the book Kamayani', answer: 'Jay Shankar Prasad', category: 'PYQ' },
  { date: '13 Aug 2021', shift: 'Shift 1', bookOrQuestion: 'Author of Kitab-ul-Hind (Repeat)', answer: 'Al-Biruni', category: 'Ancient/Medieval' },
  { date: 'Apr 2021', shift: 'Shift 1', bookOrQuestion: 'Director of The Nehru Centre in London', answer: 'Amish Tripathi', category: 'PYQ' },
]

// ─── MASTER BOOK DATABASE ─────────────────────────────────────────────────────
export const booksData: BookEntry[] = [

  // ── ANCIENT / MEDIEVAL ──────────────────────────────────────────────────────
  {
    id: 1,
    title: 'Arthashastra',
    author: 'Kautilya (Chanakya)',
    category: 'Ancient/Medieval',
    award: 'Classical Treatise',
    year: '~300 BCE',
    theme: 'Mauryan statecraft, economics & military strategy',
    mnemonic: 'CHANAKYA rules with ARTHA (wealth)',
    context: 'Repeated across 2020–2025 PYQs; Mauryan Empire context',
    examProb: 'Recurring',
  },
  {
    id: 2,
    title: 'Harsha Charita',
    author: 'Banabhatta',
    category: 'Ancient/Medieval',
    award: 'Classical Sanskrit Prose',
    year: '7th Century CE',
    theme: 'Biography of King Harsha Vardhana',
    mnemonic: 'BANA writes the story of HARSH king',
    context: 'SSC CGL 02 Dec 2022 — "Who wrote Harsha Charita?"',
    examProb: 'Confirmed',
  },
  {
    id: 3,
    title: 'Rajtarangini',
    author: 'Kalhana',
    category: 'Ancient/Medieval',
    award: 'Historical Chronicle',
    year: '12th Century CE',
    theme: 'Chronicle of the Kings of Kashmir',
    mnemonic: 'KALHANA keeps the RANI (queen) chronicle',
    context: 'Frequently asked — Kashmir history angle',
    examProb: 'Recurring',
  },
  {
    id: 4,
    title: 'Mudrarakshasa',
    author: 'Visakhadatta',
    category: 'Ancient/Medieval',
    award: 'Sanskrit Drama',
    year: '~4th–8th Century CE',
    theme: 'Rise of Chandragupta Maurya — historical play',
    mnemonic: 'VISHAKA dramatises MUDRA (seal) politics',
    context: 'Questions on Mauryan empire political history',
    examProb: 'Recurring',
  },
  {
    id: 5,
    title: 'Kathasaritsagar',
    author: 'Somadeva',
    category: 'Ancient/Medieval',
    award: 'Classical Sanskrit',
    year: '11th Century CE',
    theme: 'Ocean of stories — Indian folk tales collection',
    mnemonic: 'SOMA collects SEA (sagar) of stories',
    context: 'Asked in context of Sanskrit literary tradition',
    examProb: 'Recurring',
  },
  {
    id: 6,
    title: 'Kamasutra',
    author: 'Vatsayana',
    category: 'Ancient/Medieval',
    award: 'Ancient Sanskrit Text',
    year: '~3rd–4th Century CE',
    theme: 'Ancient treatise on human behaviour & relationships',
    mnemonic: 'VATSA (calf) follows KAMA (desire)',
    context: 'Context: Ancient Indian social literature',
    examProb: 'Recurring',
  },
  {
    id: 7,
    title: 'Buddhacharita',
    author: 'Asvaghosa',
    category: 'Ancient/Medieval',
    award: 'Sanskrit Epic Poem',
    year: '~1st–2nd Century CE',
    theme: 'Epic poem on the life of Gautama Buddha',
    mnemonic: 'ASHVA (horse) gallops through BUDDHA\'s life',
    context: 'Buddhist literature — Kushana period',
    examProb: 'Recurring',
  },
  {
    id: 8,
    title: 'Natyashastra',
    author: 'Bharata Muni',
    category: 'Ancient/Medieval',
    award: 'Foundational Treatise',
    year: '~200 BCE–200 CE',
    theme: 'Foundational guide to performing arts — drama, music, dance',
    mnemonic: 'BHARAT\'s NATYA (drama) is the shastric base',
    context: 'Asked in culture & arts questions',
    examProb: 'Recurring',
  },
  {
    id: 9,
    title: 'Indica',
    author: 'Megasthenes',
    category: 'Ancient/Medieval',
    award: 'Greek Account',
    year: '~3rd Century BCE',
    theme: 'Greek traveler\'s account of Mauryan India',
    mnemonic: 'MEGA Greek writes INDICA of India',
    context: 'Foreign accounts of India — Chandragupta era',
    examProb: 'Recurring',
  },
  {
    id: 10,
    title: 'Gita Govinda',
    author: 'Jayadeva',
    category: 'Ancient/Medieval',
    award: 'Devotional Sanskrit Poem',
    year: '12th Century CE',
    theme: 'Devotional poem — Radha-Krishna love (12th century)',
    mnemonic: 'JAYA (victory) to GITA of GOVINDA',
    context: 'Medieval devotional literature',
    examProb: 'Recurring',
  },
  {
    id: 11,
    title: 'Abhijnanasakuntalam',
    author: 'Kalidasa',
    category: 'Ancient/Medieval',
    award: 'Sanskrit Classic Drama',
    year: 'Gupta Period (~4th–5th Century CE)',
    theme: 'Sanskrit play — Shakuntala & King Dushyanta (Gupta era)',
    mnemonic: 'KALI\'s greatest SAKUNTala play',
    context: 'Gupta Golden Age — Kalidasa\'s trilogy',
    examProb: 'Recurring',
  },
  {
    id: 12,
    title: 'Kitab-ul-Hind',
    author: 'Al-Biruni',
    category: 'Ancient/Medieval',
    award: 'Medieval Islamic Scholarship',
    year: '~1030 CE',
    theme: 'Encyclopedic account of Indian science, religion & philosophy',
    mnemonic: 'AL BIRUNI\'s KITAB is an Indian encyclopaedia',
    context: 'SSC CGL 13 Aug 2021 & 21 Jul 2023 — Repeated! Mahmud of Ghazni',
    examProb: 'Confirmed',
  },
  {
    id: 13,
    title: 'Ain-i-Akbari',
    author: 'Abul Fazl',
    category: 'Ancient/Medieval',
    award: 'Mughal Chronicle',
    year: '~1598 CE',
    theme: 'Detailed account of Mughal administration under Akbar',
    mnemonic: 'ABUL FAZL records AIN (rules) of AKBAR',
    context: 'Mughal history — administrative system',
    examProb: 'Recurring',
  },
  {
    id: 14,
    title: 'Mricchakatika',
    author: 'Sudraka',
    category: 'Ancient/Medieval',
    award: 'Sanskrit Comedy-Drama',
    year: '~2nd–5th Century CE',
    theme: 'Sanskrit social comedy — love story across caste lines',
    mnemonic: 'SUDRA wrote a CLAY CART (mriccha) play',
    context: 'SSC CGL 14 Jul 2023 — "Author of Mricchakatika?"',
    examProb: 'Confirmed',
  },
  {
    id: 15,
    title: 'Neel Darpan',
    author: 'Dinabandhu Mitra',
    category: 'Ancient/Medieval',
    award: 'Colonial Era Drama',
    year: '1860',
    theme: 'Indigo Revolt — brutality of British indigo planters',
    mnemonic: 'DINA shows the NEEL (blue) mirror to empire',
    context: 'SSC CGL 09 Sep 2024 Shift 1 — Indigo Revolt context',
    examProb: 'Confirmed',
  },
  {
    id: 16,
    title: 'Kamayani',
    author: 'Jay Shankar Prasad',
    category: 'Ancient/Medieval',
    award: 'Mangala Prasad Paritoshik',
    year: '1936',
    theme: 'Hindi epic poem — mythological allegory of Manu & Shraddha',
    mnemonic: 'PRASAD pours KAMA (desire) into Hindi epic',
    context: 'SSC CGL 20 Apr 2022 Shift 1 — Confirmed PYQ',
    examProb: 'Confirmed',
  },

  // ── FREEDOM STRUGGLE ────────────────────────────────────────────────────────
  {
    id: 17,
    title: 'My Experiments with Truth',
    author: 'M. K. Gandhi',
    category: 'Freedom Struggle',
    award: 'Autobiography / Bharat Ratna (Author)',
    year: '1927',
    theme: 'Gandhi\'s autobiography — philosophy of truth & non-violence',
    mnemonic: 'GANDHI experiments with TRUTH daily',
    context: 'Most repeated autobiography in SSC CGL history',
    examProb: 'Confirmed',
  },
  {
    id: 18,
    title: 'The Discovery of India',
    author: 'Jawaharlal Nehru',
    category: 'Freedom Struggle',
    award: 'Bharat Ratna (Author)',
    year: '1946',
    theme: 'India\'s history & civilisation — written in Ahmednagar prison',
    mnemonic: 'NEHRU DISCOVERS India while imprisoned',
    context: 'SSC CGL 2019, Tier 1 — prison + civilisation angle',
    examProb: 'Confirmed',
  },
  {
    id: 19,
    title: 'Ananda Math',
    author: 'Bankim Chandra Chatterjee',
    category: 'Freedom Struggle',
    award: 'Historical Novel',
    year: '1882',
    theme: 'Sanyasi Rebellion — source of national song Vande Mataram',
    mnemonic: 'BANKIM\'s MATH gave us Vande Mataram',
    context: 'Source of Vande Mataram — Sanyasi Rebellion context',
    examProb: 'Recurring',
  },
  {
    id: 20,
    title: 'Gitanjali',
    author: 'Rabindranath Tagore',
    category: 'Freedom Struggle',
    award: 'Nobel Prize in Literature',
    year: '1913',
    theme: 'Devotional poetry — first Indian Nobel Prize winner',
    mnemonic: 'TAGORE\'s GEET (song) wins ANJALI (Nobel)',
    context: 'First Indian Nobel Prize (Literature) 1913',
    examProb: 'Recurring',
  },
  {
    id: 21,
    title: 'Why I Am An Atheist',
    author: 'Bhagat Singh',
    category: 'Freedom Struggle',
    award: 'Revolutionary Essay',
    year: '1930',
    theme: 'Revolutionary ideology — Bhagat Singh\'s philosophical argument',
    mnemonic: 'BHAGAT (devotee) asks why he has no BHAGWAN',
    context: 'Revolutionary literature — written in prison before execution',
    examProb: 'Recurring',
  },
  {
    id: 22,
    title: 'Waiting for a Visa',
    author: 'B. R. Ambedkar',
    category: 'Freedom Struggle',
    award: 'Bharat Ratna (Author)',
    year: '1935–36',
    theme: 'Personal narrative of untouchability & caste discrimination',
    mnemonic: 'AMBEDKAR waits for VISA denied by caste',
    context: 'Dalit rights literature — essential for social justice questions',
    examProb: 'Recurring',
  },
  {
    id: 23,
    title: 'The Broken Wing',
    author: 'Sarojini Naidu',
    category: 'Freedom Struggle',
    award: 'Poetry Collection',
    year: '1917',
    theme: 'Lyric poetry — Nightingale of India\'s independence movement',
    mnemonic: 'SAROJINI\'s WING is broken but her voice soars',
    context: 'Nightingale of India — poetry & freedom struggle',
    examProb: 'Recurring',
  },
  {
    id: 24,
    title: 'India Wins Freedom',
    author: 'Maulana Abul Kalam Azad',
    category: 'Freedom Struggle',
    award: 'Bharat Ratna (Author)',
    year: '1959',
    theme: 'Political memoir — Independence & Partition tragedy',
    mnemonic: 'AZAD (Free) wins FREEDOM for India',
    context: 'SSC CGL 2020 Shift 3 — Partition history angle',
    examProb: 'Confirmed',
  },

  // ── SPORTS & CELEBRITY ──────────────────────────────────────────────────────
  {
    id: 25,
    title: 'Playing It My Way',
    author: 'Sachin Tendulkar',
    category: 'Sports',
    award: 'Bharat Ratna (Author)',
    year: '2014',
    theme: 'Autobiography of a cricketing legend — 100 international centuries',
    mnemonic: 'SACHIN plays his own WAY',
    context: 'SSC CGL 01 Dec 2022 — Confirmed PYQ',
    examProb: 'Confirmed',
  },
  {
    id: 26,
    title: 'Unbreakable: An Autobiography',
    author: 'Mary Kom',
    category: 'Sports',
    award: 'Padma Bhushan (Author)',
    year: '2013',
    theme: 'Boxing autobiography — six-time world champion from Manipur',
    mnemonic: 'MARY KOM is UNBREAKABLE in the ring',
    context: 'SSC CGL 2021, Tier 1 — women sports icon',
    examProb: 'Confirmed',
  },
  {
    id: 27,
    title: 'A Shot at History',
    author: 'Abhinav Bindra',
    category: 'Sports',
    award: 'Padma Bhushan (Author)',
    year: '2011',
    theme: 'Shooting — India\'s first individual Olympic gold medal',
    mnemonic: 'BINDRA takes a SHOT at HISTORY (first gold)',
    context: 'First individual Olympic gold for India — Beijing 2008',
    examProb: 'High',
  },
  {
    id: 28,
    title: 'Ace Against Odds',
    author: 'Sania Mirza',
    category: 'Sports',
    award: 'Padma Bhushan (Author)',
    year: '2016',
    theme: 'Tennis autobiography — Grand Slam achievements & challenges',
    mnemonic: 'SANIA hits an ACE against all ODDS',
    context: 'Grand Slam doubles champion autobiography',
    examProb: 'High',
  },
  {
    id: 29,
    title: 'The Race of My Life',
    author: 'Milkha Singh',
    category: 'Sports',
    award: 'Padma Sri (Author)',
    year: '2013',
    theme: 'Athletics — Flying Sikh, Partition survivor & Rome 1960 tragedy',
    mnemonic: 'MILKHA runs the RACE of his LIFE',
    context: 'Partition + athletics context; film adaptation boosted visibility',
    examProb: 'High',
  },
  {
    id: 30,
    title: 'Sunny Days',
    author: 'Sunil Gavaskar',
    category: 'Sports',
    award: 'Padma Bhushan (Author)',
    year: '1976',
    theme: 'Cricket memoir — Little Master\'s early international career',
    mnemonic: 'GAVASKAR\'s SUNNY DAYS on the pitch',
    context: 'Classic cricket autobiography — frequently in PYQ pool',
    examProb: 'High',
  },
  {
    id: 31,
    title: 'A Century is Not Enough',
    author: 'Sourav Ganguly',
    category: 'Sports',
    award: 'Padma Sri (Author)',
    year: '2018',
    theme: 'Cricket autobiography — BCCI President & India\'s turnaround',
    mnemonic: 'DADA needs more than a CENTURY',
    context: 'SSC CGL 2020 Tier 1 — confirmed PYQ',
    examProb: 'Confirmed',
  },
  {
    id: 32,
    title: 'Straight from the Heart',
    author: 'Kapil Dev',
    category: 'Sports',
    award: 'Padma Bhushan (Author)',
    year: '2004',
    theme: 'Cricket — 1983 World Cup captain\'s autobiography',
    mnemonic: 'KAPIL speaks STRAIGHT from the HEART',
    context: '1983 Cricket World Cup — 40th anniversary coverage boosted visibility',
    examProb: 'High',
  },
  {
    id: 33,
    title: 'The Test of My Life',
    author: 'Yuvraj Singh',
    category: 'Sports',
    award: 'Padma Bhushan (Author)',
    year: '2013',
    theme: 'Cricket — battle with cancer & comeback to 2011 World Cup',
    mnemonic: 'YUVI\'s TEST is not on pitch but with cancer',
    context: '2011 World Cup hero — cancer survivor memoir',
    examProb: 'High',
  },
  {
    id: 34,
    title: 'No Spin',
    author: 'Shane Warne',
    category: 'Sports',
    award: 'Sports Memoir',
    year: '2018',
    theme: 'Cricket — leg-spin legend\'s life & controversies',
    mnemonic: 'WARNE never gives NO SPIN on anything',
    context: 'SSC CGL 02 Dec 2022 — Confirmed PYQ; linked to his passing in 2022',
    examProb: 'Confirmed',
  },

  // ── PYQ (MODERN LITERARY / POLITICAL) ──────────────────────────────────────
  {
    id: 35,
    title: 'A Suitable Boy',
    author: 'Vikram Seth',
    category: 'PYQ',
    award: 'WH Smith Literary Award',
    year: '1993',
    theme: 'Post-independence India — family saga & arranged marriage',
    mnemonic: 'VIKRAM finds a SUITABLE match for his daughter',
    context: 'SSC CGL 2022 Tier 1 Shift 2',
    examProb: 'Confirmed',
  },
  {
    id: 36,
    title: 'The White Tiger',
    author: 'Aravind Adiga',
    category: 'PYQ',
    award: 'Booker Prize',
    year: '2008',
    theme: 'Class struggle — dark side of India\'s economic boom',
    mnemonic: 'ADIGA hunts the WHITE TIGER of corruption',
    context: 'SSC CGL 2022 Tier 1; also a Netflix film',
    examProb: 'Confirmed',
  },
  {
    id: 37,
    title: 'An Era of Darkness',
    author: 'Shashi Tharoor',
    category: 'PYQ',
    award: 'Sahitya Akademi Award',
    year: '2016',
    theme: 'Critique of British colonial rule in India',
    mnemonic: 'Shashi sheds LIGHT on DARKNESS of empire',
    context: 'SSC CGL 2020 Tier 1 — colonial history angle',
    examProb: 'Confirmed',
  },
  {
    id: 38,
    title: 'Train to Pakistan',
    author: 'Khushwant Singh',
    category: 'PYQ',
    award: 'Padma Bhushan (Author)',
    year: '1956',
    theme: 'Horrors of Partition 1947 — communal violence at the border',
    mnemonic: 'KHUSH (happy) boards the unhappy PARTITION train',
    context: 'SSC CGL 2021, Repeated — Partition literature',
    examProb: 'Confirmed',
  },
  {
    id: 39,
    title: 'The God of Small Things',
    author: 'Arundhati Roy',
    category: 'PYQ',
    award: 'Booker Prize',
    year: '1997',
    theme: 'Caste system & forbidden love in Kerala',
    mnemonic: 'ROYal family crushed by SMALL caste rules',
    context: 'SSC CGL 2022 Shift 2 — Booker + Kerala angle',
    examProb: 'Confirmed',
  },
  {
    id: 40,
    title: 'Wings of Fire',
    author: 'A. P. J. Abdul Kalam',
    category: 'PYQ',
    award: 'Bharat Ratna (Author)',
    year: '1999',
    theme: 'Autobiography of India\'s Missile Man & President',
    mnemonic: "KALAM's WINGS ignite India's missile FIRE",
    context: 'SSC CGL 2018 — Most frequently repeated; presidential + science angle',
    examProb: 'Confirmed',
  },
  {
    id: 41,
    title: 'My Truth',
    author: 'Indira Gandhi',
    category: 'PYQ',
    award: 'Political Memoir',
    year: '1981',
    theme: 'Political autobiography — Emergency, governance & personal life',
    mnemonic: 'INDIRA speaks MY TRUTH boldly',
    context: 'SSC CGL 2022 Tier 1',
    examProb: 'Confirmed',
  },
  {
    id: 42,
    title: 'Think Like a Monk',
    author: 'Jay Shetty',
    category: 'PYQ',
    award: 'Global Bestseller',
    year: '2020',
    theme: 'Self-help — mindfulness wisdom from monk philosophy',
    mnemonic: 'SHETTY the ex-MONK thinks differently',
    context: 'Direct attribution questions — "Who authored Think Like a Monk?"',
    examProb: 'High',
  },

  // ── LITERARY AWARDS ─────────────────────────────────────────────────────────
  {
    id: 43,
    title: 'Tomb of Sand (Ret Samadhi)',
    author: 'Geetanjali Shree',
    category: 'Literary Award',
    award: 'International Booker Prize',
    year: '2022',
    theme: 'First Hindi novel to win Int. Booker — Partition & elderly women',
    mnemonic: 'GEET (song) buried in SAND — first Hindi winner',
    context: 'SSC CGL 2023 / Highly important — "first Hindi-translated novel"',
    examProb: 'Confirmed',
  },
  {
    id: 44,
    title: 'Seven Moons of Maali Almeida',
    author: 'Shehan Karunatilaka',
    category: 'Literary Award',
    award: 'Booker Prize',
    year: '2022',
    theme: 'Sri Lanka civil war — ghost photographer solves his own murder',
    mnemonic: 'SHEHAN\'s SEVEN moons haunt Sri Lanka',
    context: 'Booker 2022 — Sri Lankan civil war context',
    examProb: 'High',
  },
  {
    id: 45,
    title: 'The Promise',
    author: 'Damon Galgut',
    category: 'Literary Award',
    award: 'Booker Prize',
    year: '2021',
    theme: 'South African family saga across four decades of post-apartheid',
    mnemonic: 'GALGUT promises a South African saga',
    context: 'Booker 2021 — South Africa angle',
    examProb: 'Medium',
  },
  {
    id: 46,
    title: 'Kairos',
    author: 'Jenny Erpenbeck',
    category: 'Literary Award',
    award: 'International Booker Prize',
    year: '2024',
    theme: 'East Germany — forbidden love & political collapse',
    mnemonic: 'ERPEN\'s KAIROS captures East Germany\'s end',
    context: 'Int. Booker 2024 — high probability for 2025 exams',
    examProb: 'High',
  },
  {
    id: 47,
    title: 'Heart Lamp',
    author: 'Banu Mushtaq',
    category: 'Literary Award',
    award: 'International Booker Prize',
    year: '2025',
    theme: 'Kannada short stories — women\'s lives in conservative society',
    mnemonic: 'BANU\'s HEART LAMP lights Kannada women\'s stories',
    context: 'Int. Booker 2025 (Translated by Deepa Bhasthi) — extremely HOT for 2026',
    examProb: 'Hot',
  },
  {
    id: 48,
    title: 'Flesh',
    author: 'David Szalay',
    category: 'Literary Award',
    award: 'Booker Prize',
    year: '2025',
    theme: 'Interconnected lives across Europe — human connection & fragility',
    mnemonic: 'SZALAY puts FLESH on Europe\'s bones',
    context: 'Booker Prize 2025 — very high probability for 2026 CGL',
    examProb: 'Hot',
  },
  {
    id: 49,
    title: 'Spirit Nights',
    author: 'Easterine Kire',
    category: 'Literary Award',
    award: 'Sahitya Akademi Award (English)',
    year: '2024',
    theme: 'Naga folklore & supernatural — northeast India oral tradition',
    mnemonic: 'EASTERINE brings Naga SPIRIT to English nights',
    context: 'Sahitya Akademi 2024 English winner — regional + northeast angle',
    examProb: 'High',
  },
  {
    id: 50,
    title: 'Jeete Jee Allahabad',
    author: 'Mamta Kalia',
    category: 'Literary Award',
    award: 'Sahitya Akademi Award (Hindi)',
    year: '2025',
    theme: 'Memoir — city of Allahabad through personal memory',
    mnemonic: 'MAMTA lives in ALLAHABAD while ALIVE',
    context: 'Sahitya Akademi 2025 Hindi — city-as-memoir angle',
    examProb: 'Hot',
  },
  {
    id: 51,
    title: 'Main Jab Tak Aai Bahar',
    author: 'Gagan Gill',
    category: 'Literary Award',
    award: 'Sahitya Akademi Award (Hindi)',
    year: '2024',
    theme: 'Hindi poetry — existential verse on time, memory & nature',
    mnemonic: 'GAGAN (sky) waits for BAHAR (spring) to arrive',
    context: 'Sahitya Akademi 2024 Hindi poetry winner',
    examProb: 'High',
  },
  {
    id: 52,
    title: 'Jnanpith 2025 — Vairamuthu',
    author: 'Vairamuthu',
    category: 'Literary Award',
    award: 'Jnanpith Award',
    year: '2025',
    theme: 'Tamil lyrical poetry — celebrated film lyricist & poet',
    mnemonic: 'VAIRA (diamond) MUTHU (pearl) shines in Jnanpith',
    context: 'Jnanpith 2025 (Tamil) — very high for 2026 exam',
    examProb: 'Hot',
  },
  {
    id: 53,
    title: 'Jnanpith 2024 — Vinod Kumar Shukla',
    author: 'Vinod Kumar Shukla',
    category: 'Literary Award',
    award: 'Jnanpith Award',
    year: '2024',
    theme: 'Hindi fiction & poetry — magical realism of rural life',
    mnemonic: 'VINOD\'s SHUKLA (white) world wins Jnanpith',
    context: 'Jnanpith 2024 (Hindi) — high for Tier 1 & 2 2025-26',
    examProb: 'High',
  },
  {
    id: 54,
    title: 'Jnanpith 2023 — Rambhadracharya & Gulzar',
    author: 'Rambhadracharya & Gulzar',
    category: 'Literary Award',
    award: 'Jnanpith Award',
    year: '2023',
    theme: 'Sanskrit scholarship (Rambhadracharya) & Urdu-Hindi verse (Gulzar)',
    mnemonic: 'RAM & GULZAR share the garden of Jnanpith',
    context: 'Dual Jnanpith 2023 — Sanskrit & Urdu winners, two languages angle',
    examProb: 'High',
  },

  // ── CURRENT AFFAIRS 2024 ────────────────────────────────────────────────────
  {
    id: 55,
    title: 'Why Bharat Matters',
    author: 'S. Jaishankar',
    category: 'Current Affairs',
    award: 'Political Non-fiction',
    year: '2023',
    theme: 'India\'s foreign policy & geopolitical vision by EAM',
    mnemonic: 'JAI (victory) of SHANKAR explains why BHARAT matters',
    context: 'By External Affairs Minister — diplomacy & foreign policy context',
    examProb: 'High',
  },
  {
    id: 56,
    title: 'India@100',
    author: 'Prof. K. V. Subramanian',
    category: 'Current Affairs',
    award: 'Economic Vision',
    year: '2024',
    theme: 'Economic blueprint for India\'s centenary — Viksit Bharat 2047',
    mnemonic: 'KVS maps INDIA at 100 years young',
    context: 'Viksit Bharat 2047 context — Former CEA\'s vision document',
    examProb: 'High',
  },
  {
    id: 57,
    title: 'Kargil War: The Turning Point',
    author: 'Late Col. M. B. Ravindranath',
    category: 'Current Affairs',
    award: 'Military History',
    year: '2024',
    theme: 'Kargil War 25th anniversary — tactical account of 1999 conflict',
    mnemonic: 'RAVI shows the TURNING point of KARGIL',
    context: '25 years of Kargil Vijay Diwas — July 2024 defence context',
    examProb: 'High',
  },
  {
    id: 58,
    title: 'Tipu Sultan: Saga of Mysore Interregnum',
    author: 'Vikram Sampath',
    category: 'Current Affairs',
    award: 'Historical Biography',
    year: '2024',
    theme: 'Biography of Tipu Sultan — Mysore wars & British conflict',
    mnemonic: 'VIKRAM SAMPS the TIPU saga of Mysore',
    context: 'Historical biography — December 2024 release',
    examProb: 'High',
  },
  {
    id: 59,
    title: 'Chhaunk: On Food, Economics, and Society',
    author: 'Abhijit Banerjee',
    category: 'Current Affairs',
    award: 'Nobel Laureate Work',
    year: '2024',
    theme: 'Food, economics & society through the lens of a Nobel laureate',
    mnemonic: 'BANERJEE adds CHHAUNK (tempering) to economics',
    context: 'Nobel Prize in Economics winner — December 2024',
    examProb: 'High',
  },
  {
    id: 60,
    title: 'Witness',
    author: 'Sakshi Malik',
    category: 'Current Affairs',
    award: 'Sports Memoir',
    year: '2024',
    theme: 'Wrestling autobiography — protest against WFI & women\'s rights',
    mnemonic: 'SAKSHI is a WITNESS to wrestling injustice',
    context: 'WFI protest controversy — October 2024; women in sports angle',
    examProb: 'High',
  },
  {
    id: 61,
    title: "Assam's Braveheart — Lachit Barphukon",
    author: 'Arup Kumar Dutta',
    category: 'Current Affairs',
    award: 'Regional Historical Biography',
    year: '2024',
    theme: 'Ahom general who defeated Mughal forces at Battle of Saraighat',
    mnemonic: 'LACHIT the BRAVEHEART repels Mughal BARRAGE',
    context: 'National hero centenary celebrations — Assam history',
    examProb: 'Medium',
  },

  // ── CURRENT AFFAIRS 2025 ────────────────────────────────────────────────────
  {
    id: 62,
    title: 'Operation Sindoor',
    author: 'Lt Gen K. J. S. Dhillon',
    category: 'Current Affairs',
    award: 'Military Operations Account',
    year: '2025',
    theme: 'India\'s surgical strikes inside Pakistan — 2025 military operation',
    mnemonic: 'DHILLON leads the SINDOOR operation inside Pakistan',
    context: 'September 2025 — extremely high for 2026 CGL due to current significance',
    examProb: 'Hot',
  },
  {
    id: 63,
    title: 'Why the Constitution Matters',
    author: 'Former CJI D. Y. Chandrachud',
    category: 'Current Affairs',
    award: 'Constitutional Law',
    year: '2025',
    theme: 'Constitutional values & democratic foundations of India',
    mnemonic: 'CHANDRACHUD (moon) shines light on CONSTITUTION',
    context: 'By former Chief Justice — July 2025; Polity + constitutional angle',
    examProb: 'Hot',
  },
  {
    id: 64,
    title: 'Wings to Our Hopes — Vol. II',
    author: 'President Droupadi Murmu',
    category: 'Current Affairs',
    award: 'Presidential Speeches Compilation',
    year: '2025',
    theme: 'Compilation of speeches — India\'s first tribal woman president',
    mnemonic: 'MURMU gives WINGS to tribal HOPES',
    context: 'Launched by President — June 2025; tribal & presidential angle',
    examProb: 'Hot',
  },
  {
    id: 65,
    title: 'Ready, Relevant and Resurgent — Vol. II',
    author: 'Gen. Anil Chauhan (CDS)',
    category: 'Current Affairs',
    award: 'Defence Strategy',
    year: '2025',
    theme: 'Future of Indian armed forces — defence modernisation vision',
    mnemonic: 'CDS CHAUHAN is READY and RESURGENT',
    context: 'By Chief of Defence Staff — October 2025; defence strategy',
    examProb: 'Hot',
  },
  {
    id: 66,
    title: 'Different But No Less',
    author: 'Anupam Kher',
    category: 'Current Affairs',
    award: 'Motivational Memoir',
    year: '2025',
    theme: 'Social inclusion, mental health & overcoming self-doubt',
    mnemonic: 'KHER is DIFFERENT but no less a star',
    context: 'July 2025 — motivational/social angle',
    examProb: 'High',
  },
  {
    id: 67,
    title: 'The Great Sanctions Hack',
    author: 'Urjit Patel',
    category: 'Current Affairs',
    award: 'Economic Policy',
    year: '2025',
    theme: 'Global sanctions & their economic bypass mechanisms',
    mnemonic: 'PATEL HACKS through global SANCTIONS',
    context: 'Former RBI Governor — November 2025; economics angle',
    examProb: 'High',
  },
  {
    id: 68,
    title: 'The One: Cricket, My Life and More',
    author: 'Shikhar Dhawan',
    category: 'Current Affairs',
    award: 'Sports Memoir',
    year: '2025',
    theme: 'Cricket autobiography — Gabbar\'s journey & retirement reflections',
    mnemonic: 'GABBAR (Dhawan) is THE ONE who opens with style',
    context: 'December 2025 — retirement news adds exam probability',
    examProb: 'High',
  },
  {
    id: 69,
    title: 'Mother Mary Comes to Me in Kochi',
    author: 'Arundhati Roy',
    category: 'Current Affairs',
    award: 'Modern Literary Fiction',
    year: '2025',
    theme: 'Contemporary Kerala society — faith, politics & personal memory',
    mnemonic: 'ROY meets MARY in KOCHI — two books, one Booker author',
    context: 'September 2025 — by Booker Prize winner Arundhati Roy',
    examProb: 'High',
  },

  // ── CURRENT AFFAIRS 2026 ────────────────────────────────────────────────────
  {
    id: 70,
    title: 'Atal Bihari Vajpayee: The Eternal Statesman',
    author: 'Vijay Goel',
    category: 'Current Affairs',
    award: 'Biography (Launched by VP)',
    year: 'Feb 2026',
    theme: 'Biography of former PM Vajpayee — statesman & poet',
    mnemonic: 'GOEL\'s VAJPAYEE is ETERNAL like his poetry',
    context: 'Launched by VP Jagdeep Dhankhar — 23 Feb 2026; HOT for Tier 2',
    examProb: 'Hot',
  },
  {
    id: 71,
    title: 'The Sage Who Reimagined Hinduism',
    author: 'Shashi Tharoor',
    category: 'Current Affairs',
    award: 'Religious Biography (Launched by VP)',
    year: 'Feb 2026',
    theme: 'Legacy of Sree Narayana Guru — social reformer of Kerala',
    mnemonic: 'THAROOR\'s SAGE reimagines HINDUISM for modernity',
    context: 'Launched by VP — 20 Feb 2026; social reform + Kerala angle',
    examProb: 'Hot',
  },
  {
    id: 72,
    title: 'Bakshi Jagabandhu: The Great Commander',
    author: 'Biswabhusan Harichandan',
    category: 'Current Affairs',
    award: 'Regional History',
    year: 'Feb 2026',
    theme: 'Hero of Odisha\'s Paika Rebellion against British rule',
    mnemonic: 'JAGABANDHU the GREAT commands the Paika REBELLION',
    context: '10 Feb 2026 — Paika Rebellion 200th year; Odisha history',
    examProb: 'Hot',
  },
  {
    id: 73,
    title: 'The Medicolegal Guidebook',
    author: 'Arjun Ram Meghwal (Minister)',
    category: 'Current Affairs',
    award: 'Legal-Medical Reference',
    year: 'Feb 2026',
    theme: 'Bridge between medicine and law — forensic & legal medicine',
    mnemonic: 'MEGHWAL bridges MEDICO (medicine) and LEGAL worlds',
    context: 'Launched by Law Minister — 09 Feb 2026',
    examProb: 'Hot',
  },
  {
    id: 74,
    title: 'AI-Preneurs of India',
    author: 'AIM, NITI Aayog',
    category: 'Current Affairs',
    award: 'Technology Report',
    year: 'Feb 2026',
    theme: 'Journeys of 45 AI startups — India\'s AI ecosystem',
    mnemonic: 'NITI AAYOG presents AI-PRENEURS of INDIA',
    context: 'NITI Aayog / MeitY — Feb 2026; AI + startup + governance angle',
    examProb: 'Hot',
  },

  // ── NEW ADDITIONS (from updated CSV analysis) ──────────────────────────────

  // Literary Awards — added
  {
    id: 75,
    title: 'Orbital',
    author: 'Samantha Harvey',
    category: 'Literary Award',
    award: 'Booker Prize',
    year: '2024',
    theme: 'Six astronauts orbiting Earth — meditative fiction on time & beauty',
    mnemonic: 'HARVEY sends six souls into ORBIT for Booker',
    context: 'Booker Prize 2024 — high probability for 2025-26 CGL',
    examProb: 'Hot',
  },
  {
    id: 76,
    title: 'The Burning Earth',
    author: 'Sunil Amrith',
    category: 'Literary Award',
    award: 'British Academy Book Prize',
    year: '2025',
    theme: 'Environmental history of South Asia over the last 500 years',
    mnemonic: 'AMRITH watches the BURNING EARTH\'s 500-year history',
    context: 'British Academy Book Prize 2025 — environment + history angle',
    examProb: 'High',
  },
  {
    id: 77,
    title: 'Phir Ugna',
    author: 'Parvati Tirkey',
    category: 'Literary Award',
    award: 'Sahitya Akademi Yuva Puraskar',
    year: '2025',
    theme: 'Contemporary Indian literature — tribal voice, resilience & rebirth',
    mnemonic: 'TIRKEY\'s PHIR UGNA (grow again) rises from Jharkhand soil',
    context: 'Sahitya Akademi Yuva Puraskar 2025 — regional + tribal angle; HOT',
    examProb: 'Hot',
  },
  {
    id: 78,
    title: 'Wild Fictions',
    author: 'Amitav Ghosh',
    category: 'Literary Award',
    award: 'Jnanpith Award (Author, 2018)',
    year: '2025',
    theme: 'Essays on climate crisis, nature & modern environmental literature',
    mnemonic: 'GHOSH writes WILD FICTIONS about nature\'s revenge',
    context: 'By Jnanpith & Commonwealth Prize winner — environmental literature',
    examProb: 'High',
  },

  // Sports — added
  {
    id: 79,
    title: 'Bring It On: The Incredible Story of My Life',
    author: 'Deepa Malik',
    category: 'Sports',
    award: 'Padma Shri (Author)',
    year: '2025',
    theme: 'Para-athlete memoir — first Indian woman to win Paralympic silver medal',
    mnemonic: 'DEEPA MALIK says BRING IT ON to every obstacle',
    context: 'First Indian woman Paralympic medalist — sports + disability angle',
    examProb: 'High',
  },
  {
    id: 80,
    title: 'Tested: The Remarkable Power of Resolve',
    author: 'Pat Cummins',
    category: 'Sports',
    award: 'Sports Memoir',
    year: '2025',
    theme: 'Resilience & leadership in cricket — Australia captain\'s philosophy',
    mnemonic: 'CUMMINS is TESTED as captain and human being',
    context: 'Australia cricket captain memoir — international sports figure',
    examProb: 'Medium',
  },
  {
    id: 81,
    title: 'The Rise of the Hitman',
    author: 'R. Kaushik',
    category: 'Sports',
    award: 'Sports Biography',
    year: '2025',
    theme: 'Biography of Rohit Sharma — from Bandra to becoming Test captain',
    mnemonic: 'KAUSHIK writes ROHIT\'s RISE as India\'s HITMAN',
    context: 'Rohit Sharma biography — runs + ODI World Cup + captaincy angle',
    examProb: 'High',
  },
  {
    id: 82,
    title: 'March of Glory',
    author: 'K. Arumugam',
    category: 'Sports',
    award: 'Sports History',
    year: '2025',
    theme: 'India\'s 1975 Hockey World Cup triumph — Ajit Pal Singh\'s team',
    mnemonic: 'ARUMUGAM records India\'s GLORY MARCH to 1975 Hockey gold',
    context: '50th anniversary of 1975 Hockey World Cup — national sport history',
    examProb: 'High',
  },
  {
    id: 83,
    title: 'Stumped',
    author: 'Syed Kirmani',
    category: 'Sports',
    award: 'Padma Sri (Author)',
    year: '2024',
    theme: 'Memoir of India\'s legendary 1983 World Cup wicketkeeper',
    mnemonic: 'KIRMANI is STUMPED by how far cricket took him',
    context: '1983 World Cup hero memoir — Kapil Dev\'s team angle',
    examProb: 'Medium',
  },

  // PYQ / Historical Fiction — added
  {
    id: 84,
    title: 'The Chola Tigers: Avengers of Somnath',
    author: 'Amish Tripathi',
    category: 'PYQ',
    award: 'Popular Historical Fiction',
    year: '2025',
    theme: 'Historical fiction — Chola Dynasty avenging the Somnath invasion',
    mnemonic: 'AMISH\'s CHOLA TIGERS roar for Somnath revenge',
    context: 'Amish Tripathi (former Nehru Centre Director — SSC PYQ Apr 2021)',
    examProb: 'High',
  },

  // Current Affairs 2024-2025 — added
  {
    id: 85,
    title: 'Operation Sindhu',
    author: 'Kanwaljit Singh Dhillon',
    category: 'Current Affairs',
    award: 'Military Affairs',
    year: '2025',
    theme: 'Strategic response after Pahalgam terror attack — military narrative',
    mnemonic: 'DHILLON\'s SINDHU flows after Pahalgam\'s tragedy',
    context: 'Post-Pahalgam attack context — 2025; extremely HOT for CGL 2026',
    examProb: 'Hot',
  },
  {
    id: 86,
    title: 'M.S. Swaminathan: The Man Who Fed India',
    author: 'Priyambara Jayakumar',
    category: 'Current Affairs',
    award: 'Biography',
    year: '2025',
    theme: 'Biography of M.S. Swaminathan — Father of India\'s Green Revolution',
    mnemonic: 'JAYAKUMAR writes how SWAMINATHAN FED a billion Indians',
    context: 'Green Revolution + agriculture angle; Swaminathan received Bharat Ratna 2024',
    examProb: 'Hot',
  },
  {
    id: 87,
    title: 'Janata Ki Kahani: Meri Atmakatha',
    author: 'Bandaru Dattatreya',
    category: 'Current Affairs',
    award: 'Autobiography',
    year: '2025',
    theme: 'Autobiography of Bandaru Dattatreya — former Governor of Himachal Pradesh',
    mnemonic: 'DATTATREYA tells JANATA\'s KAHANI in his atmakatha',
    context: 'Former Governor autobiography — Governor + politics angle',
    examProb: 'Medium',
  },
  {
    id: 88,
    title: 'Believer\'s Dilemma',
    author: 'Abhishek Choudhary',
    category: 'Current Affairs',
    award: 'Political Analysis',
    year: '2025',
    theme: 'Vajpayee and the Hindu Right (1977–2018) — political history',
    mnemonic: 'CHOUDHARY\'s BELIEVER faces VAJPAYEE\'s political DILEMMA',
    context: 'Vajpayee centenary year 2024-25 — BJP political history angle',
    examProb: 'High',
  },
  {
    id: 89,
    title: 'PMO: Prime Minister\'s Office Through the Years',
    author: 'Himanshu Roy',
    category: 'Current Affairs',
    award: 'Institutional History',
    year: '2025',
    theme: 'Historical evolution of the Prime Minister\'s Office — governance',
    mnemonic: 'ROY traces the PMO\'s power through Indian history',
    context: 'Governance + polity angle — PMO institutional history',
    examProb: 'High',
  },
  {
    id: 90,
    title: 'India: 5000 Years of History',
    author: 'Audrey Truschke',
    category: 'Current Affairs',
    award: 'Historical Non-fiction',
    year: '2025',
    theme: 'Comprehensive history of the Indian subcontinent across 5000 years',
    mnemonic: 'TRUSCHKE tracks INDIA\'s 5000-year civilisational march',
    context: 'International scholar on India — history + Mughal period angle',
    examProb: 'High',
  },
  {
    id: 91,
    title: 'India\'s Finance Ministers (1998–2014)',
    author: 'A. K. Bhattacharya',
    category: 'Current Affairs',
    award: 'Political Economy',
    year: '2024',
    theme: 'Profiles and economic policies of India\'s Finance Ministers 1998–2014',
    mnemonic: 'BHATTACHARYA profiles the FINANCE MINISTERS of India',
    context: 'Economic history + governance — FM profiles from Vajpayee era',
    examProb: 'Medium',
  },
  {
    id: 92,
    title: 'The Man Who Became Cinema: Dilip Kumar',
    author: 'Ashok Chopra',
    category: 'Current Affairs',
    award: 'Film Biography',
    year: '2025',
    theme: 'Biography of Dilip Kumar — the tragedy king who became Indian cinema',
    mnemonic: 'CHOPRA captures DILIP becoming CINEMA itself',
    context: 'Padma Vibhushan & Dadasaheb Phalke awardee biography',
    examProb: 'Medium',
  },
  {
    id: 93,
    title: 'Ramanujan: Journey of a Great Mathematician',
    author: 'Arun Singhal',
    category: 'Current Affairs',
    award: 'Scientific Biography',
    year: '2025',
    theme: 'Biography of Srinivasa Ramanujan — self-taught mathematical genius',
    mnemonic: 'SINGHAL charts RAMANUJAN\'s journey from Kumbakonam to Cambridge',
    context: 'National Mathematics Day (Dec 22) context — recurring topic in GK',
    examProb: 'High',
  },
  {
    id: 94,
    title: 'A Different Kind of Power',
    author: 'Jacinda Ardern',
    category: 'Current Affairs',
    award: 'Political Memoir',
    year: '2025',
    theme: 'Memoir of Jacinda Ardern — empathetic leadership & New Zealand politics',
    mnemonic: 'ARDERN leads with a DIFFERENT KIND of power — empathy',
    context: 'International political leader — women leadership angle',
    examProb: 'Medium',
  },
  {
    id: 95,
    title: 'The Great Conciliator',
    author: 'Sanjeev Chopra',
    category: 'Current Affairs',
    award: 'Political Biography',
    year: '2025',
    theme: 'Lal Bahadur Shastri and India\'s transformation — statesman biography',
    mnemonic: 'CHOPRA\'s SHASTRI is India\'s GREAT CONCILIATOR',
    context: 'Lal Bahadur Shastri centenary — "Jai Jawan Jai Kisan" angle',
    examProb: 'High',
  },
  {
    id: 96,
    title: 'Parliament: Power, Function and Privileges',
    author: 'K. S. Chauhan',
    category: 'Current Affairs',
    award: 'Constitutional Reference',
    year: '2025',
    theme: 'Analysis of Indian Parliamentary system — powers, functions, privileges',
    mnemonic: 'CHAUHAN unlocks PARLIAMENT\'s POWER, FUNCTIONS and PRIVILEGES',
    context: 'Polity + constitutional law — high value for GA + descriptive paper',
    examProb: 'Medium',
  },
  {
    id: 97,
    title: 'The World After Gaza: A History',
    author: 'Pankaj Mishra',
    category: 'Current Affairs',
    award: 'International Affairs',
    year: '2025',
    theme: 'Geopolitics and modern history in the context of the Gaza crisis',
    mnemonic: 'MISHRA envisions the WORLD AFTER GAZA\'s ruins',
    context: 'International affairs — geopolitics angle for Current Affairs section',
    examProb: 'Medium',
  },
  {
    id: 98,
    title: 'Speaking with Nature',
    author: 'Ramachandra Guha',
    category: 'Current Affairs',
    award: 'Environmental History',
    year: '2025',
    theme: 'Origins of Indian environmentalism — nature, ecology & Indian thought',
    mnemonic: 'GUHA SPEAKS with NATURE through India\'s green conscience',
    context: 'By notable Indian historian & environmentalist — ecology + history',
    examProb: 'Medium',
  },
]
