export type PolityCategory =
  | 'Important Articles'
  | 'Schedules'
  | 'Amendments'
  | 'Landmark Cases'
  | 'Constitutional Bodies'
  | 'Parliament & Executive'
  | 'Fundamental Rights & DPSP'

export type ExamProb = 'Hot' | 'High' | 'Confirmed' | 'Recurring'

export interface PolityEntry {
  id: number
  category: PolityCategory
  topic: string           // e.g. "Article 32", "10th Schedule"
  question: string        // SSC-style question
  answer: string          // direct answer
  shortcut: string        // ONE-LINE memory trick / shortcut
  detail: string          // brief explanation (2-3 lines max)
  context: string         // PYQ date or 'SSC CGL standard'
  examProb: ExamProb
}

export interface PolityPYQEntry {
  date: string
  shift: string
  question: string
  answer: string
  category: PolityCategory
}

export const polityData: PolityEntry[] = [

  // ═══════════════════════════════════════════════════════════
  // IMPORTANT ARTICLES
  // ═══════════════════════════════════════════════════════════
  {
    id: 1, category: 'Important Articles', topic: 'Article 1',
    question: 'What does Article 1 of the Indian Constitution declare?',
    answer: 'India, that is Bharat, shall be a Union of States',
    shortcut: 'Art 1 = India = Union of States (NOT federation)',
    detail: 'Uses "Union" not "Federation" — shows indestructibility of union. States cannot secede.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
  },
  {
    id: 2, category: 'Important Articles', topic: 'Article 12',
    question: 'What does Article 12 define in the Indian Constitution?',
    answer: 'Definition of "State" for Part III (Fundamental Rights)',
    shortcut: 'Art 12 = "State" definition → includes Govt, Parliament, State legislatures, local bodies',
    detail: 'Crucial for FR enforcement. SC, PSUs, universities can be "State" under Art 12 if they perform public functions.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 3, category: 'Important Articles', topic: 'Article 13',
    question: 'Article 13 declares any law violating Fundamental Rights as what?',
    answer: 'Void (null and void)',
    shortcut: 'Art 13 = Judicial Review power — FR trump all laws',
    detail: 'Art 13(1): pre-constitutional laws inconsistent with FRs are void. Art 13(2): State shall not make laws abridging FRs.',
    context: 'SSC CGL 2022–23', examProb: 'High',
  },
  {
    id: 4, category: 'Important Articles', topic: 'Article 14',
    question: 'Article 14 guarantees which right?',
    answer: 'Right to Equality before law and equal protection of laws',
    shortcut: 'Art 14 = Equality before law (British) + Equal protection (US-borrowed)',
    detail: 'Two concepts: equality before law (negative concept) and equal protection of laws (positive concept). No unreasonable classification.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
  },
  {
    id: 5, category: 'Important Articles', topic: 'Article 15',
    question: 'Article 15 prohibits discrimination on which grounds?',
    answer: 'Religion, Race, Caste, Sex, Place of Birth',
    shortcut: 'Art 15 = RRCSB — Religion Race Caste Sex Birth',
    detail: 'Art 15(3): special provision for women/children. Art 15(4)/(5): reservations for SC/ST/OBC. Art 15(6): EWS reservation.',
    context: 'SSC CGL 2024', examProb: 'Hot',
  },
  {
    id: 6, category: 'Important Articles', topic: 'Article 16',
    question: 'Article 16 guarantees equality of opportunity in which matters?',
    answer: 'Public employment (government jobs)',
    shortcut: 'Art 16 = Equal opportunity in GOVT JOBS; Art 16(4) = reservations for backward classes',
    detail: 'Art 16(4A): reservation in promotion for SC/ST. Art 16(4B): carry-forward of unfilled reserved vacancies.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 7, category: 'Important Articles', topic: 'Article 17',
    question: 'Article 17 deals with abolition of what?',
    answer: 'Untouchability',
    shortcut: 'Art 17 = Untouchability ABOLISHED — absolute right, no exceptions',
    detail: 'Untouchability Offences Act 1955 (later Protection of Civil Rights Act). Only FR with no exceptions.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
  },
  {
    id: 8, category: 'Important Articles', topic: 'Article 19',
    question: 'Article 19(1)(a) guarantees which freedom?',
    answer: 'Freedom of speech and expression',
    shortcut: 'Art 19 = Six freedoms: SCAPE+R (Speech, Assembly, Assoc, Profession, Residence, Employment gone)',
    detail: 'Originally 7 freedoms; right to property (19(1)(f)) removed by 44th Amendment 1978. Reasonable restrictions under Art 19(2).',
    context: 'SSC CGL 2024', examProb: 'Hot',
  },
  {
    id: 9, category: 'Important Articles', topic: 'Article 20',
    question: 'Article 20 provides protection against what in criminal matters?',
    answer: 'Ex post facto laws, double jeopardy, self-incrimination',
    shortcut: 'Art 20 = 3 protections: No retrospective punishment + No double trial + No self-testimony',
    detail: 'Art 20 cannot be suspended even during Emergency (along with Art 21). Absolute protection.',
    context: 'SSC CGL 2023 Shift 2', examProb: 'Confirmed',
  },
  {
    id: 10, category: 'Important Articles', topic: 'Article 21',
    question: 'Article 21 guarantees which right, and what has the Supreme Court expanded it to include?',
    answer: 'Right to life and personal liberty; expanded to 30+ rights including right to education, health, privacy',
    shortcut: 'Art 21 = Most expansive FR — includes right to die with dignity, privacy (Puttaswamy), livelihood',
    detail: 'Cannot be suspended even during Emergency. Maneka Gandhi case (1978) broadened "procedure established by law" to just, fair and reasonable.',
    context: 'SSC CGL 2024', examProb: 'Hot',
  },
  {
    id: 11, category: 'Important Articles', topic: 'Article 21A',
    question: 'Article 21A was inserted by which amendment and provides what right?',
    answer: '86th Amendment 2002 — Free and compulsory education for children aged 6–14',
    shortcut: 'Art 21A = 86th Amend = RTE for 6–14 years',
    detail: 'Right to Education Act 2009 enacted under Art 21A. Made education a Fundamental Right (not just DPSP).',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 12, category: 'Important Articles', topic: 'Article 22',
    question: 'Article 22 provides protection against which kind of arrest?',
    answer: 'Arbitrary arrest and detention (right to be informed of grounds, right to legal counsel, Magistrate within 24 hours)',
    shortcut: 'Art 22 = 24-hour rule + Lawyer right + Inform of grounds',
    detail: 'Art 22(4)–(7) allows preventive detention up to 3 months. Cannot be suspended in Emergency for foreign nationals.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 13, category: 'Important Articles', topic: 'Article 32',
    question: 'Article 32 is called the "heart and soul of the Constitution" — by whom and what does it provide?',
    answer: 'Dr. B.R. Ambedkar called it so. It gives the right to move the Supreme Court for enforcement of Fundamental Rights.',
    shortcut: 'Art 32 = Heart & Soul (Ambedkar) = SC can issue 5 writs',
    detail: '5 writs: Habeas Corpus, Mandamus, Prohibition, Certiorari, Quo Warranto. Art 32 itself is a FR — cannot be suspended (except Art 359 during Emergency).',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
  },
  {
    id: 14, category: 'Important Articles', topic: 'Article 36–51',
    question: 'Articles 36–51 contain Directive Principles of State Policy (DPSP). They are borrowed from which Constitution?',
    answer: 'Irish Constitution (Ireland)',
    shortcut: 'DPSP = Irish origin, non-justiciable but fundamental in governance',
    detail: 'Three types: Socialistic (39, 41, 42), Gandhian (40, 43, 46–48), Liberal-Intellectual (44, 45, 50). State must implement but courts cannot enforce them.',
    context: 'SSC CGL 2022–23', examProb: 'High',
  },
  {
    id: 15, category: 'Important Articles', topic: 'Article 39B/C',
    question: 'Article 39B and 39C deal with what directive principle?',
    answer: 'Distribution of material resources to sub-serve common good; prevention of concentration of wealth',
    shortcut: 'Art 39B/C = No wealth hoarding — spread resources = socialist principle',
    detail: 'Used to justify nationalisation. Art 31C (42nd Amend) gave protection to laws implementing Art 39B/C. Confirmed in Minerva Mills case.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 16, category: 'Important Articles', topic: 'Article 44',
    question: 'Article 44 of DPSP directs the State to secure what?',
    answer: 'Uniform Civil Code (UCC) for all citizens',
    shortcut: 'Art 44 = UCC — one law for all personal matters regardless of religion',
    detail: 'Still not implemented fully. Goa has a partial UCC. Shah Bano case (1985) reignited debate. Recently Uttarakhand enacted UCC (2024).',
    context: 'SSC CGL 2024', examProb: 'Hot',
  },
  {
    id: 17, category: 'Important Articles', topic: 'Article 51A',
    question: 'Article 51A was added by which amendment and contains what?',
    answer: '42nd Amendment 1976 — Fundamental Duties (11 duties)',
    shortcut: 'Art 51A = 11 FDs, added by 42nd Amend (Swaran Singh Committee). 11th duty by 86th Amend 2002.',
    detail: 'Originally 10 FDs; 11th (educate children) added by 86th Amendment. Non-justiciable but aid in interpreting laws.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 18, category: 'Important Articles', topic: 'Article 72',
    question: 'Article 72 gives which power to the President of India?',
    answer: 'Pardon power — to grant pardons, reprieves, respites, remissions, commutations',
    shortcut: 'Art 72 = President pardons (incl. death sentence) | Art 161 = Governor pardons (excl. death sentence)',
    detail: 'President can pardon death sentence; Governor cannot. Kehar Singh case: President\'s pardon power is reviewable by SC.',
    context: 'SSC CGL 2023–24', examProb: 'High',
  },
  {
    id: 19, category: 'Important Articles', topic: 'Article 74',
    question: 'What does Article 74 state about the Council of Ministers?',
    answer: 'Council of Ministers headed by PM shall aid and advise the President; President shall act on such advice',
    shortcut: 'Art 74 = PM + CoM advise President; President MUST follow (44th Amend made advice binding)',
    detail: '44th Amendment 1978 made CoM advice binding on President. Art 75: Ministers are collectively responsible to Lok Sabha.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 20, category: 'Important Articles', topic: 'Article 110',
    question: 'Article 110 defines what type of bill?',
    answer: 'Money Bill — deals only with taxation, borrowing, custody of funds, expenditure from Consolidated Fund',
    shortcut: 'Art 110 = Money Bill definition; Speaker certifies it; Rajya Sabha can only recommend, not reject',
    detail: 'Rajya Sabha has 14 days to return Money Bill with recommendations; Lok Sabha can accept or reject. Rajya Sabha cannot amend.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 21, category: 'Important Articles', topic: 'Article 112',
    question: 'What is the Annual Financial Statement under Article 112 called?',
    answer: 'Union Budget (Annual Financial Statement)',
    shortcut: 'Art 112 = Union Budget laid before Parliament annually',
    detail: 'Estimates of receipts and expenditure. Voted and non-voted expenditure. Charged expenditure (salary of President, Judges) not voted.',
    context: 'SSC CGL standard', examProb: 'High',
  },
  {
    id: 22, category: 'Important Articles', topic: 'Article 123',
    question: 'Under Article 123, when can the President promulgate an Ordinance?',
    answer: 'When Parliament is not in session and immediate action is needed',
    shortcut: 'Art 123 = President Ordinance when Parliament not in session; valid 6 weeks after reassembly',
    detail: 'Ordinance has same force as Parliament Act but is temporary. Must be placed before Parliament when it reassembles. Lapses after 6 weeks.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 23, category: 'Important Articles', topic: 'Article 148',
    question: 'Article 148 deals with which constitutional authority?',
    answer: 'Comptroller and Auditor General of India (CAG)',
    shortcut: 'Art 148 = CAG; removed like SC judge; guardian of public purse',
    detail: 'CAG audits all accounts of Union and States. Reports submitted to President/Governor who places them before Parliament/Legislature.',
    context: 'SSC CGL 2022–24', examProb: 'High',
  },
  {
    id: 24, category: 'Important Articles', topic: 'Article 155',
    question: 'How is the Governor of a State appointed under Article 155?',
    answer: 'By the President (on advice of PM/Council of Ministers)',
    shortcut: 'Art 155 = Governor appointed by President; Art 156 = holds office during pleasure of President',
    detail: 'Governor is agent of Centre in State. Sarkaria Commission recommended Governor should be prominent person not from state political life.',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 25, category: 'Important Articles', topic: 'Article 163',
    question: 'Article 163 provides for a Council of Ministers to aid and advise the Governor — when can the Governor act independently?',
    answer: 'When Constitution requires him to act in his discretion',
    shortcut: 'Art 163 = Governor has discretion unlike President who must follow advice always',
    detail: 'Areas of discretion: reservation of bills for President, dismissal of CM if no majority, appointment of CM when no clear majority.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 26, category: 'Important Articles', topic: 'Article 214',
    question: 'Article 214 states there shall be a High Court for each State — which article gives HC power of judicial review?',
    answer: 'Article 226 — HC can issue writs to any person/authority in its territory',
    shortcut: 'Art 214 = HC for each State; Art 226 = HC writ power (WIDER than SC Art 32)',
    detail: 'HC under Art 226 can issue writs for ANY legal right (not just FRs), making its writ power broader than SC\'s Art 32.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 27, category: 'Important Articles', topic: 'Article 243',
    question: 'Part IX (Articles 243–243O) deals with which bodies, inserted by which amendment?',
    answer: 'Panchayati Raj Institutions (PRIs); 73rd Constitutional Amendment 1992',
    shortcut: 'Art 243 = Panchayati Raj by 73rd Amend; 3-tier: Gram, Panchayat Samiti, Zila Parishad',
    detail: '73rd Amend = rural local bodies; 74th Amend (Art 243P–243ZG) = urban local bodies (Municipalities). Both added 11th/12th Schedule.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 28, category: 'Important Articles', topic: 'Article 280',
    question: 'Article 280 provides for which body that recommends devolution of taxes?',
    answer: 'Finance Commission — constituted every 5 years by President',
    shortcut: 'Art 280 = Finance Commission; 16th FC due 2026; recommends Centre-State tax sharing',
    detail: 'Finance Commission recommends sharing of divisible pool (tax revenues) between Centre and States, and grants-in-aid. Non-binding but usually accepted.',
    context: 'SSC CGL 2024', examProb: 'Hot',
  },
  {
    id: 29, category: 'Important Articles', topic: 'Article 300A',
    question: 'After the 44th Amendment 1978, the right to property became what under Article 300A?',
    answer: 'A Constitutional Right (legal right), not a Fundamental Right',
    shortcut: 'Art 300A = Property = Legal right only after 44th Amend; earlier Art 19(1)(f) + Art 31',
    detail: 'Right to property removed from Part III by 44th Amendment. Now only a legal right — violations can be challenged in HC but penalties are weaker.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 30, category: 'Important Articles', topic: 'Article 312',
    question: 'Article 312 authorises the creation of which services?',
    answer: 'All India Services (IAS, IPS, IFoS) by Rajya Sabha resolution',
    shortcut: 'Art 312 = All India Services authorised by Rajya Sabha (not Lok Sabha)',
    detail: 'Rajya Sabha can create new All India Services by 2/3rd majority resolution. Unusual — normally Rajya Sabha has lesser power.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 31, category: 'Important Articles', topic: 'Article 324',
    question: 'Article 324 vests superintendence of all elections in which body?',
    answer: 'Election Commission of India (ECI)',
    shortcut: 'Art 324 = ECI — superintendence, direction and control of all elections',
    detail: 'ECI covers elections to Parliament, State Legislatures, President and Vice-President. Not panchayat/municipal elections (those are State ECs).',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 32, category: 'Important Articles', topic: 'Article 352',
    question: 'Article 352 deals with which type of Emergency and who proclaims it?',
    answer: 'National Emergency (armed rebellion/external aggression); proclaimed by President on written advice of Cabinet',
    shortcut: 'Art 352 = National Emergency (War/Aggression/Armed Rebellion); approved by 2/3rd + absolute majority',
    detail: '44th Amend: changed "internal disturbance" to "armed rebellion". Must be approved by both Houses within 1 month. Lok Sabha can revoke by simple majority.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 33, category: 'Important Articles', topic: 'Article 356',
    question: 'Article 356 is also known as what, and when is it imposed?',
    answer: "President's Rule (State Emergency); when State government cannot function as per Constitution",
    shortcut: 'Art 356 = President\'s Rule in State; approved by Parliament within 2 months; max 3 years',
    detail: 'S.R. Bommai case (1994): floor test mandatory before dismissal of state govt. Misuse curbed after Bommai judgment.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 34, category: 'Important Articles', topic: 'Article 360',
    question: 'Article 360 deals with which type of Emergency?',
    answer: 'Financial Emergency — when financial stability/credit of India or any part is threatened',
    shortcut: 'Art 360 = Financial Emergency; never declared in India so far',
    detail: 'Only Emergency never used. President can direct States to reduce salaries, reserve Money Bills for his consideration during Financial Emergency.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 35, category: 'Important Articles', topic: 'Article 368',
    question: 'Article 368 deals with the power to amend the Constitution — which type of bills cannot be introduced in Rajya Sabha first?',
    answer: 'Money Bills cannot be introduced in Rajya Sabha; Constitutional Amendment Bills can be introduced in either House',
    shortcut: 'Art 368 = Amendment power; Simple majority vs Special majority vs Ratification by States',
    detail: 'Three types: Simple majority (ordinary), Special majority (2/3rd present + absolute majority), Special majority + ratification by ½ States (federal provisions).',
    context: 'SSC CGL 2024', examProb: 'Hot',
  },

  // ═══════════════════════════════════════════════════════════
  // SCHEDULES
  // ═══════════════════════════════════════════════════════════
  {
    id: 36, category: 'Schedules', topic: '1st Schedule',
    question: 'What does the 1st Schedule of the Indian Constitution contain?',
    answer: 'Names of States and Union Territories and their territories',
    shortcut: '1st = States & UTs list; currently 28 States + 8 UTs',
    detail: 'Modified whenever a new state is created or boundaries change. J&K bifurcation (2019) reduced states from 29 to 28.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 37, category: 'Schedules', topic: '2nd Schedule',
    question: 'What does the 2nd Schedule contain?',
    answer: 'Salaries and allowances of President, Governors, Supreme Court/High Court Judges, CAG, Speaker/Deputy Speaker',
    shortcut: '2nd Schedule = SALARY SCHEDULE — big constitutional offices',
    detail: 'Salary of President (₹5 lakh/month), Governors (₹3.5 lakh), CJI (₹2.8 lakh). Charged on Consolidated Fund — not voted.',
    context: 'SSC CGL standard', examProb: 'High',
  },
  {
    id: 38, category: 'Schedules', topic: '3rd Schedule',
    question: 'What does the 3rd Schedule contain?',
    answer: 'Forms of oaths and affirmations for constitutional offices',
    shortcut: '3rd Schedule = OATH FORMS — swearing-in texts for President, Ministers, Judges, MPs',
    detail: 'Constitutional officers take oaths prescribed in 3rd Schedule. Members of Parliament take oath to bear allegiance to Constitution.',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 39, category: 'Schedules', topic: '4th Schedule',
    question: 'What does the 4th Schedule of the Constitution contain?',
    answer: 'Allocation of seats in Rajya Sabha for each State and UT',
    shortcut: '4th Schedule = Rajya Sabha seat allocation per State',
    detail: 'Rajya Sabha has 245 seats total (233 elected + 12 nominated by President for arts, literature, science, social service).',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 40, category: 'Schedules', topic: '5th Schedule',
    question: 'The 5th Schedule deals with administration of which areas?',
    answer: 'Scheduled Areas and Scheduled Tribes (except NE states)',
    shortcut: '5th Schedule = Scheduled Areas (non-NE states); Tribes Advisory Council; Governor has special powers',
    detail: 'Governor submits annual report to President. No demarcation criteria for Scheduled Area in Constitution — decided by Presidential Order.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 41, category: 'Schedules', topic: '6th Schedule',
    question: 'The 6th Schedule deals with which states specifically?',
    answer: 'Tribal areas in Assam, Meghalaya, Tripura and Mizoram — Autonomous District/Regional Councils',
    shortcut: '6th Schedule = AMTM (Assam, Meghalaya, Tripura, Mizoram) Autonomous Councils',
    detail: 'Autonomous District Councils have legislative, executive, judicial powers for tribals. Can make laws on land, forest use, money lending.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 42, category: 'Schedules', topic: '7th Schedule',
    question: 'What does the 7th Schedule contain and how many items are in each list?',
    answer: 'Three legislative lists: Union List (98 subjects), State List (59 subjects), Concurrent List (52 subjects)',
    shortcut: '7th Schedule = 3 Lists: Union 98, State 59, Concurrent 52 — REMEMBER: 98-59-52',
    detail: 'Residuary subjects vest with Centre (Art 248). In conflict: Centre wins on Concurrent List. Defence, foreign affairs, railways = Union List.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 43, category: 'Schedules', topic: '8th Schedule',
    question: 'How many languages are in the 8th Schedule of the Indian Constitution?',
    answer: '22 languages (originally 14; Sindhi added 1967, Konkani/Manipuri/Nepali by 71st Amend 1992, 4 more by 92nd Amend 2003)',
    shortcut: '8th Schedule = 22 Official languages; Latest 4: Bodo, Dogri, Maithili, Santhali (92nd Amend)',
    detail: 'These languages are recognised for official use. Official Language Commission looks at their spread. Sixth Schedule different from Eighth.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 44, category: 'Schedules', topic: '9th Schedule',
    question: 'The 9th Schedule was added by which amendment, and what is its significance?',
    answer: '1st Constitutional Amendment 1951 — laws placed in 9th Schedule were exempt from judicial review of FRs',
    shortcut: '9th Schedule = FR-proof shield for land reform laws; I.R. Coelho case (2007): SC can review if basic structure violated',
    detail: 'Contains 284 laws mainly related to land reforms and zamindari abolition. After I.R. Coelho, laws added after 24 April 1973 can be challenged if they violate basic structure.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 45, category: 'Schedules', topic: '10th Schedule',
    question: 'The 10th Schedule added by the 52nd Amendment 1985 is also known as?',
    answer: 'Anti-Defection Law',
    shortcut: '10th Schedule = Anti-Defection (52nd Amend 1985); Speaker/Chairman decides; 2/3rd merger exception',
    detail: 'Disqualification if: votes against party whip, voluntarily gives up membership. Exception: merger of 2/3rd members of original party.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 46, category: 'Schedules', topic: '11th Schedule',
    question: 'The 11th Schedule was added by which amendment and deals with what?',
    answer: '73rd Amendment 1992 — contains 29 subjects for Panchayati Raj Institutions',
    shortcut: '11th Schedule = 29 Panchayat subjects (73rd Amend); 12th Schedule = 18 Municipality subjects (74th Amend)',
    detail: 'Subjects include: agriculture, land improvement, minor irrigation, animal husbandry, fisheries, rural housing, education, public health.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 47, category: 'Schedules', topic: '12th Schedule',
    question: 'The 12th Schedule was added by which amendment?',
    answer: '74th Amendment 1992 — contains 18 subjects for Urban Local Bodies (Municipalities)',
    shortcut: '12th Schedule = 18 Municipality subjects; Wards Committees for cities >3 lakh population',
    detail: 'Urban planning, regulation of land use, public health, water supply, slum improvement, vital statistics are among the 18 subjects.',
    context: 'SSC CGL 2023', examProb: 'High',
  },

  // ═══════════════════════════════════════════════════════════
  // AMENDMENTS
  // ═══════════════════════════════════════════════════════════
  {
    id: 48, category: 'Amendments', topic: '1st Amendment 1951',
    question: 'What did the 1st Constitutional Amendment 1951 primarily do?',
    answer: 'Added 9th Schedule to protect land reform laws; added Art 15(4) for reservation for socially/educationally backward classes; added "public order" as restriction on free speech',
    shortcut: '1st Amend = 9th Schedule + OBC reservation + Free speech restrictions',
    detail: 'Passed to override Patna HC judgment in Kameshwar case that challenged zamindari abolition. First test of Parliament vs Judiciary.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 49, category: 'Amendments', topic: '7th Amendment 1956',
    question: 'The 7th Amendment 1956 reorganised states on what basis?',
    answer: 'Linguistic basis following States Reorganisation Act 1956 (Fazl Ali Commission)',
    shortcut: '7th Amend = States reorganised on LANGUAGE basis; abolished Part A/B/C/D categories',
    detail: 'Created 14 States and 6 UTs. Abolished the four-tier classification of states. Established principle of linguistic states.',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 50, category: 'Amendments', topic: '24th Amendment 1971',
    question: 'The 24th Amendment 1971 was passed to override which Supreme Court judgment?',
    answer: 'Golaknath case (1967) — which held Parliament cannot amend Part III (FRs)',
    shortcut: '24th Amend = overruled Golaknath; Parliament CAN amend FRs under Art 368; Art 13 does not apply to Art 368',
    detail: 'Added that President MUST give assent to Constitutional Amendment Bills. Kesavananda Bharati case (1973) later said basic structure still cannot be amended.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 51, category: 'Amendments', topic: '42nd Amendment 1976',
    question: 'The 42nd Amendment 1976 is called the "Mini Constitution" — what major changes did it make?',
    answer: 'Added Fundamental Duties (Art 51A), Preamble words "Socialist" + "Secular" + "Integrity", made DPSP supreme over FRs, added Preventive Detention, created Administrative Tribunals',
    shortcut: '42nd = MOST AMENDMENTS EVER; added Socialist+Secular+Integrity to Preamble; Swaran Singh Committee',
    detail: 'Passed during Emergency (1975–77). 59 changes. Many provisions reverted by 44th Amendment. Preamble changes retained permanently.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 52, category: 'Amendments', topic: '44th Amendment 1978',
    question: 'What major change did the 44th Amendment 1978 make to property rights?',
    answer: 'Removed Right to Property from Fundamental Rights (deleted Art 19(1)(f) and Art 31); property became only a legal right under Art 300A',
    shortcut: '44th Amend = Property right REMOVED from FRs; CoM advice BINDING on President; "armed rebellion" replaces "internal disturbance"',
    detail: 'Also reversed several 42nd Amendment excesses. Made CoM advice binding on President. Changed "internal disturbance" to "armed rebellion" in Art 352.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 53, category: 'Amendments', topic: '52nd Amendment 1985',
    question: 'The 52nd Amendment 1985 added which Schedule and deals with what?',
    answer: '10th Schedule — Anti-Defection Law to prevent floor crossing by elected members',
    shortcut: '52nd Amend = 10th Schedule = Anti-Defection; Rajiv Gandhi\'s govt; Kihoto Hollohan case validated it',
    detail: 'Kihoto Hollohan vs Zachillhu (1992): SC upheld Anti-Defection Law but said Speaker\'s decision is subject to judicial review.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 54, category: 'Amendments', topic: '61st Amendment 1988',
    question: 'The 61st Amendment 1988 reduced the voting age from 21 to what?',
    answer: '18 years (Art 326)',
    shortcut: '61st Amend = Voting age 21→18 years (Rajiv Gandhi govt)',
    detail: 'Reduced voting age to increase youth participation. Amended Art 326. First general election with 18-year voting was 1989.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
  },
  {
    id: 55, category: 'Amendments', topic: '73rd Amendment 1992',
    question: 'The 73rd Amendment 1992 gave constitutional status to which bodies?',
    answer: 'Panchayati Raj Institutions (PRIs) — Part IX added; 11th Schedule; State Finance Commission; Gram Sabha',
    shortcut: '73rd Amend = Panchayati Raj; Gram Sabha has constitutional status; elections by State EC',
    detail: 'Mandates elections every 5 years; 1/3 seats reserved for women; reservation for SC/ST. State Finance Commission every 5 years.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 56, category: 'Amendments', topic: '74th Amendment 1992',
    question: 'The 74th Amendment 1992 gave constitutional status to which bodies?',
    answer: 'Urban Local Bodies — Municipalities, Municipal Corporations, Nagar Panchayats; 12th Schedule',
    shortcut: '74th Amend = Urban bodies; Ward Committees for cities >3 lakh; 12th Schedule = 18 functions',
    detail: 'Three types: Nagar Panchayat (transitional), Municipal Council (smaller urban), Municipal Corporation (larger urban).',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 57, category: 'Amendments', topic: '86th Amendment 2002',
    question: 'The 86th Amendment 2002 inserted which article and added which Fundamental Duty?',
    answer: 'Art 21A (Right to Education 6–14 yrs); amended Art 45 (DPSP) to early childhood care; added 11th Fundamental Duty',
    shortcut: '86th Amend = Art 21A = RTE 6–14; 11th Fundamental Duty = educate your child',
    detail: 'Changed Art 45 from free education up to 14 to early childhood care for under-6. RTE Act 2009 enacted under Art 21A.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 58, category: 'Amendments', topic: '91st Amendment 2003',
    question: 'The 91st Amendment 2003 placed what limit on Council of Ministers?',
    answer: 'Council of Ministers (Centre + State) cannot exceed 15% of total strength of Lok Sabha/State Assembly',
    shortcut: '91st Amend = Cabinet size capped at 15%; also strengthened Anti-Defection law',
    detail: 'Also stated that member disqualified under Anti-Defection shall not be appointed as Minister. Minimum: 12 ministers.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 59, category: 'Amendments', topic: '101st Amendment 2016',
    question: 'The 101st Amendment 2016 introduced which major economic reform?',
    answer: 'Goods and Services Tax (GST) — Art 246A, Art 279A (GST Council)',
    shortcut: '101st Amend = GST; Art 246A = concurrent power for GST; GST Council has Centre + all States',
    detail: 'GST Council: Union Finance Minister as Chairperson; State Finance Ministers as members. Centre has 1/3rd vote; States have 2/3rd vote.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 60, category: 'Amendments', topic: '103rd Amendment 2019',
    question: 'The 103rd Amendment 2019 provided reservation for which group?',
    answer: 'Economically Weaker Sections (EWS) — 10% reservation in government jobs and educational institutions',
    shortcut: '103rd Amend = 10% EWS quota; added Art 15(6) and Art 16(6); income <₹8 lakh p.a.',
    detail: 'Upheld by SC in Janhit Abhiyan case (Nov 2022) 3:2 majority. Total reservation can now exceed 50% — diverges from Mandal Commission cap.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 61, category: 'Amendments', topic: '104th Amendment 2020',
    question: 'The 104th Amendment 2020 extended reservation for SC/ST in Lok Sabha and State Assemblies by how many years?',
    answer: '10 more years (until 2030)',
    shortcut: '104th Amend = SC/ST political reservation extended till 2030; Anglo-Indian nominated seats REMOVED',
    detail: 'Also abolished the nominated Anglo-Indian seats in Lok Sabha and State Assemblies (Art 331 and 333). Two-seat provision removed.',
    context: 'SSC CGL 2022–23', examProb: 'High',
  },
  {
    id: 62, category: 'Amendments', topic: '106th Amendment 2023',
    question: 'The 106th Amendment 2023 (Constitution 128th Amendment Bill) provides what?',
    answer: "Women's Reservation — 33% reservation for women in Lok Sabha, State Assemblies and Delhi Assembly",
    shortcut: '106th Amend = Nari Shakti Vandan Act = 33% Women reservation; effective after delimitation',
    detail: 'Added Art 330A and Art 332A. Reservation will be effective only after next delimitation exercise (after 2026 census). Reserved seats to rotate.',
    context: 'Current Affairs 2023', examProb: 'Hot',
  },

  // ═══════════════════════════════════════════════════════════
  // LANDMARK CASES
  // ═══════════════════════════════════════════════════════════
  {
    id: 63, category: 'Landmark Cases', topic: 'Kesavananda Bharati (1973)',
    question: 'What did the Kesavananda Bharati case 1973 establish?',
    answer: 'Basic Structure Doctrine — Parliament can amend any part of Constitution but cannot destroy its basic structure',
    shortcut: 'Kesavananda 1973 = BASIC STRUCTURE doctrine; 13-judge bench; 7:6 verdict',
    detail: 'Basic structure includes: supremacy of Constitution, republican & democratic form, secular character, separation of powers, federal character, judicial review, unity & integrity.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 64, category: 'Landmark Cases', topic: 'Maneka Gandhi (1978)',
    question: 'What did the Maneka Gandhi vs Union of India 1978 case establish?',
    answer: '"Procedure established by law" in Art 21 must be just, fair and reasonable (not merely technical/arbitrary)',
    shortcut: 'Maneka Gandhi 1978 = Art 21 + Due Process = law must be FAIR; expanded personal liberty enormously',
    detail: 'Overruled A.K. Gopalan case (1950) which gave narrow interpretation of Art 21. Now Art 14, 19, 21 must be read together.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 65, category: 'Landmark Cases', topic: 'S.R. Bommai (1994)',
    question: 'What did the S.R. Bommai case 1994 rule regarding President\'s Rule?',
    answer: 'Imposition of Art 356 is subject to judicial review; floor test must be conducted before dismissing state government; Secularism is part of basic structure',
    shortcut: 'S.R. Bommai 1994 = Art 356 not immune from review; floor test must come first; federalism basic structure',
    detail: 'Before Bommai, Centre frequently misused Art 356. After this case, President\'s Rule misuse drastically reduced. Also held secularism is basic structure.',
    context: 'SSC CGL 2023', examProb: 'Hot',
  },
  {
    id: 66, category: 'Landmark Cases', topic: 'Indra Sawhney (1992)',
    question: 'The Indra Sawhney case 1992 (Mandal Commission case) established which key principles?',
    answer: '50% ceiling on reservations; creamy layer exclusion for OBCs; reservations cannot apply to promotions',
    shortcut: 'Indra Sawhney = 50% cap on reservations; OBC creamy layer excluded; no reservation in promotion (Art 16(4A) later added exception for SC/ST)',
    detail: 'Upheld 27% OBC reservation. Set 50% overall cap (except extraordinary circumstances). Creamy layer concept introduced for OBCs.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 67, category: 'Landmark Cases', topic: 'Vishaka Guidelines (1997)',
    question: 'The Vishaka vs State of Rajasthan case 1997 established what?',
    answer: 'Guidelines against sexual harassment at workplace (before POSH Act); right against sexual harassment is part of Art 21',
    shortcut: 'Vishaka 1997 = Workplace sexual harassment guidelines; led to POSH Act 2013',
    detail: 'Bhanwari Devi gang rape case triggered PIL. SC laid down binding Vishaka Guidelines. Later replaced by Sexual Harassment of Women at Workplace Act 2013 (POSH).',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 68, category: 'Landmark Cases', topic: 'Puttaswamy (Right to Privacy 2017)',
    question: 'The K.S. Puttaswamy vs Union of India 2017 case held what?',
    answer: 'Right to Privacy is a Fundamental Right under Article 21 (9-judge bench unanimous)',
    shortcut: 'Puttaswamy 2017 = Privacy is FR under Art 21; 9-judge unanimous; overruled M.P. Sharma + Kharak Singh',
    detail: 'Laid foundation for data protection law. Privacy includes: informational privacy, bodily integrity, sexual orientation. DPDP Act 2023 follows from this.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 69, category: 'Landmark Cases', topic: 'Navtej Singh Johar (2018)',
    question: 'The Navtej Singh Johar case 2018 decriminalised what?',
    answer: 'Section 377 IPC — consensual same-sex relations between adults decriminalised',
    shortcut: 'Navtej Johar 2018 = Sec 377 decriminalised; sexual orientation protected under Art 21 + Art 15',
    detail: 'Overruled Suresh Kumar Koushal case (2013). 5-judge Constitution bench unanimous. Held criminalisation of consensual adult same-sex relations violates dignity and equality.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 70, category: 'Landmark Cases', topic: 'Arnab Goswami (2020)',
    question: 'The SC\'s ruling in Arnab Goswami case 2020 reaffirmed which principle?',
    answer: 'High Courts must not be reluctant to grant bail/interim relief in cases involving personal liberty under Art 21',
    shortcut: 'Arnab Goswami 2020 = HCs must protect personal liberty; personal liberty cases deserve priority',
    detail: 'SC criticised HCs for taking hyper-technical approach in bail matters. Reinforced that Art 21 is paramount and HCs should act as guardians of liberty.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 71, category: 'Landmark Cases', topic: 'Janhit Abhiyan (2022)',
    question: 'The Janhit Abhiyan vs Union of India 2022 case upheld which constitutional amendment?',
    answer: '103rd Amendment 2019 — EWS 10% reservation valid; 50% Indra Sawhney cap can be exceeded for EWS',
    shortcut: 'Janhit Abhiyan 2022 = EWS quota valid; 3:2 verdict; "poor among upper castes" can be reserved separately',
    detail: 'Majority: EWS reservation does not violate basic structure. Dissent (2 judges): excludes SC/ST/OBC poor — discriminatory. Important for SSC questions on EWS.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },

  // ═══════════════════════════════════════════════════════════
  // CONSTITUTIONAL BODIES
  // ═══════════════════════════════════════════════════════════
  {
    id: 72, category: 'Constitutional Bodies', topic: 'Election Commission',
    question: 'Election Commission is established under which article? How many Commissioners are there currently?',
    answer: 'Art 324; Chief Election Commissioner + 2 Election Commissioners (since 1993)',
    shortcut: 'ECI = Art 324; CEC removed like SC judge (impeachment); ECs removed on CEC recommendation',
    detail: 'CEC can be removed only by impeachment (like SC judge) — protection of independence. ECs can be removed on recommendation of CEC.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 73, category: 'Constitutional Bodies', topic: 'Finance Commission',
    question: 'Finance Commission is established under Article 280 — the 16th Finance Commission is chaired by whom?',
    answer: 'Arvind Panagariya (16th FC, constituted 2023, report due 2026)',
    shortcut: 'Art 280 = Finance Commission; 16th FC = Arvind Panagariya; report for 2026–31 period',
    detail: 'Recommends: share of States in divisible pool of taxes, grants-in-aid to States, measures to augment State resources.',
    context: 'Current Affairs 2024', examProb: 'Hot',
  },
  {
    id: 74, category: 'Constitutional Bodies', topic: 'UPSC',
    question: 'UPSC is established under which article and how many members does it have?',
    answer: 'Article 315; up to 11 members (Chairman + 10); serve 6-year term or till 65 years',
    shortcut: 'UPSC = Art 315; removed like SC judge; members cannot return to govt employment after service',
    detail: 'Conducts Civil Services Exam, recommends for appointments, consulted on service matters. Reports annually to President.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 75, category: 'Constitutional Bodies', topic: 'CAG',
    question: 'CAG of India is established under Article 148 — how is the CAG removed?',
    answer: 'By President after address by each House of Parliament (same manner as a Supreme Court Judge)',
    shortcut: 'CAG = Art 148; guardian of public purse; removed like SC Judge (address by Parliament)',
    detail: 'Three types of audit: regularity audit, propriety audit, efficiency audit. CAG of India is also auditor of State governments.',
    context: 'SSC CGL 2022–24', examProb: 'High',
  },
  {
    id: 76, category: 'Constitutional Bodies', topic: 'National Commission for SC/ST',
    question: 'National Commission for Scheduled Castes is established under which Article?',
    answer: 'Article 338; National Commission for Scheduled Tribes under Article 338A (89th Amendment 2003)',
    shortcut: 'Art 338 = SC Commission; Art 338A = ST Commission (separated by 89th Amend 2003)',
    detail: 'Originally combined. 89th Amendment bifurcated into two separate commissions. Both investigate complaints and report to President.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 77, category: 'Constitutional Bodies', topic: 'Inter-State Council',
    question: 'Inter-State Council is established under Article 263 — who chairs it?',
    answer: 'Prime Minister (members: all CMs, 6 Cabinet Ministers nominated by PM)',
    shortcut: 'Art 263 = Inter-State Council; PM chairs; resolves inter-state disputes',
    detail: 'Different from Zonal Councils (statutory, not constitutional). Sarkaria Commission recommended it be set up (finally set up 1990). Not a permanent body constitutionally.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 78, category: 'Constitutional Bodies', topic: 'Attorney General',
    question: 'The Attorney General of India is appointed under which article and has the right of audience in which courts?',
    answer: 'Art 76; right of audience in all courts throughout India',
    shortcut: 'Art 76 = AG of India; highest law officer of India; not a member of Cabinet; can appear in all courts',
    detail: 'AG is appointed by President on advice of PM. Must be qualified to be a SC judge. Can participate in Parliament proceedings without voting rights.',
    context: 'SSC CGL 2023', examProb: 'High',
  },

  // ═══════════════════════════════════════════════════════════
  // PARLIAMENT & EXECUTIVE
  // ═══════════════════════════════════════════════════════════
  {
    id: 79, category: 'Parliament & Executive', topic: 'Lok Sabha',
    question: 'What is the maximum strength of Lok Sabha and what is the normal term?',
    answer: '552 members (530 from States + 20 from UTs + 2 Anglo-Indian nominated — now removed); term is 5 years',
    shortcut: 'LS = max 552 (but currently 543 elected); Anglo-Indian seats removed by 104th Amend; 5-year term',
    detail: 'Can be dissolved before 5 years by President. During Emergency, term can be extended by 1 year at a time. Speaker elected by members.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 80, category: 'Parliament & Executive', topic: 'Rajya Sabha',
    question: 'Rajya Sabha is a permanent House — what is its maximum strength and how are members elected?',
    answer: '250 members (238 elected + 12 nominated); elected by State Legislative Assemblies by STV method',
    shortcut: 'RS = 250 max; permanent (1/3 retire every 2 years); 12 nominated for arts/science/literature/social service',
    detail: 'Special powers: Art 249 (empower Parliament on State subject), Art 312 (create All India Services). VP is ex-officio Chairman.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 81, category: 'Parliament & Executive', topic: 'Question Hour',
    question: 'What is the difference between Starred and Unstarred questions in Parliament?',
    answer: 'Starred: require oral answer (supplementary questions allowed); Unstarred: written answer, no supplementary questions',
    shortcut: 'Starred = Spoken answer + Supplement; Unstarred = Written only; Zero Hour = Indian innovation after Question Hour',
    detail: 'Zero Hour: informal session immediately after Question Hour; no specific provision in Rules; raised since 1962. Private Member Bills: introduced by non-ministers.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 82, category: 'Parliament & Executive', topic: 'No Confidence Motion',
    question: 'What is the minimum number of members required to introduce a No-Confidence Motion in Lok Sabha?',
    answer: '50 members (must give notice; Lok Sabha sets date within 10 days)',
    shortcut: 'No-Confidence = 50 LS members needed; topples government; only in Lok Sabha (not RS)',
    detail: 'Motion of Confidence: PM proves majority. Confidence vote: asked by government. No-confidence: moved by opposition. Government falls if loses.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 83, category: 'Parliament & Executive', topic: 'President Election',
    question: 'How is the President of India elected?',
    answer: 'By Electoral College comprising elected MPs (both Houses) and elected MLAs of State Assemblies + Delhi + Puducherry; proportional representation by STV',
    shortcut: 'President = Electoral College = Elected MPs + Elected MLAs; STV; value of votes calibrated',
    detail: 'Value of MLA vote = (State population ÷ Total elected MLAs) ÷ 1000. VP elected by members of both Houses of Parliament only (not MLAs).',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 84, category: 'Parliament & Executive', topic: 'PM Appointment',
    question: 'Under which article is the Prime Minister appointed and what is the constitutional position?',
    answer: 'Art 75 — PM appointed by President; other ministers appointed on advice of PM; collectively responsible to Lok Sabha',
    shortcut: 'Art 75 = PM appointed by President; Art 74 = CoM aid & advise President; Art 78 = PM duties to President',
    detail: 'Art 78: PM must communicate all Cabinet decisions to President; furnish information as required; submit any matter for Cabinet consideration on President\'s request.',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },

  // ═══════════════════════════════════════════════════════════
  // FUNDAMENTAL RIGHTS & DPSP
  // ═══════════════════════════════════════════════════════════
  {
    id: 85, category: 'Fundamental Rights & DPSP', topic: 'Six FRs Overview',
    question: 'How many Fundamental Rights are currently guaranteed by the Indian Constitution?',
    answer: '6 Fundamental Rights (originally 7; Right to Property removed by 44th Amendment 1978)',
    shortcut: '6 FRs: REFRCE — Right to Equality (14-18), FR (19-22), Against Exploitation (23-24), Religion (25-28), Education/Culture (29-30), Constitutional Remedies (32)',
    detail: 'Art 12-35 contains FRs. Right to Property was Art 19(1)(f) + Art 31. Now only Art 300A (legal right).',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 86, category: 'Fundamental Rights & DPSP', topic: 'Writs — Habeas Corpus',
    question: 'What does the writ of Habeas Corpus literally mean and when is it issued?',
    answer: '"To have the body" — issued to free a person illegally detained',
    shortcut: 'Habeas Corpus = "produce the body"; most important writ for personal liberty; Art 32 (SC) / Art 226 (HC)',
    detail: 'Can be issued against private individuals too. Cannot be issued if detention is by a court order. Available even during Emergency (Art 21 cannot be suspended).',
    context: 'SSC CGL 2022–23', examProb: 'Recurring',
  },
  {
    id: 87, category: 'Fundamental Rights & DPSP', topic: 'Writs — Mandamus',
    question: 'The writ of Mandamus is issued to compel whom to do what?',
    answer: 'Issued to a public official/body to perform a public duty they have failed or refused to perform',
    shortcut: 'Mandamus = "We command"; cannot be issued against President/Governor, purely private bodies, or discretionary functions',
    detail: 'Mandamus means "we command." Cannot compel a person to do something that is discretionary. Also called a "writ of command."',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 88, category: 'Fundamental Rights & DPSP', topic: 'Writs — Quo Warranto',
    question: 'The writ of Quo Warranto is used for what purpose?',
    answer: 'To inquire into the legality of a person\'s claim to a public office',
    shortcut: 'Quo Warranto = "By what authority?"; challenges RIGHT to hold public office; only against public offices',
    detail: 'Only writ that can be sought by any person (not just aggrieved party). Used to oust usurpers from public office.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 89, category: 'Fundamental Rights & DPSP', topic: 'Art 23–24 Against Exploitation',
    question: 'Article 23 prohibits what, and what does Article 24 prohibit?',
    answer: 'Art 23: prohibition of traffic in human beings and forced labour (begar). Art 24: no child labour under 14 in factories, mines or hazardous work',
    shortcut: 'Art 23 = No bonded labour/trafficking; Art 24 = No child labour under 14 in hazardous work',
    detail: 'Art 23 applies to both State and private individuals. Bandhua Mukti Morcha case expanded "forced labour." Art 24 age limit is 14 (not 18).',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 90, category: 'Fundamental Rights & DPSP', topic: 'Art 25–28 Religion',
    question: 'What does Article 25 guarantee regarding freedom of religion?',
    answer: 'Freedom of conscience and right to freely profess, practise and propagate religion (subject to public order, morality, health)',
    shortcut: 'Art 25 = Profess + Practise + Propagate religion; Art 26 = Religious denominations manage own affairs',
    detail: 'Art 27: No tax for promotion of any religion. Art 28: No religious instruction in State-funded schools. Art 25 is available to all persons (not just citizens).',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 91, category: 'Fundamental Rights & DPSP', topic: 'DPSP vs FR Conflict',
    question: 'In case of conflict between Fundamental Rights and DPSP, which prevails?',
    answer: 'Fundamental Rights prevail (but Parliament can amend Constitution to implement DPSP without violating basic structure)',
    shortcut: 'FR > DPSP in conflict; BUT Art 31C (42nd Amend) protected laws implementing Art 39B/C from FR challenge',
    detail: 'Kesavananda Bharati limited Art 31C. Minerva Mills (1980): cannot give absolute primacy to DPSP over FRs — violates basic structure (balance between FR and DPSP).',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 92, category: 'Fundamental Rights & DPSP', topic: 'Art 29–30 Minorities',
    question: 'Article 30 gives which right to religious and linguistic minorities?',
    answer: 'Right to establish and administer educational institutions of their choice',
    shortcut: 'Art 30 = Minority right to run schools; cannot be discriminated in aid; Art 29 = protect distinct culture',
    detail: 'Minorities = religious or linguistic. Art 30(2): State shall not discriminate in granting aid to minority institutions. TMA Pai Foundation case defined "minority" state-wise.',
    context: 'SSC CGL 2023', examProb: 'High',
  },

  // ═══════════════════════════════════════════════════════════
  // IMPORTANT ARTICLES — continued
  // ═══════════════════════════════════════════════════════════
  {
    id: 93, category: 'Important Articles', topic: 'Article 2 & 3',
    question: 'Which articles give Parliament the power to admit new states or alter existing state boundaries?',
    answer: 'Article 2 (admission of new states) and Article 3 (formation of new states, alteration of boundaries/names)',
    shortcut: 'Art 2 = NEW state admitted | Art 3 = alter/merge/rename existing states — Parliament decides, not states',
    detail: 'Art 3 requires President\'s prior recommendation and consultation with affected state legislature (opinion not binding). Sikkim joined via Art 2 in 1975.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 94, category: 'Important Articles', topic: 'Article 18',
    question: 'Article 18 deals with abolition of what?',
    answer: 'Titles — no titles except military/academic distinctions; no foreign titles without President\'s consent',
    shortcut: 'Art 18 = Abolition of TITLES (no "Sir", "Rai Bahadur" etc.); Bharat Ratna NOT covered (not a title)',
    detail: 'Balaji Raghavan case (1996): SC upheld Bharat Ratna, Padma awards as not violating Art 18 — they are civilian honours, not titles.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 95, category: 'Important Articles', topic: 'Article 40',
    question: 'Article 40 of the DPSP directs the State to do what?',
    answer: 'Organise village panchayats and endow them with necessary powers for self-government',
    shortcut: 'Art 40 (DPSP) = Village Panchayats → self-govt; made justiciable by 73rd Amend (Part IX)',
    detail: 'Gandhian principle. 73rd Amendment 1992 gave constitutional status to Panchayats — converting this DPSP aspiration into enforceable reality via Part IX.',
    context: 'SSC CGL standard', examProb: 'High',
  },
  {
    id: 96, category: 'Important Articles', topic: 'Article 50',
    question: 'Article 50 of DPSP directs separation of which two?',
    answer: 'Separation of judiciary from executive (in public services of State)',
    shortcut: 'Art 50 = Separate Judiciary from Executive — independence of judiciary principle (DPSP)',
    detail: 'Part of liberal-intellectual DPSP. Ensures judges are not under executive control. Connected to judicial independence as part of basic structure.',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 97, category: 'Important Articles', topic: 'Article 54 & 55',
    question: 'Articles 54 and 55 deal with which process?',
    answer: 'Election of President — Art 54 specifies Electoral College; Art 55 specifies the manner (proportional representation)',
    shortcut: 'Art 54 = WHO elects President (Electoral College) | Art 55 = HOW elected (STV + proportional)',
    detail: 'Electoral College = elected MPs (both Houses) + elected MLAs (States + Delhi + Puducherry). Nominated MPs/MLAs excluded. VP elected differently — by all MPs only.',
    context: 'SSC CGL 2022–23', examProb: 'High',
  },
  {
    id: 98, category: 'Important Articles', topic: 'Article 61',
    question: 'Article 61 lays down the procedure for which process?',
    answer: 'Impeachment of the President — by Parliament for violation of Constitution',
    shortcut: 'Art 61 = President impeached by Parliament; 14-day notice; 2/3 majority of TOTAL membership of each House',
    detail: 'Charges must be investigated by the other House. 2/3rd of total membership (not just present & voting) of both Houses must agree. Never done in India.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 99, category: 'Important Articles', topic: 'Article 66',
    question: 'How is the Vice President of India elected?',
    answer: 'By members of BOTH Houses of Parliament (Lok Sabha + Rajya Sabha) — not by MLAs; by proportional representation',
    shortcut: 'Art 66 = VP elected by all MPs (LS + RS); NOT by MLAs; ex-officio Chairman of Rajya Sabha (Art 64)',
    detail: 'Key distinction: President elected by Electoral College (MPs + MLAs); VP elected by only MPs. VP can be removed by RS resolution agreed by LS (simple majority).',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 100, category: 'Important Articles', topic: 'Article 76 vs Article 165',
    question: 'What is the difference between Attorney General (Art 76) and Advocate General (Art 165)?',
    answer: 'AG (Art 76) = law officer of Union, appointed by President | Advocate General (Art 165) = law officer of State, appointed by Governor',
    shortcut: 'AG = Centre, President appoints | Advocate General = State, Governor appoints; both must be HC/SC judge-qualified',
    detail: 'AG is the highest law officer of India. Solicitor General and Additional SGs assist the AG but are not constitutional posts.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 101, category: 'Important Articles', topic: 'Article 79',
    question: 'Article 79 states that Parliament shall consist of what?',
    answer: 'President + Council of States (Rajya Sabha) + House of People (Lok Sabha)',
    shortcut: 'Art 79 = Parliament = President + RS + LS (President IS part of Parliament)',
    detail: 'Bills become law only after President\'s assent. President\'s address to joint sitting (Art 87). President can summon, prorogue, dissolve Parliament.',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 102, category: 'Important Articles', topic: 'Article 108',
    question: 'Article 108 provides for which special parliamentary procedure?',
    answer: 'Joint sitting of both Houses — called by President when there is deadlock; Speaker of Lok Sabha presides',
    shortcut: 'Art 108 = Joint Sitting; LS Speaker presides; deadlock situation; CANNOT be held for Money Bill or Constitutional Amendment',
    detail: 'Held 3 times in history: 1961 (Dowry Prohibition), 1978 (Banking Service Commission), 2002 (POTA). Simple majority of total present & voting decides.',
    context: 'SSC CGL 2022–23', examProb: 'High',
  },
  {
    id: 103, category: 'Important Articles', topic: 'Article 124',
    question: 'Article 124 establishes which court and how many judges does the Supreme Court currently have?',
    answer: 'Supreme Court of India; currently 34 judges (1 CJI + 33 other judges); original strength was 8',
    shortcut: 'Art 124 = Supreme Court; CJI + 33 judges; appointment by President after consultation; removed by impeachment',
    detail: 'CJI appointment: senior-most SC judge by convention (collegium system). Collegium (5 senior judges) recommends judges. NJAC struck down in 2015.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 104, category: 'Important Articles', topic: 'Article 143',
    question: 'Article 143 gives the President which advisory power?',
    answer: 'Power to refer questions of law or fact to the Supreme Court for its advisory opinion (Reference Jurisdiction)',
    shortcut: 'Art 143 = Presidential Reference to SC; SC opinion advisory (NOT binding); President need not follow',
    detail: 'SC can refuse to give opinion (has done so). Ram Janmabhoomi reference declined (1993). Differs from US Supreme Court — in India, advisory opinions exist.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 105, category: 'Important Articles', topic: 'Article 200',
    question: 'Under Article 200, a Governor can take which actions on a State Bill passed by Legislature?',
    answer: 'Assent / withhold assent / reserve for President / return for reconsideration (cannot return Money Bills)',
    shortcut: 'Art 200 = Governor on State Bills: 4 options; if returned and passed again, MUST assent (no pocket veto for state bills)',
    detail: 'If Governor reserves for President, Art 201 applies — President can assent, withhold, or direct Governor to return (President HAS pocket veto for state bills).',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 106, category: 'Important Articles', topic: 'Article 249',
    question: 'Under Article 249, Rajya Sabha can pass a resolution allowing Parliament to legislate on what?',
    answer: 'A State List subject (if it is necessary in national interest) — by 2/3rd majority resolution',
    shortcut: 'Art 249 = RS 2/3 resolution → Parliament legislates on STATE LIST subject for national interest; valid 1 year (renewable)',
    detail: 'One of Rajya Sabha\'s special powers reinforcing its role as protector of states. Parliament acquires temporary power on State List.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 107, category: 'Important Articles', topic: 'Article 262',
    question: 'Article 262 deals with adjudication of inter-state water disputes — which body was created under it?',
    answer: 'Inter-State River Water Disputes Act 1956 → Tribunals like Cauvery Tribunal, Krishna Tribunal',
    shortcut: 'Art 262 = Inter-state water disputes; Parliament can create Tribunal; SC has NO jurisdiction here',
    detail: 'Parliament can exclude SC jurisdiction. ISRWD Act 1956 enacted. Cauvery Water Disputes Tribunal (1990) resolved Karnataka-Tamil Nadu dispute in 2018.',
    context: 'SSC CGL 2023', examProb: 'High',
  },

  // ═══════════════════════════════════════════════════════════
  // SCHEDULES — additional
  // ═══════════════════════════════════════════════════════════
  {
    id: 108, category: 'Schedules', topic: '5th vs 6th Schedule',
    question: 'What is the key difference between 5th and 6th Schedule areas?',
    answer: '5th Schedule = Scheduled Areas (non-NE states, President notifies); 6th Schedule = Tribal areas in AMTM states with Autonomous District Councils with legislative powers',
    shortcut: '5th = Governor special powers, no Council laws | 6th = AMTM Autonomous Councils CAN pass laws',
    detail: '5th Schedule: Tribes Advisory Council advises Governor. 6th Schedule Councils can make laws on land, forests, money lending — but subject to Governor/Parliament assent.',
    context: 'SSC CGL 2022–23', examProb: 'High',
  },
  {
    id: 109, category: 'Schedules', topic: '7th Schedule — Key Entries',
    question: 'Give examples of subjects under each list of the 7th Schedule.',
    answer: 'Union: Defence, Railways, Banking, Foreign Affairs, Atomic energy | State: Police, Land, Agriculture, Public health | Concurrent: Education, Forests, Marriage, Criminal law',
    shortcut: 'Union = national security & economy | State = law & order + local | Concurrent = Education + Criminal law (Centre wins in conflict)',
    detail: 'Residuary subjects go to Centre (Art 248). After 42nd Amend, Education and Forests moved from State to Concurrent list.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 110, category: 'Schedules', topic: '8th Schedule — All 22 Languages',
    question: 'Which 4 languages were added to the 8th Schedule by the 92nd Amendment 2003?',
    answer: 'Bodo, Dogri, Maithili, Santhali (total went from 18 to 22)',
    shortcut: 'BoDo-DoGri-MaIthIli-SanthALI = BDMS (92nd Amend 2003); Sindhi = 21st Amend 1967 (13th language)',
    detail: 'Current 22 languages: Assamese, Bengali, Bodo, Dogri, Gujarati, Hindi, Kannada, Kashmiri, Konkani, Maithili, Malayalam, Manipuri, Marathi, Nepali, Odia, Punjabi, Sanskrit, Santhali, Sindhi, Tamil, Telugu, Urdu.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },

  // ═══════════════════════════════════════════════════════════
  // AMENDMENTS — additional
  // ═══════════════════════════════════════════════════════════
  {
    id: 111, category: 'Amendments', topic: '25th Amendment 1971',
    question: 'What did the 25th Amendment 1971 do?',
    answer: 'Inserted Art 31C — laws implementing Art 39B/C (DPSP) cannot be challenged as violating Art 14/19',
    shortcut: '25th Amend = Art 31C shield; DPSP 39B/C laws protected from FR challenge; modified by Minerva Mills (1980)',
    detail: 'Also reduced compensation for property acquisition to "amount" instead of full market value. Minerva Mills limited Art 31C to only Art 39B and 39C, not all DPSP.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 112, category: 'Amendments', topic: '26th Amendment 1971',
    question: 'The 26th Amendment 1971 abolished what?',
    answer: 'Privy purses and special privileges of former rulers of princely states',
    shortcut: '26th Amend = Abolished Privy Purses; Indira Gandhi; overruled SC judgment in Madhavrao Scindia case',
    detail: 'SC had restored privy purses in 1970. 26th Amendment constitutionally ended them. Deleted Art 291 and Art 362 which guaranteed privy purses.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 113, category: 'Amendments', topic: '36th Amendment 1975',
    question: 'The 36th Amendment 1975 incorporated which new state into India?',
    answer: 'Sikkim became the 22nd state of India',
    shortcut: '36th Amend = Sikkim became 22nd State (1975); added via Art 2A (later deleted) and via 36th Amend',
    detail: 'Sikkim was a protectorate. After a referendum, the Chogyal was deposed and Sikkim merged with India as 22nd state under Indira Gandhi\'s government.',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 114, category: 'Amendments', topic: '38th Amendment 1975',
    question: 'The 38th Amendment 1975 made which actions non-justiciable?',
    answer: "Made President's proclamation of Emergency and Governor's Ordinances non-justiciable (passed during Emergency)",
    shortcut: '38th Amend (Emergency era) = Emergency proclamation not reviewable; reversed by 44th Amend 1978',
    detail: 'One of several authoritarian Emergency-period amendments. Reversed by 44th Amendment (1978) after Emergency lifted. Made Art 352 proclamation reviewable by courts again.',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 115, category: 'Amendments', topic: '43rd & 44th Amendment 1977–78',
    question: 'The 43rd Amendment 1977 and 44th Amendment 1978 were passed by which government and what did they primarily restore?',
    answer: 'Janata Party government — reversed Emergency-era 42nd Amendment excesses; restored fundamental rights and judicial review',
    shortcut: '43rd + 44th = Janata Party undid Emergency damage; property out of FRs; CoM advice binding; "armed rebellion" replaces "internal disturbance"',
    detail: '44th Amend also prevented misuse of Art 352 by requiring Cabinet\'s written recommendation and allowing Lok Sabha to revoke Emergency by simple majority.',
    context: 'SSC CGL 2022–23', examProb: 'High',
  },
  {
    id: 116, category: 'Amendments', topic: '69th Amendment 1991',
    question: 'The 69th Amendment 1991 gave special status to which territory?',
    answer: 'Delhi (NCT of Delhi) — given a Legislative Assembly and a Council of Ministers',
    shortcut: '69th Amend = Delhi gets Assembly + CoM; but Police, Land, Public order remain with Centre (Lt. Governor)',
    detail: 'NCT of Delhi has limited statehood. Key areas — police, land, public order — remain with Centre through LG. SC ruled in 2023 that services (civil servants) under elected govt.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 117, category: 'Amendments', topic: '89th Amendment 2003',
    question: 'The 89th Amendment 2003 split which single commission into two?',
    answer: 'National Commission for Scheduled Castes and Scheduled Tribes bifurcated into separate commissions (Art 338 and Art 338A)',
    shortcut: '89th Amend = SC Commission (Art 338) and ST Commission (Art 338A) separated',
    detail: 'Previously a combined National Commission for SC and ST. ST Commission now has separate mandate for tribal affairs, forest rights, displacement issues.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 118, category: 'Amendments', topic: '92nd Amendment 2003',
    question: 'The 92nd Amendment 2003 added which four languages to the 8th Schedule?',
    answer: 'Bodo, Dogri, Maithili, Santhali — taking total from 18 to 22',
    shortcut: '92nd Amend = 4 new languages: Bodo + Dogri + Maithili + Santhali = 22 total',
    detail: 'Maithili is the language of Bihar\'s Mithila region. Santhali is a Santali tribal language (Ol Chiki script). Bodo from Assam, Dogri from J&K.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 119, category: 'Amendments', topic: '97th Amendment 2011',
    question: 'The 97th Amendment 2011 gave constitutional status and fundamental right protection to what?',
    answer: 'Co-operative societies — Art 19(1)(c) expanded; Art 43B (DPSP) added; Part IXB (Art 243ZH–243ZT) added',
    shortcut: '97th Amend = Co-operative societies get FR + DPSP + dedicated constitutional provisions',
    detail: 'Partially struck down by SC in 2021 (Union of India vs Rajendra Shah) — provisions relating to State co-operative societies could not be amended by Parliament alone.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 120, category: 'Amendments', topic: '100th Amendment 2015',
    question: 'The 100th Amendment 2015 ratified which agreement between India and Bangladesh?',
    answer: 'Land Boundary Agreement (LBA) — exchange of enclaves; India gave 111 enclaves to Bangladesh, received 51',
    shortcut: '100th Amend = India-Bangladesh LBA; enclave exchange; India gave 111, got 51; \'Tin Bigha Corridor\' settled',
    detail: 'Resolved 68-year-old territorial dispute. Persons in exchanged enclaves given choice of citizenship. Required constitutional amendment as territory was exchanged.',
    context: 'SSC CGL 2022', examProb: 'High',
  },

  // ═══════════════════════════════════════════════════════════
  // LANDMARK CASES — additional
  // ═══════════════════════════════════════════════════════════
  {
    id: 121, category: 'Landmark Cases', topic: 'A.K. Gopalan (1950)',
    question: 'What did the A.K. Gopalan case 1950 hold about Article 21, and which later case overruled it?',
    answer: 'Art 21\'s "procedure established by law" means any procedure fixed by law (even arbitrary); Arts 19 and 21 are independent — overruled by Maneka Gandhi 1978',
    shortcut: 'A.K. Gopalan 1950 = Narrow reading of Art 21; FRs read separately; OVERRULED by Maneka Gandhi (1978)',
    detail: 'SC held that as long as a law prescribes a procedure, any detention under that law is valid. Maneka Gandhi broadened this to require the procedure to be just, fair and reasonable.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 122, category: 'Landmark Cases', topic: 'Indira Gandhi vs Raj Narain (1975)',
    question: 'What did the Indira Gandhi vs Raj Narain case 1975 establish?',
    answer: 'Free and fair elections are part of the basic structure; struck down Art 329A inserted by 39th Amendment (immunised PM election from judicial review)',
    shortcut: 'Indira Gandhi vs Raj Narain = Free elections = basic structure; Art 329A (39th Amend) struck down',
    detail: 'Allahabad HC found Indira Gandhi guilty of corrupt practices in 1971 election. Parliament passed 39th Amendment to shield her. SC struck this down as basic structure violation.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 123, category: 'Landmark Cases', topic: 'Minerva Mills (1980)',
    question: 'The Minerva Mills case 1980 struck down which part of the 42nd Amendment?',
    answer: 'Struck down Art 368(4) and (5) which made constitutional amendments non-justiciable; also limited Art 31C',
    shortcut: 'Minerva Mills 1980 = Balance between FR and DPSP = basic structure; 42nd Amend DPSP supremacy struck down',
    detail: 'SC held that harmony and balance between FRs and DPSP is a basic structure feature. Parliament cannot give absolute primacy to DPSP over FRs.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 124, category: 'Landmark Cases', topic: 'Waman Rao (1981)',
    question: 'What did the Waman Rao case 1981 clarify about the 9th Schedule?',
    answer: 'Laws placed in 9th Schedule before 24 April 1973 (Kesavananda judgment date) are fully protected; those added after can be reviewed if they violate basic structure',
    shortcut: 'Waman Rao 1981 = 9th Schedule cut-off date is 24 April 1973; later confirmed by I.R. Coelho (2007)',
    detail: 'Pre-Kesavananda 9th Schedule laws get absolute protection. Post-Kesavananda additions can be challenged on basic structure grounds. Important for agrarian reform laws.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 125, category: 'Landmark Cases', topic: 'Kihoto Hollohan (1992)',
    question: 'The Kihoto Hollohan case 1992 upheld which law but with what caveat?',
    answer: 'Upheld Anti-Defection Law (10th Schedule); BUT held that Speaker\'s decision is subject to judicial review by HC and SC',
    shortcut: 'Kihoto Hollohan = 10th Schedule valid; Speaker NOT final arbiter; courts CAN review Speaker\'s disqualification order',
    detail: 'Important limitation: Para 7 of 10th Schedule (which barred courts) was struck down. Judiciary can intervene in defection cases, preventing arbitrary Speaker decisions.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 126, category: 'Landmark Cases', topic: 'Unni Krishnan (1993)',
    question: 'The Unni Krishnan case 1993 held what about the right to education?',
    answer: 'Right to education (up to 14 years) is part of Art 21 (right to life); the State is bound to provide it — this later led to Art 21A by 86th Amendment',
    shortcut: 'Unni Krishnan 1993 = Education = part of Art 21; led to 86th Amend making it explicit FR via Art 21A (2002)',
    detail: 'Before Art 21A, education was only in DPSP (Art 45). SC in Unni Krishnan read it into Art 21. The 86th Amendment formalised this as a constitutional right.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 127, category: 'Landmark Cases', topic: 'NJAC Case (2015)',
    question: 'The NJAC case 2015 (Supreme Court Advocates on Record Association) struck down what?',
    answer: 'National Judicial Appointments Commission (NJAC) — 99th Constitutional Amendment struck down; collegium system restored',
    shortcut: 'NJAC 2015 = 99th Amend struck down; judicial independence = basic structure; collegium continues',
    detail: 'NJAC would have given executive role in judicial appointments. SC held that judicial primacy in appointments is part of basic structure (judicial independence).',
    context: 'SSC CGL 2023', examProb: 'Hot',
  },
  {
    id: 128, category: 'Landmark Cases', topic: 'Shreya Singhal (2015)',
    question: 'The Shreya Singhal case 2015 struck down which provision?',
    answer: 'Section 66A of IT Act — which penalised "offensive" online speech — struck down as unconstitutional, violating Art 19(1)(a)',
    shortcut: 'Shreya Singhal 2015 = Sec 66A IT Act killed; online free speech = Art 19(1)(a) protection',
    detail: 'Landmark internet freedom judgment. SC held that "grossly offensive" is vague and overbroad — fails the test of reasonable restrictions under Art 19(2).',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 129, category: 'Landmark Cases', topic: 'Triple Talaq Case (2017)',
    question: 'The Triple Talaq (Shayara Bano) case 2017 held what?',
    answer: 'Instantaneous Triple Talaq (talaq-e-biddat) is unconstitutional — violates Art 14 (equality) and Art 21 (dignity); 3:2 majority',
    shortcut: 'Triple Talaq 2017 = Shayara Bano; 3:2 verdict; Muslim Women Protection Act 2019 criminalised it',
    detail: 'SC found it manifestly arbitrary. Parliament subsequently passed Muslim Women (Protection of Rights on Marriage) Act 2019 making triple talaq a criminal offence.',
    context: 'SSC CGL 2022–23', examProb: 'Hot',
  },
  {
    id: 130, category: 'Landmark Cases', topic: 'Ayodhya Verdict (2019)',
    question: 'What did the SC\'s Ayodhya verdict 2019 decide?',
    answer: '5-judge unanimous bench: disputed land given to Ram Lalla (deity); 5-acre alternative land to Sunni Waqf Board; directed construction of Ram Temple',
    shortcut: 'Ayodhya 2019 = Ram Lalla gets disputed 2.77 acres; Sunni Waqf Board gets 5 acres alternate; Ram Temple built',
    detail: 'SC used Art 142 (complete justice) to direct the government. Title dispute decided under civil law, not religious law. Ram Mandir consecration January 2024.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 131, category: 'Landmark Cases', topic: 'Electoral Bonds Case (2024)',
    question: 'The SC\'s Electoral Bonds judgment 2024 struck down what?',
    answer: 'Electoral Bonds Scheme 2018 — struck down unanimously as unconstitutional; violates right to information (Art 19(1)(a)) about political funding',
    shortcut: 'Electoral Bonds 2024 = 5:0 SC struck down; voters have right to know who funds parties (Art 19(1)(a))',
    detail: 'SC held that anonymous political funding violates voters\' right to information. Directed SBI to stop issuing bonds and ECI to publish donor details.',
    context: 'Current Affairs Feb 2024', examProb: 'Hot',
  },

  // ═══════════════════════════════════════════════════════════
  // CONSTITUTIONAL BODIES — additional
  // ═══════════════════════════════════════════════════════════
  {
    id: 132, category: 'Constitutional Bodies', topic: 'Comptroller vs Controller',
    question: 'The CAG is both Comptroller and Auditor General — what is the significance of "Comptroller"?',
    answer: 'In practice, CAG performs only audit functions — the RBI controls funds, not CAG. "Comptroller" is nominal in India unlike UK where CAG controls expenditure',
    shortcut: 'CAG = Auditor (actual); Comptroller title is NOMINAL in India; reports to President/Governor',
    detail: 'CAG audits: (1) Government of India, (2) State Governments, (3) Government companies. Reports submitted separately to President (Union) and Governor (State).',
    context: 'SSC CGL standard', examProb: 'Recurring',
  },
  {
    id: 133, category: 'Constitutional Bodies', topic: 'Panchayat Election Commission',
    question: 'Who conducts elections to Panchayati Raj bodies — ECI or State Election Commission?',
    answer: 'State Election Commission (Art 243K) — NOT the Election Commission of India; separate constitutional body for each state',
    shortcut: 'Art 243K = State EC for Panchayat/Municipal elections | Art 324 = ECI for Parliament/Assembly/President/VP',
    detail: 'State Election Commissioner has security of tenure (removed like HC judge). ECI has NO jurisdiction over local body elections — common exam confusion.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 134, category: 'Constitutional Bodies', topic: 'National Commission for Women',
    question: 'Is the National Commission for Women a constitutional body?',
    answer: 'No — it is a statutory body established under the National Commission for Women Act 1990 (NOT a constitutional body)',
    shortcut: 'NCW = STATUTORY (not constitutional); established 1992 under 1990 Act; Vijaya Rahatkar is current chairperson',
    detail: 'Common trap question. Constitutional bodies are created by the Constitution itself (Art 324 for ECI etc.). Statutory bodies are created by Parliament\'s legislation.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 135, category: 'Constitutional Bodies', topic: 'Special Officer for Linguistic Minorities',
    question: 'Which constitutional body protects linguistic minorities under Article 350B?',
    answer: 'Special Officer for Linguistic Minorities — appointed by President; reports to President; ensures safeguards for linguistic minorities',
    shortcut: 'Art 350B = Special Officer for Linguistic Minorities; submits annual report to President → tabled in Parliament',
    detail: 'Often called "Commissioner for Linguistic Minorities." Not well-known but appears in exams. Created to protect language rights of minorities in different states.',
    context: 'SSC CGL 2022', examProb: 'High',
  },
  {
    id: 136, category: 'Constitutional Bodies', topic: 'National Commission for Backward Classes',
    question: 'The National Commission for Backward Classes was given constitutional status by which amendment?',
    answer: '102nd Amendment 2018 — Art 338B inserted; also gave constitutional status to Central List of OBCs',
    shortcut: 'NCBC = Art 338B (102nd Amend 2018); Art 342A = President notifies OBC list; removes State power to add to Central OBC list',
    detail: '102nd Amendment also inserted Art 342A — President specifies OBCs for Central purposes. Supreme Court in Maratha case (2021) clarified states cannot expand central OBC list independently.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },

  // ═══════════════════════════════════════════════════════════
  // PARLIAMENT & EXECUTIVE — additional
  // ═══════════════════════════════════════════════════════════
  {
    id: 137, category: 'Parliament & Executive', topic: 'Budget Process',
    question: 'What is the difference between Voted and Charged expenditure in the Union Budget?',
    answer: 'Voted: requires Parliament\'s approval | Charged: automatically charged to Consolidated Fund without Parliament\'s vote (e.g. President\'s salary, SC judges, CAG, Speaker)',
    shortcut: 'Charged = Not voted (President, Judges, CAG, Speaker salaries) | Voted = Parliament must approve',
    detail: 'Charged expenditure cannot be voted against but can be discussed. Railway Budget merged with General Budget from 2017. Interim Budget ≠ Vote on Account (interim is full budget before election).',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 138, category: 'Parliament & Executive', topic: 'President vs Governor Powers',
    question: 'What are the key differences between President\'s and Governor\'s discretionary powers?',
    answer: 'Governor has real discretion in: appointing CM (hung assembly), reserving bills for President, dismissing ministry losing confidence. President has NO real discretion (must follow CoM advice per Art 74)',
    shortcut: 'President = Constitutional head, NO real discretion | Governor = Some real discretion; can act independently in hung assembly',
    detail: '44th Amendment made CoM advice binding on President. Governor\'s discretion more real but Sarkaria Commission said it should be used sparingly. Governor = agent of Centre in state.',
    context: 'SSC CGL 2023–24', examProb: 'Hot',
  },
  {
    id: 139, category: 'Parliament & Executive', topic: 'Speaker\'s Powers',
    question: 'List the key powers of the Speaker of Lok Sabha.',
    answer: 'Presides over LS, certifies Money Bills, decides disqualification under Anti-Defection, casting vote in tie, adjourns LS, cannot vote in normal proceedings',
    shortcut: 'Speaker: Money Bill certifier + Defection decider + No vote (except casting) + Presides + Adjournment power',
    detail: 'Speaker cannot be removed except by LS resolution (14 days notice). Speaker continues even after dissolution until new LS meets. Kihoto Hollohan: Speaker\'s defection ruling is subject to judicial review.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
  {
    id: 140, category: 'Parliament & Executive', topic: 'Parliamentary Committees',
    question: 'What are the three Financial Committees of Parliament and what does each examine?',
    answer: 'Public Accounts Committee (PAC) — past expenditure; Estimates Committee — future estimates; Committee on Public Undertakings (COPU) — PSU working',
    shortcut: 'PAC = Past spending (LS + RS) | Estimates = Future budget (only LS) | COPU = PSU performance',
    detail: 'PAC: 22 members (15 LS + 7 RS); chaired by Opposition leader traditionally. Estimates Committee: 30 members, all from LS. COPU: 22 members.',
    context: 'SSC CGL 2022–23', examProb: 'High',
  },
  {
    id: 141, category: 'Parliament & Executive', topic: 'Constitutional Amendments — Procedure',
    question: 'Which constitutional provisions require ratification by at least half the State Legislatures in addition to special majority in Parliament?',
    answer: 'Federal provisions: election of President (Art 54/55), extent of executive power of Union/States, Supreme Court, High Courts, distribution of legislative power (7th Schedule), representation in Parliament, Art 368 itself',
    shortcut: 'Federal provisions = Special majority + HALF STATES ratification; Simple majority = ordinary matters like new state admission',
    detail: 'Three-tier amendment: (1) Simple majority — ordinary constitutional changes; (2) Special majority — 2/3 present+voting + absolute majority; (3) Special majority + ½ States — federal provisions.',
    context: 'SSC CGL 2022–24', examProb: 'Hot',
  },
  {
    id: 142, category: 'Parliament & Executive', topic: 'Prorogation vs Dissolution vs Adjournment',
    question: 'What is the difference between Adjournment, Prorogation and Dissolution of Parliament?',
    answer: 'Adjournment = temporary suspension within session (by Speaker/Chairman) | Prorogation = session ended by President, pending business lapses | Dissolution = Lok Sabha dissolved; all pending Bills lapse (except RS ones)',
    shortcut: 'Adjournment = pause | Prorogation = session ends | Dissolution = LS ends + elections; Rajya Sabha never dissolved',
    detail: 'After dissolution, Bills introduced in LS lapse. Bills pending in RS do not lapse. Joint committee report lapses. Bill passed by LS but pending in RS also lapses on dissolution.',
    context: 'SSC CGL 2023', examProb: 'High',
  },
]

export const polityPYQHistory: PolityPYQEntry[] = [
  { date: '2024 CGL', shift: 'Shift 1', question: 'Which Article deals with Right to Education (6–14 years)?', answer: 'Article 21A', category: 'Important Articles' },
  { date: '2024 CGL', shift: 'Shift 2', question: 'Which amendment introduced GST in India?', answer: '101st Amendment 2016', category: 'Amendments' },
  { date: '2024 CGL', shift: 'Various', question: 'Which schedule contains the Anti-Defection Law?', answer: '10th Schedule', category: 'Schedules' },
  { date: '2024 CGL', shift: 'Various', question: 'EWS 10% reservation was introduced by which amendment?', answer: '103rd Amendment 2019', category: 'Amendments' },
  { date: '2023 CGL', shift: 'Shift 1', question: 'Article 32 is called "heart and soul" of the Constitution by whom?', answer: 'Dr. B.R. Ambedkar', category: 'Important Articles' },
  { date: '2023 CGL', shift: 'Shift 2', question: 'Basic Structure Doctrine was established in which case?', answer: 'Kesavananda Bharati (1973)', category: 'Landmark Cases' },
  { date: '2023 CGL', shift: 'Various', question: 'Which amendment added "Socialist" and "Secular" to Preamble?', answer: '42nd Amendment 1976', category: 'Amendments' },
  { date: '2023 CGL', shift: 'Various', question: 'How many languages are listed in the 8th Schedule?', answer: '22 languages', category: 'Schedules' },
  { date: '2023 CGL', shift: 'Shift 3', question: 'Right to privacy declared FR in which case?', answer: 'K.S. Puttaswamy vs Union of India (2017)', category: 'Landmark Cases' },
  { date: '2022 CGL', shift: 'Various', question: 'President\'s Rule is imposed under which Article?', answer: 'Article 356', category: 'Important Articles' },
  { date: '2022 CGL', shift: 'Various', question: 'Voting age reduced to 18 by which amendment?', answer: '61st Amendment 1988', category: 'Amendments' },
  { date: '2022 CGL', shift: 'Various', question: '7th Schedule contains how many lists?', answer: '3 lists (Union, State, Concurrent)', category: 'Schedules' },
  { date: 'Current 2024', shift: 'CA', question: '16th Finance Commission chaired by?', answer: 'Arvind Panagariya', category: 'Constitutional Bodies' },
  { date: 'Current 2023', shift: 'CA', question: "Women's reservation (33%) introduced by which amendment?", answer: '106th Amendment 2023 (Nari Shakti Vandan Act)', category: 'Amendments' },
]
