export type Subject = 'Physics' | 'Chemistry' | 'Biology' | 'Space & Defense' | 'Technology'
export type ExamProb = 'Hot' | 'High' | 'Confirmed' | 'Recurring'

export interface SciEntry {
  id: number
  subject: Subject
  topic: string
  question: string
  answer: string
  explanation: string
  context: string
  examProb: ExamProb
  mnemonic?: string
}

export interface SciPYQEntry {
  date: string
  shift: string
  question: string
  answer: string
  subject: Subject
}

export const sciData: SciEntry[] = [
  // ── PHYSICS ──────────────────────────────────────────────────────────────
  {
    id: 1, subject: 'Physics', topic: 'Laws of Motion',
    question: 'The path followed by a javelin thrown at an angle is called?',
    answer: 'Curvilinear motion (Projectile)',
    explanation: 'A javelin follows a parabolic/curvilinear path under gravity after launch.',
    context: 'SSC CGL 12 Sep 2024 Shift 1', examProb: 'Confirmed',
    mnemonic: 'Javelin = Curved beauty in the sky',
  },
  {
    id: 2, subject: 'Physics', topic: 'Optics',
    question: 'Which phenomenon is responsible for the working of optical fibres?',
    answer: 'Total Internal Reflection (TIR)',
    explanation: 'Light travels through fibre by continuously reflecting off inner walls when angle exceeds critical angle.',
    context: 'SSC CGL 2022 Tier 1', examProb: 'Hot',
    mnemonic: 'TIR = Totally Inside Reflecting',
  },
  {
    id: 3, subject: 'Physics', topic: 'Optics',
    question: 'Diffraction of light proves that light has what nature?',
    answer: 'Wave nature',
    explanation: 'Diffraction is the bending of waves around obstacles — only waves diffract, not particles.',
    context: 'SSC CGL 23 Sep 2024 Shift 1', examProb: 'Confirmed',
    mnemonic: 'Diffraction → Deviation → Wave',
  },
  {
    id: 4, subject: 'Physics', topic: 'Electricity',
    question: 'Which metal has the highest electrical resistivity and is used in heating elements?',
    answer: 'Nichrome',
    explanation: 'Nichrome (Ni-Cr alloy) has very high resistivity (~100×10⁻⁸ Ωm) and high melting point — ideal for heaters.',
    context: 'SSC CGL 17 Jul 2023 Shift 1', examProb: 'Confirmed',
    mnemonic: 'Nichrome = Nickel + Chrome = HIGH resistance',
  },
  {
    id: 5, subject: 'Physics', topic: 'Electricity',
    question: 'What does a sphygmomanometer measure?',
    answer: 'Blood pressure',
    explanation: 'Sphygmomanometer measures arterial blood pressure using an inflatable cuff.',
    context: 'SSC CGL 2023 GA section', examProb: 'Hot',
    mnemonic: 'Sphygmo = pulse pressure measure',
  },
  {
    id: 6, subject: 'Physics', topic: 'Sound',
    question: 'The speed of sound is maximum in which medium?',
    answer: 'Solids',
    explanation: 'Sound needs a medium and travels fastest in solids due to tightly packed particles (e.g., iron: ~5100 m/s).',
    context: 'SSC CGL standard PYQ', examProb: 'High',
    mnemonic: 'Solid > Liquid > Gas for sound speed',
  },
  {
    id: 7, subject: 'Physics', topic: 'Thermodynamics',
    question: 'Which law of thermodynamics defines the concept of temperature?',
    answer: 'Zeroth Law',
    explanation: 'Zeroth Law: if A is in thermal equilibrium with B, and B with C, then A is with C — defines temperature.',
    context: 'SSC CGL 2022–23', examProb: 'High',
    mnemonic: 'Zeroth = Zero start = Temperature concept',
  },
  {
    id: 8, subject: 'Physics', topic: 'Optics',
    question: 'Which mirror is used as a rear-view mirror in vehicles?',
    answer: 'Convex mirror',
    explanation: 'Convex mirrors always form virtual, diminished, erect images — wider field of view for rear-view mirrors.',
    context: 'SSC CGL standard PYQ', examProb: 'High',
    mnemonic: 'Convex = Cars use it to see behind WIDE',
  },
  {
    id: 9, subject: 'Physics', topic: 'Nuclear Physics',
    question: 'Which particle has no charge and negligible mass, emitted during beta decay?',
    answer: 'Neutrino (antineutrino)',
    explanation: 'In beta-minus decay: n → p + e⁻ + antineutrino. Neutrinos interact very weakly with matter.',
    context: 'SSC CGL 2024 GA', examProb: 'High',
    mnemonic: 'Neutrino = neutral ghost particle',
  },
  {
    id: 10, subject: 'Physics', topic: 'Magnetism',
    question: 'The SI unit of magnetic field strength (flux density) is?',
    answer: 'Tesla (T)',
    explanation: '1 Tesla = 1 Weber per square meter. Named after Nikola Tesla.',
    context: 'SSC CGL 2023 GA', examProb: 'High',
    mnemonic: 'Tesla the car = magnetic power',
  },
  {
    id: 11, subject: 'Physics', topic: 'Laws of Motion',
    question: "Newton's second law of motion gives the definition of which quantity?",
    answer: 'Force (F = ma)',
    explanation: 'F = ma — the rate of change of momentum equals the applied force. Defines force quantitatively.',
    context: 'SSC CGL standard PYQ', examProb: 'Recurring',
    mnemonic: 'Second law = Second thing after identifying motion = FORCE',
  },
  {
    id: 12, subject: 'Physics', topic: 'Optics',
    question: 'Which lens is used to correct myopia (short-sightedness)?',
    answer: 'Concave lens',
    explanation: 'Concave (diverging) lens diverges incoming light, shifting the focus back onto the retina.',
    context: 'SSC CGL Tier 1 2022', examProb: 'Recurring',
    mnemonic: 'Myopia → Minus lens → Concave',
  },
  {
    id: 13, subject: 'Physics', topic: 'Work & Energy',
    question: 'The unit of power in the SI system is?',
    answer: 'Watt (W)',
    explanation: '1 Watt = 1 Joule per second. Power = Work / Time.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Watt did you power today?',
  },
  {
    id: 14, subject: 'Physics', topic: 'Gravitation',
    question: "The value of acceleration due to gravity (g) at the centre of the Earth is?",
    answer: 'Zero',
    explanation: "At Earth's centre, gravitational pull from all directions cancels out → g = 0.",
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'Centre = surrounded equally = zero pull',
  },
  {
    id: 15, subject: 'Physics', topic: 'Electricity',
    question: "Transformers work on which principle?",
    answer: "Mutual induction (Faraday's electromagnetic induction)",
    explanation: 'A changing current in primary coil induces EMF in secondary coil via changing magnetic flux.',
    context: 'SSC CGL 2022–24', examProb: 'High',
    mnemonic: 'Transformer = Transfer energy via mutual induction',
  },
  {
    id: 16, subject: 'Physics', topic: 'Waves',
    question: 'Ultrasonics are used in SONAR for what purpose?',
    answer: 'Detection of underwater objects / depth measurement',
    explanation: 'SONAR = Sound Navigation And Ranging. Uses ultrasonic waves reflected from objects to determine distance.',
    context: 'SSC CGL 2023 Tier 1', examProb: 'High',
    mnemonic: 'SONAR = underwater RADAR using sound',
  },
  {
    id: 17, subject: 'Physics', topic: 'Modern Physics',
    question: 'Laser works on the principle of?',
    answer: 'Stimulated emission of radiation',
    explanation: 'LASER = Light Amplification by Stimulated Emission of Radiation. Photons trigger coherent photon emission.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'L-A-S-E-R spells the principle',
  },
  {
    id: 18, subject: 'Physics', topic: 'Thermodynamics',
    question: 'Which scale of temperature is based on the properties of an ideal gas?',
    answer: 'Kelvin (absolute) scale',
    explanation: 'Kelvin starts at absolute zero (−273.15°C) where all molecular motion stops.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: 'Kelvin = King of temperature scales',
  },

  // ── CHEMISTRY ────────────────────────────────────────────────────────────
  {
    id: 19, subject: 'Chemistry', topic: 'Periodic Table',
    question: 'Mendeleev predicted the existence of germanium calling it what?',
    answer: 'Eka-silicon',
    explanation: 'Mendeleev left gaps in his periodic table and predicted properties of missing elements. Gallium=eka-aluminium, Germanium=eka-silicon.',
    context: 'SSC CGL 2024 GA', examProb: 'Confirmed',
    mnemonic: 'Eka = one below (Sanskrit). Eka-silicon sits below Silicon.',
  },
  {
    id: 20, subject: 'Chemistry', topic: 'Periodic Table',
    question: 'Mendeleev called the undiscovered element below aluminium — what was it found to be?',
    answer: 'Gallium (predicted as Eka-aluminium)',
    explanation: "Mendeleev's eka-aluminium was discovered in 1875 as Gallium — matching his predicted properties almost exactly.",
    context: 'SSC CGL 2024 Confirmed PYQ', examProb: 'Confirmed',
    mnemonic: 'Gal(lium) fills the Aluminium gap',
  },
  {
    id: 21, subject: 'Chemistry', topic: 'Organic Chemistry',
    question: 'What is the molecular formula of Butane?',
    answer: 'C₄H₁₀',
    explanation: 'Butane (n-butane or isobutane) is an alkane with formula CₙH₂ₙ₊₂ → C₄H₁₀.',
    context: 'SSC CGL 2024 GA', examProb: 'Confirmed',
    mnemonic: 'But(4)ane: 4 carbons, 10 hydrogens',
  },
  {
    id: 22, subject: 'Chemistry', topic: 'Organic Chemistry',
    question: 'IUPAC name of 2-Methylpropan-2-ol is the systematic name for which common compound?',
    answer: 'Tert-butanol (t-BuOH)',
    explanation: '2-methylpropan-2-ol has OH on the central carbon of isobutane — tertiary butyl alcohol.',
    context: 'SSC CGL 09 Sep 2024 Shift 1', examProb: 'Confirmed',
    mnemonic: '2-Methyl, 2-position = 2nd carbon gets the OH and methyl branch',
  },
  {
    id: 23, subject: 'Chemistry', topic: 'States of Matter',
    question: 'Italian researchers reported "Supersolid Light" in 2024 — what state does it represent?',
    answer: 'Fourth state of light / supersolid phase of polaritons',
    explanation: 'Italian researchers created a supersolid phase using polaritons (light-matter quasi-particles) — rigid structure yet flows like superfluid.',
    context: 'Current Affairs 2024', examProb: 'High',
    mnemonic: 'Supersolid = solid structure + superfluid flow',
  },
  {
    id: 24, subject: 'Chemistry', topic: 'Acids & Bases',
    question: 'Which acid is present in vinegar?',
    answer: 'Acetic acid (CH₃COOH)',
    explanation: 'Vinegar is 5–8% acetic acid solution. Ethanoic acid by IUPAC name.',
    context: 'SSC CGL standard Recurring', examProb: 'Recurring',
    mnemonic: 'VINegar = ethanVINic = acetic acid',
  },
  {
    id: 25, subject: 'Chemistry', topic: 'Metals',
    question: 'Which metal is the best conductor of electricity?',
    answer: 'Silver (Ag)',
    explanation: 'Silver has the highest electrical conductivity of all metals at room temperature. Copper is second.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Silver = #1 conductor, Copper = #2',
  },
  {
    id: 26, subject: 'Chemistry', topic: 'Metals',
    question: 'What is the chemical name of "Baking Soda"?',
    answer: 'Sodium bicarbonate (NaHCO₃)',
    explanation: 'NaHCO₃ releases CO₂ when heated — used as leavening agent in baking.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'Baking Soda = Bi-carb of Soda = NaHCO₃',
  },
  {
    id: 27, subject: 'Chemistry', topic: 'Chemical Reactions',
    question: 'What gas is produced when acids react with metal carbonates?',
    answer: 'Carbon dioxide (CO₂)',
    explanation: 'Acid + Metal carbonate → Salt + Water + CO₂. This turns lime water milky.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: 'Carbonate + Acid = CO₂ bubbles',
  },
  {
    id: 28, subject: 'Chemistry', topic: 'Polymers',
    question: 'What is the monomer of natural rubber?',
    answer: 'Isoprene (2-methylbuta-1,3-diene)',
    explanation: 'Natural rubber is a polymer of isoprene units. Vulcanisation adds sulphur cross-links to make it durable.',
    context: 'SSC CGL 2023 GA', examProb: 'High',
    mnemonic: 'ISOprene = rubber ISO standard monomer',
  },
  {
    id: 29, subject: 'Chemistry', topic: 'Environmental Chemistry',
    question: 'Which gas is mainly responsible for the greenhouse effect?',
    answer: 'Carbon dioxide (CO₂) — also methane CH₄',
    explanation: 'CO₂ from burning fossil fuels traps IR radiation. CH₄ is 25x more potent but less abundant.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'CO₂ = Chief greenhouse criminal',
  },
  {
    id: 30, subject: 'Chemistry', topic: 'Periodic Table',
    question: 'The element with highest electronegativity is?',
    answer: 'Fluorine (F)',
    explanation: 'Fluorine (F) has electronegativity 4.0 on Pauling scale — highest of all elements.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: 'F = First to grab electrons = most electronegative',
  },
  {
    id: 31, subject: 'Chemistry', topic: 'Nuclear Chemistry',
    question: 'Heavy water (D₂O) is used in nuclear reactors as what?',
    answer: 'Moderator (slows down neutrons)',
    explanation: 'D₂O slows fast neutrons to thermal energy for sustained fission without absorbing them like light water.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'Heavy water = slows (moderates) fast neutrons',
  },
  {
    id: 32, subject: 'Chemistry', topic: 'Organic Chemistry',
    question: 'What is the common name for ethanol?',
    answer: 'Alcohol / Grain alcohol / Drinking alcohol',
    explanation: 'C₂H₅OH is ethyl alcohol — produced by fermentation of sugars. IUPAC: ethanol.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Ethanol = the social molecule',
  },
  {
    id: 33, subject: 'Chemistry', topic: 'Chemical Bonding',
    question: 'Diamond and graphite are both made of carbon — they are examples of what?',
    answer: 'Allotropes of carbon',
    explanation: 'Allotropes are different structural forms of the same element. Diamond (tetrahedral, hard) vs graphite (layered, soft).',
    context: 'SSC CGL standard Recurring', examProb: 'Recurring',
    mnemonic: 'Allotropes = ALL same atom, different ROPE/structure',
  },
  {
    id: 34, subject: 'Chemistry', topic: 'Acids & Bases',
    question: 'Which indicator turns red in acid and blue in base?',
    answer: 'Litmus',
    explanation: 'Natural litmus from lichen turns red in acid (pH<7) and blue in base (pH>7). Neutral = purple.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Litmus test = Red Acid, Blue Base',
  },
  {
    id: 35, subject: 'Chemistry', topic: 'Metals',
    question: 'Stainless steel is an alloy of iron with which metals?',
    answer: 'Chromium and Nickel (Fe + Cr + Ni)',
    explanation: 'Stainless steel: ~10.5% Cr prevents oxidation; Ni adds toughness. The passive Cr₂O₃ layer prevents rust.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'Stainless = Stays Shiny = Cr (Chrome) protection',
  },
  {
    id: 36, subject: 'Chemistry', topic: 'Organic Chemistry',
    question: 'Which gas is produced when chlorine reacts with slaked lime? (used as bleaching powder)',
    answer: 'Bleaching powder = Ca(OCl)Cl / Calcium hypochlorite',
    explanation: 'Cl₂ + Ca(OH)₂ → CaOCl₂ + H₂O. Bleaching powder releases Cl₂ when with dilute acid — the active bleaching agent.',
    context: 'SSC CGL 2024', examProb: 'High',
    mnemonic: 'Bleaching powder = Chlorine locked in calcium',
  },

  // ── BIOLOGY ───────────────────────────────────────────────────────────────
  {
    id: 37, subject: 'Biology', topic: 'Cell Biology',
    question: 'Which organelle produces H₂O₂ during fatty acid oxidation?',
    answer: 'Peroxisomes',
    explanation: 'Peroxisomes contain enzymes like catalase that generate and then break down H₂O₂ — protecting the cell.',
    context: 'SSC CGL 10 Sep 2024 Shift 3', examProb: 'Confirmed',
    mnemonic: 'Peroxisome = H₂O₂ generator + destroyer',
  },
  {
    id: 38, subject: 'Biology', topic: 'Cell Biology',
    question: 'Ribosomes are present in which types of cells?',
    answer: 'Both prokaryotic and eukaryotic cells',
    explanation: 'All living cells need ribosomes for protein synthesis. Prokaryotes have 70S; eukaryotes have 80S ribosomes.',
    context: 'SSC CGL 2023–24', examProb: 'High',
    mnemonic: 'Ribosome = Ribs of ALL cells',
  },
  {
    id: 39, subject: 'Biology', topic: 'Cell Biology',
    question: 'Which cell organelle is called the "powerhouse of the cell"?',
    answer: 'Mitochondria',
    explanation: 'Mitochondria produce ATP through cellular respiration (Krebs cycle + oxidative phosphorylation).',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'Mito = Mighty powerhouse',
  },
  {
    id: 40, subject: 'Biology', topic: 'Genetics',
    question: 'Watson and Crick proposed the double helix model of DNA in which year?',
    answer: '1953',
    explanation: 'Published in Nature, April 1953. Used X-ray crystallography data from Rosalind Franklin.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: '1953 = DNA double helix birthday',
  },
  {
    id: 41, subject: 'Biology', topic: 'Human Body',
    question: 'Aquaporins are channel proteins that facilitate the transport of what?',
    answer: 'Water (across cell membranes)',
    explanation: 'Aquaporins allow rapid water movement across membranes. Nobel Prize in Chemistry 2003 (Peter Agre).',
    context: 'SSC CGL 2024 GA', examProb: 'High',
    mnemonic: 'Aqua = water, Pore = channel = water channel',
  },
  {
    id: 42, subject: 'Biology', topic: 'Disease & Vaccines',
    question: 'AdFalciVax is a vaccine developed for which disease?',
    answer: 'Malaria (Plasmodium falciparum)',
    explanation: 'AdFalciVax uses adenovirus vector to deliver malaria antigens. P. falciparum is the deadliest malaria parasite.',
    context: 'Current Affairs 2024', examProb: 'Hot',
    mnemonic: 'Ad-FALCI-vax = FALCIparum vaccine',
  },
  {
    id: 43, subject: 'Biology', topic: 'Human Body',
    question: 'Which blood group is known as the "universal donor"?',
    answer: 'O negative (O⁻)',
    explanation: 'O⁻ red cells lack ABO antigens and Rh factor — can be given to any patient in emergency.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'O⁻ = Opens to All (universal donor)',
  },
  {
    id: 44, subject: 'Biology', topic: 'Human Body',
    question: 'Which organ produces insulin in the human body?',
    answer: 'Pancreas (beta cells of islets of Langerhans)',
    explanation: 'Insulin lowers blood glucose by promoting cellular uptake. Deficiency causes Type 1 diabetes.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'PancreAs = regulates sugAr with Insulin',
  },
  {
    id: 45, subject: 'Biology', topic: 'Plant Biology',
    question: 'Which process converts light energy into chemical energy in plants?',
    answer: 'Photosynthesis',
    explanation: '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Occurs in chloroplasts using chlorophyll.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Photo = light + Synthesis = building = light building sugar',
  },
  {
    id: 46, subject: 'Biology', topic: 'Human Body',
    question: 'The hardest substance in the human body is?',
    answer: 'Tooth enamel',
    explanation: 'Tooth enamel (96% hydroxyapatite) is rated 5 on Mohs scale — harder than bone.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'Enamel = hardest shell of the body',
  },
  {
    id: 47, subject: 'Biology', topic: 'Genetics',
    question: 'The study of heredity and variation is called?',
    answer: 'Genetics',
    explanation: 'Gregor Mendel is the Father of Genetics. Modern genetics includes molecular genetics and genomics.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'GENetics = GENE study',
  },
  {
    id: 48, subject: 'Biology', topic: 'Disease & Vaccines',
    question: 'Which vitamin deficiency causes Scurvy?',
    answer: 'Vitamin C (Ascorbic acid)',
    explanation: 'Vitamin C is needed for collagen synthesis. Deficiency → bleeding gums, weakened immune system.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'sCurvy = no C vitamin',
  },
  {
    id: 49, subject: 'Biology', topic: 'Disease & Vaccines',
    question: 'Malaria is caused by which parasite and transmitted by which mosquito?',
    answer: 'Plasmodium parasite; female Anopheles mosquito',
    explanation: 'Plasmodium falciparum causes deadliest malaria. Female Anopheles mosquito is the vector.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'ANOpheles = ANOther malaria carrier',
  },
  {
    id: 50, subject: 'Biology', topic: 'Human Body',
    question: 'Which part of the brain controls balance and coordination?',
    answer: 'Cerebellum',
    explanation: 'Cerebellum (little brain) coordinates voluntary movements, balance and posture.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'CerebelLUM = baLANce UMbrella of the brain',
  },
  {
    id: 51, subject: 'Biology', topic: 'Cell Biology',
    question: 'Which organelle is called the "suicide bag" of the cell?',
    answer: 'Lysosome',
    explanation: 'Lysosomes contain digestive enzymes. When ruptured, they digest the cell itself — hence "suicide bag".',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'LYSOsome = LYSIS (cell death) bag',
  },
  {
    id: 52, subject: 'Biology', topic: 'Plant Biology',
    question: 'The green pigment in plants responsible for photosynthesis is?',
    answer: 'Chlorophyll',
    explanation: 'Chlorophyll a and b absorb red and blue light, reflecting green — hence plants look green.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Chloro = green, phyll = leaf pigment',
  },
  {
    id: 53, subject: 'Biology', topic: 'Human Body',
    question: 'Which gland is known as the "master gland"?',
    answer: 'Pituitary gland',
    explanation: 'Pituitary secretes hormones that control other endocrine glands (thyroid, adrenal, gonads).',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'Pituitary = Pilot (master) of hormone HQ',
  },
  {
    id: 54, subject: 'Biology', topic: 'Human Body',
    question: 'The largest gland in the human body is?',
    answer: 'Liver',
    explanation: 'Liver (1.5 kg) performs 500+ functions: bile production, detoxification, glycogen storage.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: 'LIVER = LargestInternal organ & Vital Engine of Reactions',
  },
  {
    id: 55, subject: 'Biology', topic: 'Nutrition',
    question: 'Which vitamin is synthesized in the skin on exposure to sunlight?',
    answer: 'Vitamin D',
    explanation: 'UV-B radiation converts 7-dehydrocholesterol in skin to Vitamin D₃ (cholecalciferol).',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'D = Day (sunlight) vitamin',
  },
  {
    id: 56, subject: 'Biology', topic: 'Disease & Vaccines',
    question: 'AIDS is caused by which virus?',
    answer: 'HIV (Human Immunodeficiency Virus)',
    explanation: 'HIV attacks CD4+ T-cells (helper T-cells), destroying the immune system. No cure, but ART controls it.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'HIV = Hunts Immune Vessels',
  },
  {
    id: 57, subject: 'Biology', topic: 'Cell Biology',
    question: 'Cell wall of fungi is made up of?',
    answer: 'Chitin',
    explanation: 'Fungi cell wall = chitin (N-acetyl glucosamine polymer). Plants = cellulose; bacteria = peptidoglycan.',
    context: 'SSC CGL 2023–24', examProb: 'High',
    mnemonic: 'Chitin = CHItinous fungi coat',
  },
  {
    id: 58, subject: 'Biology', topic: 'Genetics',
    question: 'Which nitrogenous base pairs with Adenine in DNA?',
    answer: 'Thymine (A-T pair; 2 hydrogen bonds)',
    explanation: "Chargaff's rules: A=T (2 H-bonds), G≡C (3 H-bonds). In RNA, Uracil replaces Thymine (A-U pair).",
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'AT(e) a GC cookie = A-T, G-C pairs',
  },
  {
    id: 59, subject: 'Biology', topic: 'Human Body',
    question: 'The normal RBC count in adult males (per mm³) is approximately?',
    answer: '5 million per mm³ (4.7–6.1 million)',
    explanation: 'RBCs carry haemoglobin for oxygen transport. Low count = anaemia.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: '5 million RBCs = keep you alive and kicking',
  },
  {
    id: 60, subject: 'Biology', topic: 'Human Body',
    question: 'Which is the longest bone in the human body?',
    answer: 'Femur (thigh bone)',
    explanation: 'Femur (thigh bone) is about 25% of total body height and the strongest bone.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'FEmur = FEmale dancers have long thighs',
  },
  {
    id: 61, subject: 'Biology', topic: 'Human Body',
    question: 'The smallest bone in the human body is located where?',
    answer: 'Stapes — in the middle ear',
    explanation: 'Stapes (stirrup bone) is ~3mm long. The three ear ossicles are malleus, incus, stapes.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'Stapes = Smallest stirrup in the ear',
  },

  // ── SPACE & DEFENSE ───────────────────────────────────────────────────────
  // SpaDeX moved to id 86 with more detail
  // Aditya-L1 position moved to id 90 with more detail
  {
    id: 64, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: 'Chandrayaan-3 achieved what historic first on August 23, 2023?',
    answer: "First ever soft landing at the Moon's South Pole",
    explanation: 'Vikram lander and Pragyan rover operated for ~14 Earth days. India = 4th nation to soft-land on Moon.',
    context: 'SSC CGL 2024 / Current Affairs Aug 2023', examProb: 'Hot',
    mnemonic: 'Chandrayaan-3 = CHANDRA (Moon) landing at SOUTH pole',
  },
  // NISAR moved to id 87 with updated launch details
  {
    id: 66, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: 'Proba-3 satellite was launched by ISRO using which rocket?',
    answer: 'PSLV-C59',
    explanation: 'Proba-3 (ESA mission) launched Dec 2024 via PSLV-C59 from Sriharikota. Studies solar corona.',
    context: 'Current Affairs Dec 2024', examProb: 'High',
    mnemonic: 'Proba = Probe-3 = ESA via PSLV',
  },
  {
    id: 67, subject: 'Space & Defense', topic: 'Human Spaceflight',
    question: 'Who will be the 2nd Indian to travel to the ISS as part of Axiom Mission 4?',
    answer: 'Group Captain Shubhanshu Shukla (IAF)',
    explanation: "Shubhanshu Shukla is the ISS mission specialist for Axiom Mission 4 (planned 2025). Rakesh Sharma was the 1st Indian in space (1984).",
    context: 'Current Affairs 2024–25', examProb: 'Hot',
    mnemonic: "Shukla = Shining hope for India's ISS mission",
  },
  {
    id: 68, subject: 'Space & Defense', topic: 'Defense',
    question: 'India signed a deal to purchase 26 Rafale-M jets from which country?',
    answer: 'France',
    explanation: "Signed April 2025. Rafale-M (Marine version) for Indian Navy's INS Vikrant aircraft carrier. Dassault Aviation.",
    context: 'Current Affairs 2025', examProb: 'Hot',
    mnemonic: 'Rafale = French fighter jet for Indian Navy',
  },
  {
    id: 69, subject: 'Space & Defense', topic: 'Defense',
    question: "India's deep-sea submersible MATSYA 6000 can dive to what depth?",
    answer: '6000 metres (6 km)',
    explanation: "MATSYA 6000 part of Samudrayaan mission — India's first crewed deep-sea mission for mineral exploration.",
    context: 'Current Affairs 2024', examProb: 'Hot',
    mnemonic: 'MATSYA 6000 = Fish (matsya) that dives 6 km deep',
  },
  {
    id: 70, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: "India's first satellite Aryabhata was launched in which year?",
    answer: '1975',
    explanation: 'Aryabhata (19 April 1975) was launched by the Soviet Kosmos-3M rocket from Kapustin Yar. Named after the ancient mathematician.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: "Aryabhata 1975 = India's first step to space",
  },
  {
    id: 71, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: 'MOM (Mangalyaan) made India the __ nation to reach Mars and the first to succeed in its first attempt.',
    answer: '4th nation (and first to succeed on maiden attempt)',
    explanation: 'Mars Orbiter Mission launched Nov 2013, entered Mars orbit Sep 2014. Cost only ₹450 crore.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'MOM = Mars On Mission, 1st attempt success',
  },
  // Operation Sindoor moved to id 93 with Pahalgam attack context
  {
    id: 73, subject: 'Space & Defense', topic: 'Defense',
    question: 'BrahMos is a supersonic cruise missile jointly developed by India and which country?',
    answer: 'Russia (BRAHmaputra + MOScva river names)',
    explanation: 'BrahMos = BRAHMOS Aerospace. Speed ~2.8 Mach, range 290–800 km. Air, Land, Sea-launched variants.',
    context: 'SSC CGL 2022–23', examProb: 'High',
    mnemonic: 'BrahMos = BRAHmaputra + MOScva = Indo-Russian missile',
  },
  {
    id: 74, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: "Gaganyaan is India's first human spaceflight mission — which organisation is implementing it?",
    answer: 'ISRO (Indian Space Research Organisation)',
    explanation: 'Gaganyaan aims to send 3 Indian astronauts (Gagannauts) to 400 km orbit for 3 days. Uncrewed test flights first.',
    context: 'Current Affairs 2024–25', examProb: 'Hot',
    mnemonic: "Gagan = sky, Yaan = vehicle = India's sky vehicle",
  },
  {
    id: 75, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: "Which ISRO mission studies the Sun's corona and was India's first solar observatory?",
    answer: 'Aditya-L1',
    explanation: 'Launched Sep 2023, reached L1 Jan 2024. Payloads include VELC (corona study), SUIT (UV imaging).',
    context: 'SSC CGL 2024', examProb: 'Hot',
    mnemonic: "Aditya = Sun god = India's Sun watcher at L1",
  },

  // ── TECHNOLOGY ────────────────────────────────────────────────────────────
  // BharatGen moved to id 102 with more detail
  {
    id: 77, subject: 'Technology', topic: 'Internet & Networks',
    question: 'What does "5G" stand for in telecommunications?',
    answer: '5th Generation mobile network',
    explanation: '5G offers speeds up to 20 Gbps, ultra-low latency (~1ms). Launched in India Oct 2022.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: '5G = 5th Generation = 10x faster than 4G',
  },
  {
    id: 78, subject: 'Technology', topic: 'Cybersecurity',
    question: 'What is a "Trojan Horse" in computer security?',
    answer: 'Malware disguised as legitimate software',
    explanation: "Like the mythological Trojan horse — appears useful but hides malicious code. Unlike viruses, doesn't self-replicate.",
    context: 'SSC CGL 2023 GA', examProb: 'High',
    mnemonic: 'Trojan = disguised dangerous entry',
  },
  {
    id: 79, subject: 'Technology', topic: 'AI & Computing',
    question: 'The full form of CPU is?',
    answer: 'Central Processing Unit',
    explanation: "CPU = brain of computer. Executes instructions, performs arithmetic/logic. Contains ALU + CU + registers.",
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: "CPU = Computer's Primary Unit of thinking",
  },
  {
    id: 80, subject: 'Technology', topic: 'Space Tech',
    question: "India's UPI (Unified Payments Interface) is managed by which organisation?",
    answer: 'NPCI (National Payments Corporation of India)',
    explanation: 'UPI launched Apr 2016 by NPCI. Over 14 billion transactions/month by 2024. Uses IMPS infrastructure.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: "UPI = United by NPCI's Payments Infrastructure",
  },
  {
    id: 81, subject: 'Technology', topic: 'Internet & Networks',
    question: 'WWW was invented by which scientist, in which year?',
    answer: '1989 (proposed) / 1991 (public)',
    explanation: 'Proposed at CERN in 1989. First website went live August 6, 1991. HTML + HTTP + URL.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: "Tim Berners-Lee = The Web's Father, 1989",
  },
  {
    id: 82, subject: 'Technology', topic: 'AI & Computing',
    question: "India's indigenous mobile operating system developed by C-DAC is called?",
    answer: 'BharOS',
    explanation: 'BharOS developed at IIT Madras / JandK Operations. Android-compatible but without Google dependency.',
    context: 'Current Affairs 2023', examProb: 'High',
    mnemonic: "BharOS = Bharat's Own operating System",
  },
  {
    id: 83, subject: 'Technology', topic: 'Internet & Networks',
    question: 'Which protocol is used to send emails?',
    answer: 'SMTP (Simple Mail Transfer Protocol)',
    explanation: 'SMTP (port 25/587) sends emails. POP3/IMAP receive emails. HTTP ≠ email.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'SMTP = Send Mail To Person',
  },
  {
    id: 84, subject: 'Technology', topic: 'Biotechnology',
    question: 'CRISPR-Cas9 is a tool used for what in biotechnology?',
    answer: 'Gene editing (precise DNA modification)',
    explanation: 'CRISPR-Cas9 = molecular scissors that cut DNA at specific sequences. Nobel Prize 2020 (Doudna & Charpentier).',
    context: 'Current Affairs / SSC GA 2024', examProb: 'High',
    mnemonic: 'CRISPR = Cutting Rapidly Into Specific Precise Regions',
  },
  {
    id: 85, subject: 'Technology', topic: 'Space Tech',
    question: "India's first quantum computer was developed by which organization in 2023?",
    answer: 'C-DAC (under National Quantum Mission)',
    explanation: "India's National Quantum Mission (2023) with ₹6003 crore budget. C-DAC working on 50-qubit quantum computer.",
    context: 'Current Affairs 2023–24', examProb: 'High',
    mnemonic: 'Quantum India = C-DAC leads the qubit quest',
  },

  // ── 2025–2026 CURRENT AFFAIRS: SPACE TECHNOLOGY ─────────────────────────
  {
    id: 86, subject: 'Space & Defense', topic: 'ISRO SpaDeX',
    question: 'ISRO\'s SpaDeX mission (Dec 2024) made India the ___ country to achieve in-space docking?',
    answer: '4th country (after USA, Russia, China)',
    explanation: 'SpaDeX (Space Docking Experiment) launched on PSLV-C60 on 30 Dec 2024. SDX01 (Chaser) and SDX02 (Target) docked on 16 Jan 2025 at 475 km orbit. Technology is critical for Chandrayaan-4 and Gaganyaan.',
    context: 'Current Affairs Jan 2025 — very hot for SSC', examProb: 'Hot',
    mnemonic: 'SpaDeX = Space Docking Experiment = 4th nation club',
  },
  {
    id: 87, subject: 'Space & Defense', topic: 'ISRO NISAR',
    question: 'NISAR satellite launched in July 2025 is a joint mission of which two agencies?',
    answer: 'NASA and ISRO',
    explanation: 'NISAR (NASA-ISRO Synthetic Aperture Radar) launched on GSLV-F16 on 30 July 2025. Cost ~$1.5 billion. Uses dual-frequency SAR to track Earth surface changes — forests, ice, crustal movements. Operational from Nov 2025.',
    context: 'Current Affairs Jul 2025', examProb: 'Hot',
    mnemonic: 'NISAR = NASA-ISRO SAR = two flags on one satellite',
  },
  {
    id: 88, subject: 'Space & Defense', topic: 'ISRO Gaganyaan',
    question: 'What is the name of the humanoid robot developed by ISRO for the Gaganyaan mission?',
    answer: 'Vyommitra',
    explanation: 'Vyommitra (Vyom = space, Mitra = friend) is a half-humanoid robot to fly on uncrewed Gaganyaan missions before astronauts. The G1 uncrewed flight is planned for 2026. Total budget: ~Rs 20,193 crore.',
    context: 'Current Affairs 2025–26', examProb: 'Hot',
    mnemonic: 'Vyommitra = Space Friend robot on Gaganyaan',
  },
  {
    id: 89, subject: 'Space & Defense', topic: 'ISRO Chandrayaan-4',
    question: 'Chandrayaan-4 is planned as what type of lunar mission?',
    answer: 'Lunar Sample Return mission (up to 3 kg regolith)',
    explanation: 'Chandrayaan-4 will be launched in two phases on two LVM3 rockets. Spacecraft assembled via docking in Earth orbit before heading to Moon. Expected launch ~2028. Landing proposed at Mons Mouton near lunar south pole.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'C4 = Collect and Come back (sample return)',
  },
  {
    id: 90, subject: 'Space & Defense', topic: 'Aditya-L1',
    question: 'Aditya-L1 orbits around which Lagrange point and what is its distance from Earth?',
    answer: 'L1 point, about 1.5 million km from Earth',
    explanation: 'Launched 2 Sep 2023, reached L1 on 6 Jan 2024. Takes 178 days per halo orbit. First Indian solar observatory. First set of scientific data released to global community on 6 Jan 2025. Captured first-ever image of solar flare kernel.',
    context: 'Current Affairs 2024–25', examProb: 'Hot',
    mnemonic: 'Aditya (Sun) at L1 = 1.5 million km watch post',
  },
  {
    id: 91, subject: 'Space & Defense', topic: 'NASA Artemis',
    question: 'Artemis II (launched April 2026) is the first crewed mission beyond low Earth orbit since which mission?',
    answer: 'Apollo 17 (1972)',
    explanation: 'Artemis II carries 4 astronauts (incl. first woman and first person of color to leave low Earth orbit) on a lunar flyby using SLS rocket and Orion spacecraft. Victor Glover = first person of color, Christina Koch = first woman beyond LEO.',
    context: 'Current Affairs Apr 2026', examProb: 'Hot',
    mnemonic: 'Artemis II = After 50+ years, humans return moonward',
  },
  {
    id: 92, subject: 'Space & Defense', topic: 'NASA Artemis',
    question: 'NASA cancelled which planned space station in March 2026?',
    answer: 'Lunar Gateway',
    explanation: 'NASA cancelled the Lunar Gateway orbital station and will instead build a lunar surface base (2029-2036). SLS Block 1B and Block 2 upgrades were also cancelled. Artemis IV (~2028) is now the first potential lunar landing mission.',
    context: 'Current Affairs Mar 2026', examProb: 'High',
    mnemonic: 'Gateway gone = Ground base instead',
  },

  // ── 2025–2026 CURRENT AFFAIRS: DEFENSE TECHNOLOGY ───────────────────────
  {
    id: 93, subject: 'Space & Defense', topic: 'Operation Sindoor',
    question: 'Operation Sindoor (May 2025) was launched in response to which terrorist attack?',
    answer: '2025 Pahalgam attack (22 April 2025, 26 civilians killed)',
    explanation: 'IAF struck 9 terror camps in Pakistan and PoK on 7 May 2025 — first Indian strikes across international boundary since 1971. Used BrahMos missiles, Akashteer air defense. 5-day conflict ended with ceasefire on 10 May 2025.',
    context: 'Current Affairs May 2025 — extremely important', examProb: 'Hot',
    mnemonic: 'Sindoor = Strike In Nine DOmains of terror Response',
  },
  {
    id: 94, subject: 'Space & Defense', topic: 'Agni-5 MIRV',
    question: 'India tested Agni-5 with MIRV technology under which operation name in 2024?',
    answer: 'Operation Divyastra (Mission Divyastra)',
    explanation: 'Tested March 2024. MIRV = Multiple Independently Targetable Reentry Vehicles. India joined USA, Russia, China, France in MIRV club. Agni-5 range: 5,000+ km. Routine test again on 20 Aug 2025.',
    context: 'Current Affairs 2024–25', examProb: 'Hot',
    mnemonic: 'Divyastra = Divine weapon with Multiple warheads',
  },
  {
    id: 95, subject: 'Space & Defense', topic: 'Agni-P',
    question: 'India test-fired Agni-P from a rail-based mobile launcher in September 2025. What is unique about this?',
    answer: 'First-of-its-kind rail-based launch for an Indian ballistic missile',
    explanation: 'Agni-P is a nuclear-capable intermediate-range ballistic missile. Rail-based launch provides cross-country mobility and reduced visibility, enhancing survivability of nuclear deterrent.',
    context: 'Current Affairs Sep 2025', examProb: 'High',
    mnemonic: 'Agni-P on a train = mobile nuclear deterrent',
  },
  {
    id: 96, subject: 'Space & Defense', topic: 'S-400 Air Defense',
    question: 'India procured the S-400 air defense system from which country and for how much?',
    answer: 'Russia, under a $5.43 billion contract (2018)',
    explanation: 'India ordered 5 S-400 squadrons. 3 delivered by 2025, 4th expected May 2026. S-400 saw combat use during Operation Sindoor (May 2025). Range up to ~400 km.',
    context: 'Current Affairs 2025–26', examProb: 'High',
    mnemonic: 'S-400 = Shield from Russia, 5.4 billion deal',
  },
  {
    id: 97, subject: 'Space & Defense', topic: 'BrahMos Export',
    question: 'Which country signed an agreement to purchase BrahMos missiles from India in March 2026?',
    answer: 'Indonesia',
    explanation: 'Indonesia signed BrahMos deal in March 2026 ($200-350 million). Philippines was first BrahMos export customer (2022). At least 14 countries have expressed interest. BrahMos indigenous content is about 70%.',
    context: 'Current Affairs Mar 2026', examProb: 'High',
    mnemonic: 'BrahMos exports = Philippines first, Indonesia second',
  },
  {
    id: 98, subject: 'Space & Defense', topic: 'INS Vikrant',
    question: 'INS Vikrant is India\'s first indigenously built aircraft carrier. What percentage of its components are indigenous?',
    answer: 'Over 76% indigenous components',
    explanation: 'Built at Cochin Shipyard, commissioned Sep 2022. Deployed in Operation Sindoor. India planning nuclear-powered carrier INS Vishal with CATOBAR + electromagnetic catapult. Navy plans 175-200 warships by 2035.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'Vikrant = Brave + 76% Made in India',
  },
  {
    id: 99, subject: 'Space & Defense', topic: 'DRDO Hypersonics',
    question: 'DRDO\'s hypersonic missile "Dhvani" is designed to achieve speeds up to?',
    answer: 'Mach 6',
    explanation: 'Dhvani has a projected 1,500 km strike range. DRDO also tested scramjet combustor running 1000+ seconds in April 2025. BrahMos-II hypersonic variant (based on Zircon tech) prototype expected 2026-27.',
    context: 'Current Affairs 2025–26', examProb: 'High',
    mnemonic: 'Dhvani = Sound of Mach 6 speed',
  },
  {
    id: 100, subject: 'Space & Defense', topic: 'AMCA Fighter',
    question: 'What is AMCA in Indian defense context?',
    answer: 'Advanced Medium Combat Aircraft — India\'s 5th generation stealth fighter',
    explanation: 'AMCA first prototype rollout planned 2026-27, maiden flight 2028. Uses GE F414 engines initially. Full operational capability by 2035. Part of DRDO 2.0 strategy for next-gen defense tech.',
    context: 'Current Affairs 2025–26', examProb: 'High',
    mnemonic: 'AMCA = Advanced Medium Combat Aircraft = 5th Gen stealth',
  },

  // ── 2025–2026 CURRENT AFFAIRS: IT & DIGITAL TECHNOLOGY ──────────────────
  {
    id: 101, subject: 'Technology', topic: 'IndiaAI Mission',
    question: 'What is the total budget of the IndiaAI Mission approved in March 2024?',
    answer: 'Rs 10,371.92 crore over 5 years',
    explanation: 'IndiaAI Mission focuses on AI compute (38,000 GPUs at Rs 65/hour), datasets (AIKosh platform), AI applications, startups, and responsible AI. Three AI Centres of Excellence in Healthcare, Agriculture, Sustainable Cities.',
    context: 'Current Affairs 2024–25', examProb: 'Hot',
    mnemonic: 'IndiaAI = 10K crore + 38K GPUs',
  },
  {
    id: 102, subject: 'Technology', topic: 'BharatGen AI',
    question: 'BharatGen is India\'s first government-funded multimodal AI model. Which institute leads it?',
    answer: 'IIT Bombay',
    explanation: 'BharatGen processes text, speech, and images. Designed for Indian languages beyond English dominance. Part of the broader IndiaAI Mission ecosystem.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'BharatGen = Bharat Generation of AI from IIT-B',
  },
  {
    id: 103, subject: 'Technology', topic: 'Semiconductor',
    question: 'India Semiconductor Mission 2.0 was announced in which Union Budget with what provision?',
    answer: 'Union Budget 2026-27, with Rs 1,000 crore for research, training and workforce development',
    explanation: 'Part of India\'s push for semiconductor self-reliance. India Semiconductor Mission 1.0 launched in 2021. Major fabs being set up by Tata (Dholera, Gujarat) and others.',
    context: 'Current Affairs Feb 2026', examProb: 'High',
    mnemonic: 'Semiconductor 2.0 = Budget 2026-27 = Rs 1000 crore',
  },
  {
    id: 104, subject: 'Technology', topic: 'Digital India',
    question: 'Digital India programme completed how many years in July 2025?',
    answer: '10 years (launched 1 July 2015)',
    explanation: 'India ranks 3rd globally in digitalization. Digital economy contributes 11.74% to GDP (2022-23), projected to reach 20% by 2030. 5G covers 99.9% of districts.',
    context: 'Current Affairs Jul 2025', examProb: 'High',
    mnemonic: 'Digital India = 10 years in 2025 = 3rd global rank',
  },
  {
    id: 105, subject: 'Technology', topic: 'Indigenous Processor',
    question: 'DHRUV64 is India\'s first fully indigenous 64-bit microprocessor. Which architecture does it use?',
    answer: 'RISC-V (open-source architecture), developed by C-DAC',
    explanation: 'DHRUV64 marks India\'s entry into indigenous chip design. Based on open-source RISC-V, avoiding dependency on proprietary ARM/x86 architectures.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'DHRUV64 = C-DAC + RISC-V = India\'s own processor',
  },
  {
    id: 106, subject: 'Technology', topic: 'Quantum Computing',
    question: 'QpiAI launched India\'s first full-stack quantum computer with how many qubits?',
    answer: '25 qubits',
    explanation: 'India\'s first full-stack 25-qubit quantum computer integrates hardware, software, and control systems indigenously. Supports drug discovery and logistics. Backed by the National Quantum Mission.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'QpiAI = 25 Qubits = India\'s quantum leap',
  },

  // ── 2025–2026 CURRENT AFFAIRS: NUCLEAR & ENERGY TECHNOLOGY ──────────────
  {
    id: 107, subject: 'Technology', topic: 'Nuclear Mission',
    question: 'India\'s Union Budget 2025-26 set a nuclear power capacity target of how much by 2047?',
    answer: '100 GW by 2047',
    explanation: 'Current capacity ~8,880 MW (25 reactors). Rs 20,000 crore allocated for SMR R&D. Target: 5 indigenous SMRs by 2033. SHANTI Act (Dec 2025) opened nuclear sector to private investment with 49% FDI.',
    context: 'Current Affairs 2025–26', examProb: 'Hot',
    mnemonic: '100 GW by 2047 = Nuclear India vision',
  },
  {
    id: 108, subject: 'Technology', topic: 'SHANTI Act',
    question: 'What does the SHANTI Act (December 2025) stand for in India\'s nuclear context?',
    answer: 'Sustainable Harnessing and Advancement of Nuclear Energy for Transforming India',
    explanation: 'SHANTI Act is a historic reform allowing private sector participation in nuclear energy. Permits 49% FDI, reforms liability frameworks. Tata Power, Reliance, Adani, JSW among interested companies.',
    context: 'Current Affairs Dec 2025', examProb: 'Hot',
    mnemonic: 'SHANTI = peaceful nuclear reform for private players',
  },
  {
    id: 109, subject: 'Technology', topic: 'Renewable Energy',
    question: 'India crossed which milestone for solar energy installed capacity in January 2025?',
    answer: '100 GW solar capacity',
    explanation: 'Solar reached 132.85 GW by Nov 2025. India surpassed Japan as 3rd largest solar producer. Total renewable capacity: 258 GW by Dec 2025. India achieved 50% non-fossil fuel capacity 5 years early (51.5% by Nov 2025).',
    context: 'Current Affairs 2025', examProb: 'Hot',
    mnemonic: '100 GW solar club = Jan 2025 = 3rd global rank',
  },
  {
    id: 110, subject: 'Technology', topic: 'Renewable Energy',
    question: 'India added a record ___ GW of renewable energy capacity in 2025?',
    answer: '50 GW (highest ever, supported by Rs 2 trillion investment)',
    explanation: 'Total renewable capacity went from 209,444 MW to 258,008 MW in one year. India targets 500 GW renewable by 2030 and net-zero by 2070. PM Surya Ghar Yojana targets 1 crore rooftop solar homes by FY 2026-27.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: '50 GW in one year = India\'s green record',
  },

  // ── 2025–2026 CURRENT AFFAIRS: BIOTECH & HEALTH TECH ────────────────────
  {
    id: 111, subject: 'Technology', topic: 'Biotechnology',
    question: 'India\'s biotech sector grew from $10 billion in 2014 to approximately how much by 2024?',
    answer: '$165.7 billion (target: $300 billion by 2030)',
    explanation: 'India is world\'s largest vaccine manufacturer, 3rd largest biotech hub in Asia-Pacific, 12th globally. BioE3 Policy focuses on smart proteins, precision biotherapeutics, carbon capture, space-marine biotech.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'Biotech = $10B to $165B in 10 years',
  },
  {
    id: 112, subject: 'Technology', topic: 'Genomics',
    question: 'GenomeIndia project mapped how many whole genome sequences of Indians?',
    answer: 'Over 10,000 whole genome sequences',
    explanation: 'The Indian Genomic Data Set covers diverse Indian communities and has been made globally accessible. Helps understand genetic basis of diseases specific to Indian population.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'GenomeIndia = 10K genomes = India\'s DNA map',
  },
  {
    id: 113, subject: 'Technology', topic: 'Health Tech',
    question: 'India\'s first National Biofoundry Network launched in 2025 has how many biofoundries?',
    answer: '6 biofoundries',
    explanation: 'Part of BioE3 Policy implementation. Includes a high-performance biomanufacturing platform. Supports biotech R&D and scale-up across India.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: '6 Biofoundries = India\'s bio-manufacturing backbone',
  },

  // ── 2025–2026 CURRENT AFFAIRS: AWARDS, DISCOVERIES, MISC ───────────────
  {
    id: 114, subject: 'Technology', topic: 'Nobel Prize 2025',
    question: 'Who won the Nobel Prize in Physics 2025 and for what?',
    answer: 'John Clarke, Michel Devoret, and John Martinis — for discovery of macroscopic quantum tunnelling and energy quantisation in electric circuits',
    explanation: 'Their work confirmed quantum phenomena manifest in macroscopic systems. Chemistry 2025: Kitagawa, Robson, Yaghi for Metal-Organic Frameworks. Medicine 2025: Brunkow, Ramsdell, Sakaguchi for regulatory T cells.',
    context: 'Current Affairs Oct 2025', examProb: 'Hot',
    mnemonic: 'Physics 2025 = Quantum goes macro (Clarke-Devoret-Martinis)',
  },
  {
    id: 115, subject: 'Technology', topic: 'Nobel Prize 2025',
    question: 'Nobel Prize in Chemistry 2025 was awarded for the development of which materials?',
    answer: 'Metal-Organic Frameworks (MOFs) — to Kitagawa, Robson, and Yaghi',
    explanation: 'MOFs are porous crystalline materials with vast applications in gas storage, carbon capture, drug delivery, and catalysis. One of the most exciting material science breakthroughs.',
    context: 'Current Affairs Oct 2025', examProb: 'Hot',
    mnemonic: 'Chemistry 2025 = MOFs = Metal Organic Frameworks',
  },
  {
    id: 116, subject: 'Technology', topic: 'Nobel Prize 2025',
    question: 'Nobel Peace Prize 2025 was awarded to whom?',
    answer: 'Maria Corina Machado — for promoting democratic rights in Venezuela',
    explanation: 'She united a divided political opposition to peacefully strive for free elections and transition from dictatorship. Economics 2025: Mokyr, Aghion, Howitt for innovation-driven economic growth theory.',
    context: 'Current Affairs Oct 2025', examProb: 'Hot',
    mnemonic: 'Peace 2025 = Machado of Venezuela = Democracy fighter',
  },
  {
    id: 117, subject: 'Technology', topic: 'Rashtriya Vigyan Puraskar',
    question: 'What are the three categories of the Rashtriya Vigyan Puraskar (National Science Award)?',
    answer: 'Vigyan Ratna (lifetime), Vigyan Shri (distinguished), Vigyan Yuva-Shanti Swarup Bhatnagar (young scientists under 45)',
    explanation: 'One of the highest honors in Indian science. 2nd edition presented by President in Dec 2025, honoring 24 recipients. Replaced the previous Shanti Swarup Bhatnagar Prize framework.',
    context: 'Current Affairs Dec 2025', examProb: 'High',
    mnemonic: 'RVP = Ratna + Shri + Yuva = India\'s top science awards',
  },
  {
    id: 118, subject: 'Technology', topic: 'Defense Self-Reliance',
    question: 'India now produces approximately what percentage of its defense equipment indigenously?',
    answer: 'About 65% (reversed from 65% imports a decade ago)',
    explanation: 'Rs 1 lakh crore defense fund announced for deep-tech. Rs 1.30 lakh crore worth of Acceptance of Necessity approvals in 2025 — highest ever. DRDO 2.0 shifts conventional systems to private sector.',
    context: 'Current Affairs 2025–26', examProb: 'High',
    mnemonic: '65% self-made = India\'s defense flip from importer to maker',
  },
  {
    id: 119, subject: 'Technology', topic: 'Global Innovation',
    question: 'India\'s rank in the Global Innovation Index 2025 is?',
    answer: '38th',
    explanation: 'India ranked 6th globally in IP filings and 3rd in research publications. IP filings rose 44% in 5 years. India has 5.8 million STEM professionals (28% of global pool).',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'GII 38th + 3rd in research papers + 28% global STEM',
  },
  {
    id: 120, subject: 'Space & Defense', topic: 'DRDO Directed Energy',
    question: 'DRDO\'s laser-based Directed Energy Weapon tested in April 2025 is called?',
    answer: 'Sahastra Shakti (Mk-IIA)',
    explanation: 'Laser DEW for anti-drone warfare. DRDO also developing High-Power Microwave (HPM) system to disable quadcopter-class UAVs up to 1-5 km range. Part of DRDO 2.0 next-gen tech strategy.',
    context: 'Current Affairs Apr 2025', examProb: 'High',
    mnemonic: 'Sahastra Shakti = Thousand Powers = Laser weapon',
  },

  // ── NEW 2025–26 ADDITIONS (Space, Defense, Tech) ─────────────────────────
  {
    id: 121, subject: 'Space & Defense', topic: 'Defense',
    question: 'INS Arighaat, commissioned Aug 2024, is India\'s ___ nuclear-powered submarine (SSBN)?',
    answer: '2nd SSBN (after INS Arihant)',
    explanation: 'INS Arighaat commissioned 29 Aug 2024 at Visakhapatnam. 6,000 tonnes, 111.6 m long. Carries K-15 Sagarika (750 km) or K-4 (3,500 km) missiles. K-4 first launched from submarine 27 Nov 2024.',
    context: 'Current Affairs Aug 2024', examProb: 'Hot',
    mnemonic: 'Arighaat = Destroyer of enemies = 2nd SSBN',
  },
  {
    id: 122, subject: 'Space & Defense', topic: 'Defense',
    question: 'INS Aridhaman is India\'s ___ SSBN, with sea trials completed in 2025?',
    answer: '3rd SSBN (expected commissioning early 2026)',
    explanation: 'India\'s nuclear triad: INS Arihant (1st), INS Arighaat (2nd), INS Aridhaman (3rd). S4* (4th SSBN) also departed for sea trials. India plans 6 SSNs total, first by 2036–37.',
    context: 'Current Affairs 2025–26', examProb: 'High',
    mnemonic: 'Ari-series: Arihant → Arighaat → Aridhaman = 3 nuclear subs',
  },
  {
    id: 123, subject: 'Space & Defense', topic: 'Defense',
    question: 'Tejas Mk 2, India\'s indigenous 4.5-gen medium weight fighter, had its first flight in which quarter?',
    answer: 'Q1 2026 (Feb–Mar 2026)',
    explanation: 'Single-engine, canard delta wing, GE F414 engine, indigenous Uttam AESA radar. 82% indigenous content. To replace Jaguar, Mirage 2000, MiG-29 in IAF.',
    context: 'Current Affairs 2026', examProb: 'Hot',
    mnemonic: 'Tejas Mk 2 = 4.5G fighter flying in 2026',
  },
  {
    id: 124, subject: 'Space & Defense', topic: 'Defense',
    question: 'LR-AShM hypersonic anti-ship missile unveiled at Republic Day 2026 can achieve what speed?',
    answer: 'Mach 10 (initial), averages Mach 5',
    explanation: 'Long Range Anti-Ship Hypersonic Missile: indigenous avionics, two-stage solid propulsion, quasi-ballistic trajectory with multiple skips.',
    context: 'Current Affairs Jan 2026', examProb: 'Hot',
    mnemonic: 'LR-AShM = Long Range Anti-Ship Mach-10',
  },
  {
    id: 125, subject: 'Space & Defense', topic: 'Defense',
    question: 'Pralay is a quasi-ballistic surface-to-surface missile with what range?',
    answer: 'Up to 500 km; payload up to 1,000 kg',
    explanation: 'Solid propellant missile. Two successful flight tests in Jul 2025. Fills the tactical ballistic missile gap for Indian military.',
    context: 'Current Affairs Jul 2025', examProb: 'High',
    mnemonic: 'Pralay = devastation at 500 km',
  },
  {
    id: 126, subject: 'Space & Defense', topic: 'Defense',
    question: 'ERASR (Extended Range Anti-Submarine Rocket) was tested from which Indian Navy ship in Jul 2025?',
    answer: 'INS Kavaratti',
    explanation: 'Developed by DRDO\'s ARDE, Pune. User trials completed Jul 2025. Enhances anti-submarine warfare capability of the Indian Navy.',
    context: 'Current Affairs Jul 2025', examProb: 'High',
    mnemonic: 'ERASR from Kavaratti = Erase submarine threats',
  },
  {
    id: 127, subject: 'Space & Defense', topic: 'Space Exploration',
    question: 'JWST discovered a new (29th) moon of which planet?',
    answer: 'Uranus',
    explanation: 'James Webb Space Telescope also made first direct image of a Saturn-mass exoplanet, found organic molecules (benzene, methane) outside Milky Way, and observed interstellar comet 3I/ATLAS (Mar 2026).',
    context: 'Current Affairs 2025–26', examProb: 'High',
    mnemonic: 'JWST: 29th Uranus moon + organic molecules beyond Milky Way',
  },
  {
    id: 128, subject: 'Space & Defense', topic: 'Space Exploration',
    question: 'The International Space Station (ISS) is planned for retirement/deorbit in which year?',
    answer: 'January 2031',
    explanation: 'Operations committed through 2030. SpaceX awarded $843 million contract for deorbit vehicle (modified Dragon with 46 Draco thrusters). Final crash at Point Nemo in Pacific Ocean.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'ISS retires 2031 at Point Nemo',
  },
  {
    id: 129, subject: 'Technology', topic: 'Supercomputer',
    question: 'India\'s fastest supercomputer AIRAWAT is located at which facility?',
    answer: 'C-DAC Pune (ranked 188th globally, Nov 2025)',
    explanation: 'Under National Supercomputing Mission (NSM): 37 supercomputers deployed, 40 Petaflops total capacity. PARAM SHAKTI facility launched at IIT Madras on 3 Jan 2026.',
    context: 'Current Affairs 2025', examProb: 'High',
    mnemonic: 'AIRAWAT at Pune = India\'s fastest compute brain',
  },
  {
    id: 130, subject: 'Technology', topic: 'Quantum Computing',
    question: 'India\'s first 64-qubit superconducting quantum chip is called?',
    answer: 'Kaveri (by QpiAI, Nov 2025)',
    explanation: 'QpiAI first launched 25-qubit Indus computer (Apr 2025), then 64-qubit Kaveri chip (Nov 2025). NQM target: 1,000-qubit by 2031. Commercial availability targeted late 2026.',
    context: 'Current Affairs Nov 2025', examProb: 'Hot',
    mnemonic: 'Kaveri = 64-qubit chip flowing from QpiAI',
  },
  {
    id: 131, subject: 'Technology', topic: 'Quantum Computing',
    question: 'India\'s first quantum technology park \'Quantum Valley\' is located in which city?',
    answer: 'Amaravati, Andhra Pradesh (established May 2025, opened Jan 2026)',
    explanation: 'Construction by L&T. Part of India\'s National Quantum Mission ecosystem. India\'s full-stack quantum computer Indus (25-qubit) by QpiAI also backed by NQM.',
    context: 'Current Affairs 2025–26', examProb: 'High',
    mnemonic: 'Quantum Valley = Amaravati\'s tech future',
  },
  {
    id: 132, subject: 'Technology', topic: 'Semiconductor',
    question: 'Micron Technology ATMP plant inaugurated in Feb 2026 is located in which Indian city?',
    answer: 'Sanand, Gujarat',
    explanation: 'Inaugurated 28 Feb 2026 by PM Modi. Kaynes OSAT also at Sanand (31 Mar 2026). CG Power OSAT at Sanand (Aug 2025). Tata-PSMC fab at Dholera, Gujarat ($10 billion).',
    context: 'Current Affairs Feb 2026', examProb: 'Hot',
    mnemonic: 'Sanand = Silicon Hub of Gujarat (Micron + Kaynes + CG)',
  },
  {
    id: 133, subject: 'Technology', topic: 'Health Tech',
    question: 'Hillchol is an oral vaccine for which disease, completing Phase III trials in May 2025?',
    answer: 'Cholera',
    explanation: 'India produces 60% of global vaccines and has 2nd highest USFDA-approved plants outside US. Gennova developed India\'s first mRNA vaccine (GEMCOVAC-19).',
    context: 'Current Affairs May 2025', examProb: 'High',
    mnemonic: 'HILLchol = kills CHOLera orally',
  },
  {
    id: 134, subject: 'Technology', topic: 'Health Tech',
    question: 'Biopharma Shakti initiative (Budget 2026) has what budget and focus?',
    answer: '₹10,000 crore over 5 years for biologics, biosimilars, gene therapies',
    explanation: 'India\'s biotech industry valued at over $100 billion. 3rd largest in Asia, top 12 globally. Bharat Biotech launched Nucelion Therapeutics (Nov 2025) for cell and gene therapy.',
    context: 'Current Affairs Budget 2026', examProb: 'Hot',
    mnemonic: 'Biopharma Shakti = 10K crore power for bio sector',
  },
  {
    id: 135, subject: 'Technology', topic: 'Nuclear Energy',
    question: 'Rajasthan Atomic Power Station Unit 7 (700 MW) was commissioned in which month?',
    answer: 'April 2025',
    explanation: 'India has 25 reactors (8,880 MW total), 11 more under construction (8,700 MW). Nuclear = ~3% of total power. Mahi Banswara plant foundation laid 25 Sep 2025 by PM Modi.',
    context: 'Current Affairs Apr 2025', examProb: 'High',
    mnemonic: 'Rajasthan 7 = 700 MW nuclear in Apr 2025',
  },
  {
    id: 136, subject: 'Space & Defense', topic: 'Defense',
    question: 'MRSAM (Medium Range Surface-to-Air Missile) had how many successful test launches in Apr 2025?',
    answer: 'Four successful launches (by DRDO and Indian Army)',
    explanation: 'MRSAM is jointly developed by DRDO and Israel\'s IAI. Used for air defense against aircraft, helicopters, anti-ship missiles, and UAVs.',
    context: 'Current Affairs Apr 2025', examProb: 'High',
    mnemonic: 'MRSAM = 4 hits in April = Medium Range Shield',
  },
]

export const sciPyqHistory: SciPYQEntry[] = [
  { date: '12 Sep 2024', shift: 'Shift 1', question: 'Path of javelin thrown at angle is called?', answer: 'Curvilinear motion', subject: 'Physics' },
  { date: '23 Sep 2024', shift: 'Shift 1', question: "Diffraction of light proves light's ___ nature?", answer: 'Wave nature', subject: 'Physics' },
  { date: '10 Sep 2024', shift: 'Shift 3', question: 'Which organelle produces H₂O₂?', answer: 'Peroxisomes', subject: 'Biology' },
  { date: '09 Sep 2024', shift: 'Shift 1', question: 'IUPAC name 2-Methylpropan-2-ol refers to?', answer: 'Tert-butanol', subject: 'Chemistry' },
  { date: '17 Jul 2023', shift: 'Shift 1', question: 'Which metal has highest electrical resistivity?', answer: 'Nichrome', subject: 'Physics' },
  { date: '2024 GA',     shift: 'Various', question: 'Eka-aluminium was identified as which element?', answer: 'Gallium', subject: 'Chemistry' },
  { date: '2024 GA',     shift: 'Various', question: 'Molecular formula of Butane?', answer: 'C₄H₁₀', subject: 'Chemistry' },
  { date: 'Aug 2023',    shift: 'Current', question: "Chandrayaan-3 first landing at Moon's?", answer: 'South Pole', subject: 'Space & Defense' },
  { date: 'Jan 2024',    shift: 'Current', question: 'Aditya-L1 reached which Lagrangian point?', answer: 'L1 point', subject: 'Space & Defense' },
  { date: 'Dec 2024',    shift: 'Current', question: 'SpaDeX makes India ___ nation for space docking?', answer: '4th nation', subject: 'Space & Defense' },
  { date: 'Apr 2025',    shift: 'Current', question: 'Rafale-M jets deal signed with which country?', answer: 'France', subject: 'Space & Defense' },
  { date: 'May 2025',    shift: 'Current', question: 'Operation Sindoor targeted which region?', answer: 'Pakistan & PoK terror camps', subject: 'Space & Defense' },
  { date: 'Jul 2025',    shift: 'Current', question: 'NISAR satellite is a joint mission of?', answer: 'NASA and ISRO', subject: 'Space & Defense' },
  { date: 'Mar 2024',    shift: 'Current', question: 'Agni-5 MIRV test was codenamed?', answer: 'Mission Divyastra', subject: 'Space & Defense' },
  { date: 'Jan 2025',    shift: 'Current', question: 'India crossed 100 GW of which energy capacity?', answer: 'Solar energy', subject: 'Technology' },
  { date: 'Dec 2025',    shift: 'Current', question: 'SHANTI Act relates to which sector?', answer: 'Nuclear energy (private participation)', subject: 'Technology' },
  { date: 'Oct 2025',    shift: 'Current', question: 'Nobel Chemistry 2025 awarded for?', answer: 'Metal-Organic Frameworks (MOFs)', subject: 'Technology' },
  { date: 'Oct 2025',    shift: 'Current', question: 'Nobel Peace Prize 2025 winner?', answer: 'Maria Corina Machado (Venezuela)', subject: 'Technology' },
  { date: 'Apr 2026',    shift: 'Current', question: 'Artemis II is first crewed flight beyond LEO since?', answer: 'Apollo 17 (1972)', subject: 'Space & Defense' },
  { date: 'Mar 2026',    shift: 'Current', question: 'Which country signed BrahMos deal with India in 2026?', answer: 'Indonesia', subject: 'Space & Defense' },
  { date: '2025',        shift: 'Current', question: 'India\'s rank in Global Innovation Index 2025?', answer: '38th', subject: 'Technology' },
  { date: '2025',        shift: 'Current', question: 'IndiaAI Mission budget and GPU count?', answer: 'Rs 10,371 crore, 38,000 GPUs', subject: 'Technology' },
  { date: '2025',        shift: 'Current', question: 'India\'s first indigenous 64-bit processor?', answer: 'DHRUV64 (C-DAC, RISC-V)', subject: 'Technology' },
  { date: 'Aug 2024',    shift: 'Current', question: 'INS Arighaat is India\'s ___ SSBN?', answer: '2nd nuclear submarine', subject: 'Space & Defense' },
  { date: 'Q1 2026',     shift: 'Current', question: 'Tejas Mk 2 first flight — generation?', answer: '4.5-generation fighter', subject: 'Space & Defense' },
  { date: 'Jan 2026',    shift: 'Current', question: 'LR-AShM hypersonic missile top speed?', answer: 'Mach 10', subject: 'Space & Defense' },
  { date: 'Nov 2025',    shift: 'Current', question: 'India\'s first 64-qubit quantum chip?', answer: 'Kaveri (QpiAI)', subject: 'Technology' },
  { date: 'Feb 2026',    shift: 'Current', question: 'Micron ATMP plant inaugurated at?', answer: 'Sanand, Gujarat', subject: 'Technology' },
  { date: 'Budget 2026', shift: 'Current', question: 'Biopharma Shakti budget over 5 years?', answer: '₹10,000 crore', subject: 'Technology' },
  { date: 'Apr 2025',    shift: 'Current', question: 'Rajasthan Unit 7 nuclear reactor capacity?', answer: '700 MW', subject: 'Technology' },
  { date: '2025',        shift: 'Current', question: 'ISS planned retirement year?', answer: 'January 2031', subject: 'Space & Defense' },
]
