export type Subject = 'Physics' | 'Chemistry' | 'Biology' | 'Space & Defense' | 'Technology'
export type ExamProb = 'Hot' | 'High' | 'Confirmed' | 'Recurring'

export interface SciEntry {
  id: number
  subject: Subject
  topic: string
  question: string
  answer: string
  explanation: string
  context: string
  examProb: ExamProb
  mnemonic?: string
}

export interface SciPYQEntry {
  date: string
  shift: string
  question: string
  answer: string
  subject: Subject
}

export const sciData: SciEntry[] = [
  // ── PHYSICS ──────────────────────────────────────────────────────────────
  {
    id: 1, subject: 'Physics', topic: 'Laws of Motion',
    question: 'The path followed by a javelin thrown at an angle is called?',
    answer: 'Curvilinear motion (Projectile)',
    explanation: 'A javelin follows a parabolic/curvilinear path under gravity after launch.',
    context: 'SSC CGL 12 Sep 2024 Shift 1', examProb: 'Confirmed',
    mnemonic: 'Javelin = Curved beauty in the sky',
  },
  {
    id: 2, subject: 'Physics', topic: 'Optics',
    question: 'Which phenomenon is responsible for the working of optical fibres?',
    answer: 'Total Internal Reflection (TIR)',
    explanation: 'Light travels through fibre by continuously reflecting off inner walls when angle exceeds critical angle.',
    context: 'SSC CGL 2022 Tier 1', examProb: 'Hot',
    mnemonic: 'TIR = Totally Inside Reflecting',
  },
  {
    id: 3, subject: 'Physics', topic: 'Optics',
    question: 'Diffraction of light proves that light has what nature?',
    answer: 'Wave nature',
    explanation: 'Diffraction is the bending of waves around obstacles — only waves diffract, not particles.',
    context: 'SSC CGL 23 Sep 2024 Shift 1', examProb: 'Confirmed',
    mnemonic: 'Diffraction → Deviation → Wave',
  },
  {
    id: 4, subject: 'Physics', topic: 'Electricity',
    question: 'Which metal has the highest electrical resistivity and is used in heating elements?',
    answer: 'Nichrome',
    explanation: 'Nichrome (Ni-Cr alloy) has very high resistivity (~100×10⁻⁸ Ωm) and high melting point — ideal for heaters.',
    context: 'SSC CGL 17 Jul 2023 Shift 1', examProb: 'Confirmed',
    mnemonic: 'Nichrome = Nickel + Chrome = HIGH resistance',
  },
  {
    id: 5, subject: 'Physics', topic: 'Electricity',
    question: 'What does a sphygmomanometer measure?',
    answer: 'Blood pressure',
    explanation: 'Sphygmomanometer measures arterial blood pressure using an inflatable cuff.',
    context: 'SSC CGL 2023 GA section', examProb: 'Hot',
    mnemonic: 'Sphygmo = pulse pressure measure',
  },
  {
    id: 6, subject: 'Physics', topic: 'Sound',
    question: 'The speed of sound is maximum in which medium?',
    answer: 'Solids',
    explanation: 'Sound needs a medium and travels fastest in solids due to tightly packed particles (e.g., iron: ~5100 m/s).',
    context: 'SSC CGL standard PYQ', examProb: 'High',
    mnemonic: 'Solid > Liquid > Gas for sound speed',
  },
  {
    id: 7, subject: 'Physics', topic: 'Thermodynamics',
    question: 'Which law of thermodynamics defines the concept of temperature?',
    answer: 'Zeroth Law',
    explanation: 'Zeroth Law: if A is in thermal equilibrium with B, and B with C, then A is with C — defines temperature.',
    context: 'SSC CGL 2022–23', examProb: 'High',
    mnemonic: 'Zeroth = Zero start = Temperature concept',
  },
  {
    id: 8, subject: 'Physics', topic: 'Optics',
    question: 'Which mirror is used as a rear-view mirror in vehicles?',
    answer: 'Convex mirror',
    explanation: 'Convex mirrors always form virtual, diminished, erect images — wider field of view for rear-view mirrors.',
    context: 'SSC CGL standard PYQ', examProb: 'High',
    mnemonic: 'Convex = Cars use it to see behind WIDE',
  },
  {
    id: 9, subject: 'Physics', topic: 'Nuclear Physics',
    question: 'Which particle has no charge and negligible mass, emitted during beta decay?',
    answer: 'Neutrino (antineutrino)',
    explanation: 'In beta-minus decay: n → p + e⁻ + antineutrino. Neutrinos interact very weakly with matter.',
    context: 'SSC CGL 2024 GA', examProb: 'High',
    mnemonic: 'Neutrino = neutral ghost particle',
  },
  {
    id: 10, subject: 'Physics', topic: 'Magnetism',
    question: 'The SI unit of magnetic field strength (flux density) is?',
    answer: 'Tesla (T)',
    explanation: '1 Tesla = 1 Weber per square meter. Named after Nikola Tesla.',
    context: 'SSC CGL 2023 GA', examProb: 'High',
    mnemonic: 'Tesla the car = magnetic power',
  },
  {
    id: 11, subject: 'Physics', topic: 'Laws of Motion',
    question: "Newton's second law of motion gives the definition of which quantity?",
    answer: 'Force (F = ma)',
    explanation: 'F = ma — the rate of change of momentum equals the applied force. Defines force quantitatively.',
    context: 'SSC CGL standard PYQ', examProb: 'Recurring',
    mnemonic: 'Second law = Second thing after identifying motion = FORCE',
  },
  {
    id: 12, subject: 'Physics', topic: 'Optics',
    question: 'Which lens is used to correct myopia (short-sightedness)?',
    answer: 'Concave lens',
    explanation: 'Concave (diverging) lens diverges incoming light, shifting the focus back onto the retina.',
    context: 'SSC CGL Tier 1 2022', examProb: 'Recurring',
    mnemonic: 'Myopia → Minus lens → Concave',
  },
  {
    id: 13, subject: 'Physics', topic: 'Work & Energy',
    question: 'The unit of power in the SI system is?',
    answer: 'Watt (W)',
    explanation: '1 Watt = 1 Joule per second. Power = Work / Time.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Watt did you power today?',
  },
  {
    id: 14, subject: 'Physics', topic: 'Gravitation',
    question: "The value of acceleration due to gravity (g) at the centre of the Earth is?",
    answer: 'Zero',
    explanation: "At Earth's centre, gravitational pull from all directions cancels out → g = 0.",
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'Centre = surrounded equally = zero pull',
  },
  {
    id: 15, subject: 'Physics', topic: 'Electricity',
    question: "Transformers work on which principle?",
    answer: "Mutual induction (Faraday's electromagnetic induction)",
    explanation: 'A changing current in primary coil induces EMF in secondary coil via changing magnetic flux.',
    context: 'SSC CGL 2022–24', examProb: 'High',
    mnemonic: 'Transformer = Transfer energy via mutual induction',
  },
  {
    id: 16, subject: 'Physics', topic: 'Waves',
    question: 'Ultrasonics are used in SONAR for what purpose?',
    answer: 'Detection of underwater objects / depth measurement',
    explanation: 'SONAR = Sound Navigation And Ranging. Uses ultrasonic waves reflected from objects to determine distance.',
    context: 'SSC CGL 2023 Tier 1', examProb: 'High',
    mnemonic: 'SONAR = underwater RADAR using sound',
  },
  {
    id: 17, subject: 'Physics', topic: 'Modern Physics',
    question: 'Laser works on the principle of?',
    answer: 'Stimulated emission of radiation',
    explanation: 'LASER = Light Amplification by Stimulated Emission of Radiation. Photons trigger coherent photon emission.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'L-A-S-E-R spells the principle',
  },
  {
    id: 18, subject: 'Physics', topic: 'Thermodynamics',
    question: 'Which scale of temperature is based on the properties of an ideal gas?',
    answer: 'Kelvin (absolute) scale',
    explanation: 'Kelvin starts at absolute zero (−273.15°C) where all molecular motion stops.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: 'Kelvin = King of temperature scales',
  },

  // ── CHEMISTRY ────────────────────────────────────────────────────────────
  {
    id: 19, subject: 'Chemistry', topic: 'Periodic Table',
    question: 'Mendeleev predicted the existence of germanium calling it what?',
    answer: 'Eka-silicon',
    explanation: 'Mendeleev left gaps in his periodic table and predicted properties of missing elements. Gallium=eka-aluminium, Germanium=eka-silicon.',
    context: 'SSC CGL 2024 GA', examProb: 'Confirmed',
    mnemonic: 'Eka = one below (Sanskrit). Eka-silicon sits below Silicon.',
  },
  {
    id: 20, subject: 'Chemistry', topic: 'Periodic Table',
    question: 'Mendeleev called the undiscovered element below aluminium — what was it found to be?',
    answer: 'Gallium (predicted as Eka-aluminium)',
    explanation: "Mendeleev's eka-aluminium was discovered in 1875 as Gallium — matching his predicted properties almost exactly.",
    context: 'SSC CGL 2024 Confirmed PYQ', examProb: 'Confirmed',
    mnemonic: 'Gal(lium) fills the Aluminium gap',
  },
  {
    id: 21, subject: 'Chemistry', topic: 'Organic Chemistry',
    question: 'What is the molecular formula of Butane?',
    answer: 'C₄H₁₀',
    explanation: 'Butane (n-butane or isobutane) is an alkane with formula CₙH₂ₙ₊₂ → C₄H₁₀.',
    context: 'SSC CGL 2024 GA', examProb: 'Confirmed',
    mnemonic: 'But(4)ane: 4 carbons, 10 hydrogens',
  },
  {
    id: 22, subject: 'Chemistry', topic: 'Organic Chemistry',
    question: 'IUPAC name of 2-Methylpropan-2-ol is the systematic name for which common compound?',
    answer: 'Tert-butanol (t-BuOH)',
    explanation: '2-methylpropan-2-ol has OH on the central carbon of isobutane — tertiary butyl alcohol.',
    context: 'SSC CGL 09 Sep 2024 Shift 1', examProb: 'Confirmed',
    mnemonic: '2-Methyl, 2-position = 2nd carbon gets the OH and methyl branch',
  },
  {
    id: 23, subject: 'Chemistry', topic: 'States of Matter',
    question: 'Italian researchers reported "Supersolid Light" in 2024 — what state does it represent?',
    answer: 'Fourth state of light / supersolid phase of polaritons',
    explanation: 'Italian researchers created a supersolid phase using polaritons (light-matter quasi-particles) — rigid structure yet flows like superfluid.',
    context: 'Current Affairs 2024', examProb: 'High',
    mnemonic: 'Supersolid = solid structure + superfluid flow',
  },
  {
    id: 24, subject: 'Chemistry', topic: 'Acids & Bases',
    question: 'Which acid is present in vinegar?',
    answer: 'Acetic acid (CH₃COOH)',
    explanation: 'Vinegar is 5–8% acetic acid solution. Ethanoic acid by IUPAC name.',
    context: 'SSC CGL standard Recurring', examProb: 'Recurring',
    mnemonic: 'VINegar = ethanVINic = acetic acid',
  },
  {
    id: 25, subject: 'Chemistry', topic: 'Metals',
    question: 'Which metal is the best conductor of electricity?',
    answer: 'Silver (Ag)',
    explanation: 'Silver has the highest electrical conductivity of all metals at room temperature. Copper is second.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Silver = #1 conductor, Copper = #2',
  },
  {
    id: 26, subject: 'Chemistry', topic: 'Metals',
    question: 'What is the chemical name of "Baking Soda"?',
    answer: 'Sodium bicarbonate (NaHCO₃)',
    explanation: 'NaHCO₃ releases CO₂ when heated — used as leavening agent in baking.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'Baking Soda = Bi-carb of Soda = NaHCO₃',
  },
  {
    id: 27, subject: 'Chemistry', topic: 'Chemical Reactions',
    question: 'What gas is produced when acids react with metal carbonates?',
    answer: 'Carbon dioxide (CO₂)',
    explanation: 'Acid + Metal carbonate → Salt + Water + CO₂. This turns lime water milky.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: 'Carbonate + Acid = CO₂ bubbles',
  },
  {
    id: 28, subject: 'Chemistry', topic: 'Polymers',
    question: 'What is the monomer of natural rubber?',
    answer: 'Isoprene (2-methylbuta-1,3-diene)',
    explanation: 'Natural rubber is a polymer of isoprene units. Vulcanisation adds sulphur cross-links to make it durable.',
    context: 'SSC CGL 2023 GA', examProb: 'High',
    mnemonic: 'ISOprene = rubber ISO standard monomer',
  },
  {
    id: 29, subject: 'Chemistry', topic: 'Environmental Chemistry',
    question: 'Which gas is mainly responsible for the greenhouse effect?',
    answer: 'Carbon dioxide (CO₂) — also methane CH₄',
    explanation: 'CO₂ from burning fossil fuels traps IR radiation. CH₄ is 25x more potent but less abundant.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'CO₂ = Chief greenhouse criminal',
  },
  {
    id: 30, subject: 'Chemistry', topic: 'Periodic Table',
    question: 'The element with highest electronegativity is?',
    answer: 'Fluorine (F)',
    explanation: 'Fluorine (F) has electronegativity 4.0 on Pauling scale — highest of all elements.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: 'F = First to grab electrons = most electronegative',
  },
  {
    id: 31, subject: 'Chemistry', topic: 'Nuclear Chemistry',
    question: 'Heavy water (D₂O) is used in nuclear reactors as what?',
    answer: 'Moderator (slows down neutrons)',
    explanation: 'D₂O slows fast neutrons to thermal energy for sustained fission without absorbing them like light water.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'Heavy water = slows (moderates) fast neutrons',
  },
  {
    id: 32, subject: 'Chemistry', topic: 'Organic Chemistry',
    question: 'What is the common name for ethanol?',
    answer: 'Alcohol / Grain alcohol / Drinking alcohol',
    explanation: 'C₂H₅OH is ethyl alcohol — produced by fermentation of sugars. IUPAC: ethanol.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Ethanol = the social molecule',
  },
  {
    id: 33, subject: 'Chemistry', topic: 'Chemical Bonding',
    question: 'Diamond and graphite are both made of carbon — they are examples of what?',
    answer: 'Allotropes of carbon',
    explanation: 'Allotropes are different structural forms of the same element. Diamond (tetrahedral, hard) vs graphite (layered, soft).',
    context: 'SSC CGL standard Recurring', examProb: 'Recurring',
    mnemonic: 'Allotropes = ALL same atom, different ROPE/structure',
  },
  {
    id: 34, subject: 'Chemistry', topic: 'Acids & Bases',
    question: 'Which indicator turns red in acid and blue in base?',
    answer: 'Litmus',
    explanation: 'Natural litmus from lichen turns red in acid (pH<7) and blue in base (pH>7). Neutral = purple.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Litmus test = Red Acid, Blue Base',
  },
  {
    id: 35, subject: 'Chemistry', topic: 'Metals',
    question: 'Stainless steel is an alloy of iron with which metals?',
    answer: 'Chromium and Nickel (Fe + Cr + Ni)',
    explanation: 'Stainless steel: ~10.5% Cr prevents oxidation; Ni adds toughness. The passive Cr₂O₃ layer prevents rust.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'Stainless = Stays Shiny = Cr (Chrome) protection',
  },
  {
    id: 36, subject: 'Chemistry', topic: 'Organic Chemistry',
    question: 'Which gas is produced when chlorine reacts with slaked lime? (used as bleaching powder)',
    answer: 'Bleaching powder = Ca(OCl)Cl / Calcium hypochlorite',
    explanation: 'Cl₂ + Ca(OH)₂ → CaOCl₂ + H₂O. Bleaching powder releases Cl₂ when with dilute acid — the active bleaching agent.',
    context: 'SSC CGL 2024', examProb: 'High',
    mnemonic: 'Bleaching powder = Chlorine locked in calcium',
  },

  // ── BIOLOGY ───────────────────────────────────────────────────────────────
  {
    id: 37, subject: 'Biology', topic: 'Cell Biology',
    question: 'Which organelle produces H₂O₂ during fatty acid oxidation?',
    answer: 'Peroxisomes',
    explanation: 'Peroxisomes contain enzymes like catalase that generate and then break down H₂O₂ — protecting the cell.',
    context: 'SSC CGL 10 Sep 2024 Shift 3', examProb: 'Confirmed',
    mnemonic: 'Peroxisome = H₂O₂ generator + destroyer',
  },
  {
    id: 38, subject: 'Biology', topic: 'Cell Biology',
    question: 'Ribosomes are present in which types of cells?',
    answer: 'Both prokaryotic and eukaryotic cells',
    explanation: 'All living cells need ribosomes for protein synthesis. Prokaryotes have 70S; eukaryotes have 80S ribosomes.',
    context: 'SSC CGL 2023–24', examProb: 'High',
    mnemonic: 'Ribosome = Ribs of ALL cells',
  },
  {
    id: 39, subject: 'Biology', topic: 'Cell Biology',
    question: 'Which cell organelle is called the "powerhouse of the cell"?',
    answer: 'Mitochondria',
    explanation: 'Mitochondria produce ATP through cellular respiration (Krebs cycle + oxidative phosphorylation).',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'Mito = Mighty powerhouse',
  },
  {
    id: 40, subject: 'Biology', topic: 'Genetics',
    question: 'Watson and Crick proposed the double helix model of DNA in which year?',
    answer: '1953',
    explanation: 'Published in Nature, April 1953. Used X-ray crystallography data from Rosalind Franklin.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: '1953 = DNA double helix birthday',
  },
  {
    id: 41, subject: 'Biology', topic: 'Human Body',
    question: 'Aquaporins are channel proteins that facilitate the transport of what?',
    answer: 'Water (across cell membranes)',
    explanation: 'Aquaporins allow rapid water movement across membranes. Nobel Prize in Chemistry 2003 (Peter Agre).',
    context: 'SSC CGL 2024 GA', examProb: 'High',
    mnemonic: 'Aqua = water, Pore = channel = water channel',
  },
  {
    id: 42, subject: 'Biology', topic: 'Disease & Vaccines',
    question: 'AdFalciVax is a vaccine developed for which disease?',
    answer: 'Malaria (Plasmodium falciparum)',
    explanation: 'AdFalciVax uses adenovirus vector to deliver malaria antigens. P. falciparum is the deadliest malaria parasite.',
    context: 'Current Affairs 2024', examProb: 'Hot',
    mnemonic: 'Ad-FALCI-vax = FALCIparum vaccine',
  },
  {
    id: 43, subject: 'Biology', topic: 'Human Body',
    question: 'Which blood group is known as the "universal donor"?',
    answer: 'O negative (O⁻)',
    explanation: 'O⁻ red cells lack ABO antigens and Rh factor — can be given to any patient in emergency.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'O⁻ = Opens to All (universal donor)',
  },
  {
    id: 44, subject: 'Biology', topic: 'Human Body',
    question: 'Which organ produces insulin in the human body?',
    answer: 'Pancreas (beta cells of islets of Langerhans)',
    explanation: 'Insulin lowers blood glucose by promoting cellular uptake. Deficiency causes Type 1 diabetes.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'PancreAs = regulates sugAr with Insulin',
  },
  {
    id: 45, subject: 'Biology', topic: 'Plant Biology',
    question: 'Which process converts light energy into chemical energy in plants?',
    answer: 'Photosynthesis',
    explanation: '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Occurs in chloroplasts using chlorophyll.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Photo = light + Synthesis = building = light building sugar',
  },
  {
    id: 46, subject: 'Biology', topic: 'Human Body',
    question: 'The hardest substance in the human body is?',
    answer: 'Tooth enamel',
    explanation: 'Tooth enamel (96% hydroxyapatite) is rated 5 on Mohs scale — harder than bone.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'Enamel = hardest shell of the body',
  },
  {
    id: 47, subject: 'Biology', topic: 'Genetics',
    question: 'The study of heredity and variation is called?',
    answer: 'Genetics',
    explanation: 'Gregor Mendel is the Father of Genetics. Modern genetics includes molecular genetics and genomics.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'GENetics = GENE study',
  },
  {
    id: 48, subject: 'Biology', topic: 'Disease & Vaccines',
    question: 'Which vitamin deficiency causes Scurvy?',
    answer: 'Vitamin C (Ascorbic acid)',
    explanation: 'Vitamin C is needed for collagen synthesis. Deficiency → bleeding gums, weakened immune system.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'sCurvy = no C vitamin',
  },
  {
    id: 49, subject: 'Biology', topic: 'Disease & Vaccines',
    question: 'Malaria is caused by which parasite and transmitted by which mosquito?',
    answer: 'Plasmodium parasite; female Anopheles mosquito',
    explanation: 'Plasmodium falciparum causes deadliest malaria. Female Anopheles mosquito is the vector.',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'ANOpheles = ANOther malaria carrier',
  },
  {
    id: 50, subject: 'Biology', topic: 'Human Body',
    question: 'Which part of the brain controls balance and coordination?',
    answer: 'Cerebellum',
    explanation: 'Cerebellum (little brain) coordinates voluntary movements, balance and posture.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'CerebelLUM = baLANce UMbrella of the brain',
  },
  {
    id: 51, subject: 'Biology', topic: 'Cell Biology',
    question: 'Which organelle is called the "suicide bag" of the cell?',
    answer: 'Lysosome',
    explanation: 'Lysosomes contain digestive enzymes. When ruptured, they digest the cell itself — hence "suicide bag".',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'LYSOsome = LYSIS (cell death) bag',
  },
  {
    id: 52, subject: 'Biology', topic: 'Plant Biology',
    question: 'The green pigment in plants responsible for photosynthesis is?',
    answer: 'Chlorophyll',
    explanation: 'Chlorophyll a and b absorb red and blue light, reflecting green — hence plants look green.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'Chloro = green, phyll = leaf pigment',
  },
  {
    id: 53, subject: 'Biology', topic: 'Human Body',
    question: 'Which gland is known as the "master gland"?',
    answer: 'Pituitary gland',
    explanation: 'Pituitary secretes hormones that control other endocrine glands (thyroid, adrenal, gonads).',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
    mnemonic: 'Pituitary = Pilot (master) of hormone HQ',
  },
  {
    id: 54, subject: 'Biology', topic: 'Human Body',
    question: 'The largest gland in the human body is?',
    answer: 'Liver',
    explanation: 'Liver (1.5 kg) performs 500+ functions: bile production, detoxification, glycogen storage.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: 'LIVER = LargestInternal organ & Vital Engine of Reactions',
  },
  {
    id: 55, subject: 'Biology', topic: 'Nutrition',
    question: 'Which vitamin is synthesized in the skin on exposure to sunlight?',
    answer: 'Vitamin D',
    explanation: 'UV-B radiation converts 7-dehydrocholesterol in skin to Vitamin D₃ (cholecalciferol).',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'D = Day (sunlight) vitamin',
  },
  {
    id: 56, subject: 'Biology', topic: 'Disease & Vaccines',
    question: 'AIDS is caused by which virus?',
    answer: 'HIV (Human Immunodeficiency Virus)',
    explanation: 'HIV attacks CD4+ T-cells (helper T-cells), destroying the immune system. No cure, but ART controls it.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'HIV = Hunts Immune Vessels',
  },
  {
    id: 57, subject: 'Biology', topic: 'Cell Biology',
    question: 'Cell wall of fungi is made up of?',
    answer: 'Chitin',
    explanation: 'Fungi cell wall = chitin (N-acetyl glucosamine polymer). Plants = cellulose; bacteria = peptidoglycan.',
    context: 'SSC CGL 2023–24', examProb: 'High',
    mnemonic: 'Chitin = CHItinous fungi coat',
  },
  {
    id: 58, subject: 'Biology', topic: 'Genetics',
    question: 'Which nitrogenous base pairs with Adenine in DNA?',
    answer: 'Thymine (A-T pair; 2 hydrogen bonds)',
    explanation: "Chargaff's rules: A=T (2 H-bonds), G≡C (3 H-bonds). In RNA, Uracil replaces Thymine (A-U pair).",
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'AT(e) a GC cookie = A-T, G-C pairs',
  },
  {
    id: 59, subject: 'Biology', topic: 'Human Body',
    question: 'The normal RBC count in adult males (per mm³) is approximately?',
    answer: '5 million per mm³ (4.7–6.1 million)',
    explanation: 'RBCs carry haemoglobin for oxygen transport. Low count = anaemia.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: '5 million RBCs = keep you alive and kicking',
  },
  {
    id: 60, subject: 'Biology', topic: 'Human Body',
    question: 'Which is the longest bone in the human body?',
    answer: 'Femur (thigh bone)',
    explanation: 'Femur (thigh bone) is about 25% of total body height and the strongest bone.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: 'FEmur = FEmale dancers have long thighs',
  },
  {
    id: 61, subject: 'Biology', topic: 'Human Body',
    question: 'The smallest bone in the human body is located where?',
    answer: 'Stapes — in the middle ear',
    explanation: 'Stapes (stirrup bone) is ~3mm long. The three ear ossicles are malleus, incus, stapes.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: 'Stapes = Smallest stirrup in the ear',
  },

  // ── SPACE & DEFENSE ───────────────────────────────────────────────────────
  {
    id: 62, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: "India's SpaDeX mission makes India the __ nation to demonstrate space docking.",
    answer: '4th nation (after USA, Russia, China)',
    explanation: 'Space Docking Experiment (SpaDeX) launched Dec 2024. Two spacecraft (SDX01 & SDX02) demonstrated autonomous docking.',
    context: 'Current Affairs Dec 2024', examProb: 'Hot',
    mnemonic: "SpaDeX = Space Docking eXperiment = 4th club",
  },
  {
    id: 63, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: 'Aditya-L1 is positioned at which Lagrangian point?',
    answer: 'L1 (Sun-Earth L1 point, ~1.5 million km from Earth)',
    explanation: 'L1 gives unobstructed continuous view of the Sun. Aditya-L1 studies solar corona, solar wind, CMEs.',
    context: 'Current Affairs Jan 2024', examProb: 'Hot',
    mnemonic: 'Aditya = Sun; L1 = closest stable point toward Sun',
  },
  {
    id: 64, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: 'Chandrayaan-3 achieved what historic first on August 23, 2023?',
    answer: "First ever soft landing at the Moon's South Pole",
    explanation: 'Vikram lander and Pragyan rover operated for ~14 Earth days. India = 4th nation to soft-land on Moon.',
    context: 'SSC CGL 2024 / Current Affairs Aug 2023', examProb: 'Hot',
    mnemonic: 'Chandrayaan-3 = CHANDRA (Moon) landing at SOUTH pole',
  },
  {
    id: 65, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: 'NISAR satellite is a joint mission between ISRO and which foreign space agency?',
    answer: 'NASA (USA) — dual-frequency SAR satellite',
    explanation: 'NISAR = NASA-ISRO SAR. Uses L-band (NASA) and S-band (ISRO) radar. Will launch in 2025.',
    context: 'Current Affairs 2024–25', examProb: 'Hot',
    mnemonic: 'NISAR = N(ASA)+ISAR = dual-band Earth observer',
  },
  {
    id: 66, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: 'Proba-3 satellite was launched by ISRO using which rocket?',
    answer: 'PSLV-C59',
    explanation: 'Proba-3 (ESA mission) launched Dec 2024 via PSLV-C59 from Sriharikota. Studies solar corona.',
    context: 'Current Affairs Dec 2024', examProb: 'High',
    mnemonic: 'Proba = Probe-3 = ESA via PSLV',
  },
  {
    id: 67, subject: 'Space & Defense', topic: 'Human Spaceflight',
    question: 'Who will be the 2nd Indian to travel to the ISS as part of Axiom Mission 4?',
    answer: 'Group Captain Shubhanshu Shukla (IAF)',
    explanation: "Shubhanshu Shukla is the ISS mission specialist for Axiom Mission 4 (planned 2025). Rakesh Sharma was the 1st Indian in space (1984).",
    context: 'Current Affairs 2024–25', examProb: 'Hot',
    mnemonic: "Shukla = Shining hope for India's ISS mission",
  },
  {
    id: 68, subject: 'Space & Defense', topic: 'Defense',
    question: 'India signed a deal to purchase 26 Rafale-M jets from which country?',
    answer: 'France',
    explanation: "Signed April 2025. Rafale-M (Marine version) for Indian Navy's INS Vikrant aircraft carrier. Dassault Aviation.",
    context: 'Current Affairs 2025', examProb: 'Hot',
    mnemonic: 'Rafale = French fighter jet for Indian Navy',
  },
  {
    id: 69, subject: 'Space & Defense', topic: 'Defense',
    question: "India's deep-sea submersible MATSYA 6000 can dive to what depth?",
    answer: '6000 metres (6 km)',
    explanation: "MATSYA 6000 part of Samudrayaan mission — India's first crewed deep-sea mission for mineral exploration.",
    context: 'Current Affairs 2024', examProb: 'Hot',
    mnemonic: 'MATSYA 6000 = Fish (matsya) that dives 6 km deep',
  },
  {
    id: 70, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: "India's first satellite Aryabhata was launched in which year?",
    answer: '1975',
    explanation: 'Aryabhata (19 April 1975) was launched by the Soviet Kosmos-3M rocket from Kapustin Yar. Named after the ancient mathematician.',
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: "Aryabhata 1975 = India's first step to space",
  },
  {
    id: 71, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: 'MOM (Mangalyaan) made India the __ nation to reach Mars and the first to succeed in its first attempt.',
    answer: '4th nation (and first to succeed on maiden attempt)',
    explanation: 'Mars Orbiter Mission launched Nov 2013, entered Mars orbit Sep 2014. Cost only ₹450 crore.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'MOM = Mars On Mission, 1st attempt success',
  },
  {
    id: 72, subject: 'Space & Defense', topic: 'Defense',
    question: 'Operation Sindoor was carried out by India in May 2025 targeting what?',
    answer: 'Terror camps in Pakistan and Pakistan-occupied Kashmir (PoK)',
    explanation: 'Operation Sindoor (May 7, 2025) was a precision military strike by Indian Armed Forces targeting 9 terror infrastructure sites.',
    context: 'Current Affairs May 2025', examProb: 'Hot',
    mnemonic: 'Sindoor = Precision strike on terror infrastructure',
  },
  {
    id: 73, subject: 'Space & Defense', topic: 'Defense',
    question: 'BrahMos is a supersonic cruise missile jointly developed by India and which country?',
    answer: 'Russia (BRAHmaputra + MOScva river names)',
    explanation: 'BrahMos = BRAHMOS Aerospace. Speed ~2.8 Mach, range 290–800 km. Air, Land, Sea-launched variants.',
    context: 'SSC CGL 2022–23', examProb: 'High',
    mnemonic: 'BrahMos = BRAHmaputra + MOScva = Indo-Russian missile',
  },
  {
    id: 74, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: "Gaganyaan is India's first human spaceflight mission — which organisation is implementing it?",
    answer: 'ISRO (Indian Space Research Organisation)',
    explanation: 'Gaganyaan aims to send 3 Indian astronauts (Gagannauts) to 400 km orbit for 3 days. Uncrewed test flights first.',
    context: 'Current Affairs 2024–25', examProb: 'Hot',
    mnemonic: "Gagan = sky, Yaan = vehicle = India's sky vehicle",
  },
  {
    id: 75, subject: 'Space & Defense', topic: 'ISRO Missions',
    question: "Which ISRO mission studies the Sun's corona and was India's first solar observatory?",
    answer: 'Aditya-L1',
    explanation: 'Launched Sep 2023, reached L1 Jan 2024. Payloads include VELC (corona study), SUIT (UV imaging).',
    context: 'SSC CGL 2024', examProb: 'Hot',
    mnemonic: "Aditya = Sun god = India's Sun watcher at L1",
  },

  // ── TECHNOLOGY ────────────────────────────────────────────────────────────
  {
    id: 76, subject: 'Technology', topic: 'AI & Computing',
    question: "BharatGen is India's first multimodal generative AI — developed by which institution?",
    answer: 'IIT Bombay (funded by MeitY)',
    explanation: "BharatGen supports Indic languages and multimodal inputs (text + image). Part of India's National AI Mission.",
    context: 'Current Affairs 2024', examProb: 'Hot',
    mnemonic: "BharatGen = Bharat's own generative AI from IIT-B",
  },
  {
    id: 77, subject: 'Technology', topic: 'Internet & Networks',
    question: 'What does "5G" stand for in telecommunications?',
    answer: '5th Generation mobile network',
    explanation: '5G offers speeds up to 20 Gbps, ultra-low latency (~1ms). Launched in India Oct 2022.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: '5G = 5th Generation = 10x faster than 4G',
  },
  {
    id: 78, subject: 'Technology', topic: 'Cybersecurity',
    question: 'What is a "Trojan Horse" in computer security?',
    answer: 'Malware disguised as legitimate software',
    explanation: "Like the mythological Trojan horse — appears useful but hides malicious code. Unlike viruses, doesn't self-replicate.",
    context: 'SSC CGL 2023 GA', examProb: 'High',
    mnemonic: 'Trojan = disguised dangerous entry',
  },
  {
    id: 79, subject: 'Technology', topic: 'AI & Computing',
    question: 'The full form of CPU is?',
    answer: 'Central Processing Unit',
    explanation: "CPU = brain of computer. Executes instructions, performs arithmetic/logic. Contains ALU + CU + registers.",
    context: 'SSC CGL standard', examProb: 'Recurring',
    mnemonic: "CPU = Computer's Primary Unit of thinking",
  },
  {
    id: 80, subject: 'Technology', topic: 'Space Tech',
    question: "India's UPI (Unified Payments Interface) is managed by which organisation?",
    answer: 'NPCI (National Payments Corporation of India)',
    explanation: 'UPI launched Apr 2016 by NPCI. Over 14 billion transactions/month by 2024. Uses IMPS infrastructure.',
    context: 'SSC CGL 2023', examProb: 'High',
    mnemonic: "UPI = United by NPCI's Payments Infrastructure",
  },
  {
    id: 81, subject: 'Technology', topic: 'Internet & Networks',
    question: 'WWW was invented by which scientist, in which year?',
    answer: '1989 (proposed) / 1991 (public)',
    explanation: 'Proposed at CERN in 1989. First website went live August 6, 1991. HTML + HTTP + URL.',
    context: 'SSC CGL standard', examProb: 'High',
    mnemonic: "Tim Berners-Lee = The Web's Father, 1989",
  },
  {
    id: 82, subject: 'Technology', topic: 'AI & Computing',
    question: "India's indigenous mobile operating system developed by C-DAC is called?",
    answer: 'BharOS',
    explanation: 'BharOS developed at IIT Madras / JandK Operations. Android-compatible but without Google dependency.',
    context: 'Current Affairs 2023', examProb: 'High',
    mnemonic: "BharOS = Bharat's Own operating System",
  },
  {
    id: 83, subject: 'Technology', topic: 'Internet & Networks',
    question: 'Which protocol is used to send emails?',
    answer: 'SMTP (Simple Mail Transfer Protocol)',
    explanation: 'SMTP (port 25/587) sends emails. POP3/IMAP receive emails. HTTP ≠ email.',
    context: 'SSC CGL 2022', examProb: 'High',
    mnemonic: 'SMTP = Send Mail To Person',
  },
  {
    id: 84, subject: 'Technology', topic: 'Biotechnology',
    question: 'CRISPR-Cas9 is a tool used for what in biotechnology?',
    answer: 'Gene editing (precise DNA modification)',
    explanation: 'CRISPR-Cas9 = molecular scissors that cut DNA at specific sequences. Nobel Prize 2020 (Doudna & Charpentier).',
    context: 'Current Affairs / SSC GA 2024', examProb: 'High',
    mnemonic: 'CRISPR = Cutting Rapidly Into Specific Precise Regions',
  },
  {
    id: 85, subject: 'Technology', topic: 'Space Tech',
    question: "India's first quantum computer was developed by which organization in 2023?",
    answer: 'C-DAC (under National Quantum Mission)',
    explanation: "India's National Quantum Mission (2023) with ₹6003 crore budget. C-DAC working on 50-qubit quantum computer.",
    context: 'Current Affairs 2023–24', examProb: 'High',
    mnemonic: 'Quantum India = C-DAC leads the qubit quest',
  },
]

export const sciPyqHistory: SciPYQEntry[] = [
  { date: '12 Sep 2024', shift: 'Shift 1', question: 'Path of javelin thrown at angle is called?', answer: 'Curvilinear motion', subject: 'Physics' },
  { date: '23 Sep 2024', shift: 'Shift 1', question: "Diffraction of light proves light's ___ nature?", answer: 'Wave nature', subject: 'Physics' },
  { date: '10 Sep 2024', shift: 'Shift 3', question: 'Which organelle produces H₂O₂?', answer: 'Peroxisomes', subject: 'Biology' },
  { date: '09 Sep 2024', shift: 'Shift 1', question: 'IUPAC name 2-Methylpropan-2-ol refers to?', answer: 'Tert-butanol', subject: 'Chemistry' },
  { date: '17 Jul 2023', shift: 'Shift 1', question: 'Which metal has highest electrical resistivity?', answer: 'Nichrome', subject: 'Physics' },
  { date: '2024 GA',     shift: 'Various', question: 'Eka-aluminium was identified as which element?', answer: 'Gallium', subject: 'Chemistry' },
  { date: '2024 GA',     shift: 'Various', question: 'Molecular formula of Butane?', answer: 'C₄H₁₀', subject: 'Chemistry' },
  { date: 'Aug 2023',    shift: 'Current', question: "Chandrayaan-3 first landing at Moon's?", answer: 'South Pole', subject: 'Space & Defense' },
  { date: 'Jan 2024',    shift: 'Current', question: 'Aditya-L1 reached which Lagrangian point?', answer: 'L1 point', subject: 'Space & Defense' },
  { date: 'Dec 2024',    shift: 'Current', question: 'SpaDeX makes India ___ nation for space docking?', answer: '4th nation', subject: 'Space & Defense' },
  { date: 'Apr 2025',    shift: 'Current', question: 'Rafale-M jets deal signed with which country?', answer: 'France', subject: 'Space & Defense' },
  { date: 'May 2025',    shift: 'Current', question: 'Operation Sindoor targeted which region?', answer: 'Pakistan & PoK terror camps', subject: 'Space & Defense' },
]
