import type { EnglishQuestion } from '../src/topics/english/data'

export const batch3: EnglishQuestion[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 1 — SPELLING CORRECTION (40 questions, ids 421–460)
  // ═══════════════════════════════════════════════════════════════════════

  { id: 421, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Accommodation', 'Accomodation', 'Acommodation', 'Acomodation'], answer: 'Accommodation', explanation: 'Accommodation has double "c" and double "m". Remember: 2 Cots and 2 Mattresses.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 422, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Occurence', 'Occurrence', 'Ocurrence', 'Occurrance'], answer: 'Occurrence', explanation: 'Occurrence has double "c" and double "r". The word "occur" doubles the "r" before adding "-ence".', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 423, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Millenium', 'Millennium', 'Milenium', 'Milennium'], answer: 'Millennium', explanation: 'Millennium has double "l" and double "n". Think: "mill" + "ennium" (1000 years).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 424, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Embarass', 'Embarras', 'Embarrass', 'Embarras'], answer: 'Embarrass', explanation: 'Embarrass has double "r" and double "s". Remember: I go Really Red and feel So Silly.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 425, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Commitee', 'Committee', 'Comittee', 'Commitee'], answer: 'Committee', explanation: 'Committee has double "m", double "t", and double "e". Three sets of doubles.', level: 'Easy', tier: 'both', examProb: 'Confirmed' },
  { id: 426, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Neccessary', 'Necessary', 'Necesary', 'Necessery'], answer: 'Necessary', explanation: 'Necessary: 1 Collar and 2 Socks — one "c" and double "s".', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 427, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Seperate', 'Separete', 'Separate', 'Seperete'], answer: 'Separate', explanation: 'Separate has "a" in the middle, not "e". Remember: there is "a rat" in separate.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 428, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Definately', 'Definatly', 'Definitely', 'Definitly'], answer: 'Definitely', explanation: 'Definitely contains "finite" in the middle. De-FINITE-ly.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 429, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Conscience', 'Conscence', 'Consience', 'Concsience'], answer: 'Conscience', explanation: 'Conscience: "con" + "science" — think of "science" inside it.', level: 'Medium', tier: 'both', examProb: 'High' },
  { id: 430, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Privelege', 'Priviledge', 'Privilege', 'Previlege'], answer: 'Privilege', explanation: 'Privilege has no "d" and ends in "-lege", not "-ledge". It is a "privi" + "lege".', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 431, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Maintainance', 'Maintenance', 'Maintenence', 'Maintanance'], answer: 'Maintenance', explanation: 'Maintenance ends in "-enance", not "-ainance". Think: "maintain" drops the second "a" and adds "-enance".', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 432, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Surveilance', 'Surveillance', 'Survaillance', 'Survelance'], answer: 'Surveillance', explanation: 'Surveillance: "sur" + "veill" + "ance". Double "l" and "ei" (not "ai").', level: 'Hard', tier: 'both', examProb: 'High' },
  { id: 433, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Beaurocracy', 'Bureaucracy', 'Bureaucracy', 'Beurocracy'], answer: 'Bureaucracy', explanation: 'Bureaucracy: "bureau" + "cracy". The word "bureau" (desk/office) is the root.', level: 'Hard', tier: 'both', examProb: 'High' },
  { id: 434, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Exagerate', 'Exaggerate', 'Exagerrate', 'Exagarate'], answer: 'Exaggerate', explanation: 'Exaggerate has double "g". Think: it is a really "GG" (great, grand) overstatement.', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 435, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Gaurantee', 'Guarantee', 'Guarentee', 'Garuantee'], answer: 'Guarantee', explanation: 'Guarantee starts with "guar-" (like "guard") and ends with "-antee".', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 436, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Harrassment', 'Harassment', 'Harasment', 'Harasssment'], answer: 'Harassment', explanation: 'Harassment: one "r" and double "s". "Harass" + "ment".', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 437, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Independant', 'Indipendent', 'Independent', 'Indipendant'], answer: 'Independent', explanation: 'Independent ends in "-ent", not "-ant". Think: "I" am "independent" — both have "e".', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 438, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Leiutenant', 'Lieutenant', 'Leutenant', 'Lieutanant'], answer: 'Lieutenant', explanation: 'Lieutenant: "lieu" (French for place) + "tenant" (one who holds). Lieu-tenant.', level: 'Hard', tier: 'both', examProb: 'High' },
  { id: 439, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Miscellaneous', 'Miscelaneous', 'Miscellanious', 'Miscellaineous'], answer: 'Miscellaneous', explanation: 'Miscellaneous: double "l" and "-eous" ending. "Miscell" + "aneous".', level: 'Hard', tier: 'both', examProb: 'High' },
  { id: 440, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Mischevious', 'Mischievous', 'Mischievious', 'Mischevous'], answer: 'Mischievous', explanation: 'Mischievous has only 3 syllables: mis-chie-vous. There is no "i" after the "v".', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 441, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Occassionally', 'Ocasionally', 'Occasionally', 'Occationally'], answer: 'Occasionally', explanation: 'Occasionally: double "c", single "s". From "occasion" + "ally".', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 442, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Parliment', 'Parlement', 'Parliament', 'Parliment'], answer: 'Parliament', explanation: 'Parliament: "parlia" + "ment". The "ia" in the middle is key. Think: "I AM" in parliament.', level: 'Easy', tier: 'both', examProb: 'Confirmed' },
  { id: 443, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Pronounciation', 'Pronunciation', 'Pronuciation', 'Prononciation'], answer: 'Pronunciation', explanation: 'Pronunciation drops the "o" from "pronounce". It is "pronunci-" not "pronounci-".', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 444, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Questionaire', 'Questionnare', 'Questionnaire', 'Questionairre'], answer: 'Questionnaire', explanation: 'Questionnaire: double "n" and ends in "-aire". "Question" + "naire".', level: 'Hard', tier: 'both', examProb: 'High' },
  { id: 445, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Recomend', 'Reccommend', 'Recommend', 'Recommand'], answer: 'Recommend', explanation: 'Recommend: one "c" and double "m". Think: I "recommend" my "mm" (mother & mate).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 446, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Restarant', 'Restaurent', 'Restaurant', 'Restruant'], answer: 'Restaurant', explanation: 'Restaurant: "rest" + "aur" + "ant". The "au" combination is key.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 447, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Rythm', 'Rhythem', 'Rhythm', 'Rythim'], answer: 'Rhythm', explanation: 'Rhythm has no standard vowel (a, e, i, o, u). Remember: Rhythm Helps Your Two Hips Move.', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 448, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Scedule', 'Schedule', 'Shedule', 'Scheduel'], answer: 'Schedule', explanation: 'Schedule starts with "sch-" (like school). "Sche" + "dule".', level: 'Easy', tier: 'both', examProb: 'Confirmed' },
  { id: 449, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Scissors', 'Scisors', 'Sissors', 'Scizzors'], answer: 'Scissors', explanation: 'Scissors: "sc" at the start, double "s" in the middle, ends in "-ors".', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 450, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Significanse', 'Significance', 'Significence', 'Signifcance'], answer: 'Significance', explanation: 'Significance: "signific" + "ance". Ends in "-ance", not "-ence" or "-anse".', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 451, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Sincerly', 'Sincerely', 'Sinserely', 'Sincerley'], answer: 'Sincerely', explanation: 'Sincerely: "sincere" + "ly". The "e" in "sincere" stays when adding "-ly".', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 452, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Sufficent', 'Sufficient', 'Sufficeint', 'Suficient'], answer: 'Sufficient', explanation: 'Sufficient: double "f" and "-ient" ending. "Suf" + "fic" + "ient".', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 453, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Tecnique', 'Techneque', 'Technique', 'Technicue'], answer: 'Technique', explanation: 'Technique: "tech" + "nique". The "-nique" ending is from the French.', level: 'Easy', tier: 'both', examProb: 'Confirmed' },
  { id: 454, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Temperature', 'Temprature', 'Temperture', 'Temparature'], answer: 'Temperature', explanation: 'Temperature: "temper" + "ature". Think of "temper" as the root word.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 455, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Thorough', 'Thorogh', 'Thurough', 'Thourough'], answer: 'Thorough', explanation: 'Thorough: "thor" + "ough" (like "though" with an "r").', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 456, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Tommorow', 'Tommorrow', 'Tomorrow', 'Tomorow'], answer: 'Tomorrow', explanation: 'Tomorrow: one "m" and double "r" — wait, no! One "m", one "r", double nothing. "To" + "morrow".', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 457, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Unfortunatly', 'Unfortunately', 'Unfortunetly', 'Unfourtunately'], answer: 'Unfortunately', explanation: 'Unfortunately: "un" + "fortunate" + "ly". Keep "fortunate" intact and add prefix/suffix.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 458, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Vehical', 'Vehicle', 'Vehicel', 'Vahicle'], answer: 'Vehicle', explanation: 'Vehicle: "vehi" + "cle". Ends in "-cle" like "article".', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 459, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Wensday', 'Wedensday', 'Wednesday', 'Wendesday'], answer: 'Wednesday', explanation: 'Wednesday: named after Woden (Norse god). "Wed" + "nes" + "day". The silent "d" after "e" is key.', level: 'Easy', tier: 'both', examProb: 'Confirmed' },
  { id: 460, qtype: 'spelling-correction', question: 'Choose the correctly spelled word.', options: ['Acquaintence', 'Acquaintance', 'Aquaintance', 'Acquantance'], answer: 'Acquaintance', explanation: 'Acquaintance: "acqu" + "aint" + "ance". Double "c" (as "cq") and "-ance" ending.', level: 'Medium', tier: 'both', examProb: 'Hot' },

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 2 — ACTIVE/PASSIVE VOICE (40 questions, ids 461–500)
  // ═══════════════════════════════════════════════════════════════════════

  // — Simple Present —
  { id: 461, qtype: 'active-passive', question: 'Change to passive voice: "The cat chases the mouse."', options: ['The mouse is chased by the cat.', 'The mouse was chased by the cat.', 'The mouse has been chased by the cat.', 'The mouse is being chased by the cat.'], answer: 'The mouse is chased by the cat.', explanation: 'Simple Present Active → Simple Present Passive. "chases" (V1/Vs) becomes "is chased" (is + V3).', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 462, qtype: 'active-passive', question: 'Change to passive voice: "She writes a letter every day."', options: ['A letter is written by her every day.', 'A letter was written by her every day.', 'A letter is being written by her every day.', 'A letter has been written by her every day.'], answer: 'A letter is written by her every day.', explanation: 'Simple Present Active → Simple Present Passive. "writes" → "is written".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 463, qtype: 'active-passive', question: 'Change to passive voice: "They make shoes in this factory."', options: ['Shoes are made in this factory.', 'Shoes were made in this factory.', 'Shoes have been made in this factory.', 'Shoes are being made in this factory.'], answer: 'Shoes are made in this factory.', explanation: 'Simple Present Active → Simple Present Passive. "make" → "are made". Agent ("by them") is dropped when unnecessary.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 464, qtype: 'active-passive', question: 'Change to passive voice: "The teacher punishes the students."', options: ['The students were punished by the teacher.', 'The students are being punished by the teacher.', 'The students are punished by the teacher.', 'The students have been punished by the teacher.'], answer: 'The students are punished by the teacher.', explanation: 'Simple Present: "punishes" → "are punished". Subject-verb agreement: plural "students" takes "are".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 465, qtype: 'active-passive', question: 'Change to passive voice: "He does not help the poor."', options: ['The poor are not helped by him.', 'The poor were not helped by him.', 'The poor is not helped by him.', 'The poor have not been helped by him.'], answer: 'The poor are not helped by him.', explanation: 'Simple Present Negative: "does not help" → "are not helped". "The poor" is plural.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Simple Past —
  { id: 466, qtype: 'active-passive', question: 'Change to passive voice: "The cat chased the mouse."', options: ['The mouse was chased by the cat.', 'The mouse is chased by the cat.', 'The mouse has been chased by the cat.', 'The mouse was being chased by the cat.'], answer: 'The mouse was chased by the cat.', explanation: 'Simple Past Active → Simple Past Passive. "chased" (V2) becomes "was chased" (was + V3).', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 467, qtype: 'active-passive', question: 'Change to passive voice: "Columbus discovered America."', options: ['America was discovered by Columbus.', 'America is discovered by Columbus.', 'America has been discovered by Columbus.', 'America was being discovered by Columbus.'], answer: 'America was discovered by Columbus.', explanation: 'Simple Past: "discovered" → "was discovered". Proper noun kept as agent.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 468, qtype: 'active-passive', question: 'Change to passive voice: "They built this bridge in 1990."', options: ['This bridge was built in 1990.', 'This bridge is built in 1990.', 'This bridge had been built in 1990.', 'This bridge was being built in 1990.'], answer: 'This bridge was built in 1990.', explanation: 'Simple Past: "built" → "was built". Agent omitted as it is obvious/unimportant.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 469, qtype: 'active-passive', question: 'Change to passive voice: "She did not accept the offer."', options: ['The offer was not accepted by her.', 'The offer is not accepted by her.', 'The offer has not been accepted by her.', 'The offer had not been accepted by her.'], answer: 'The offer was not accepted by her.', explanation: 'Simple Past Negative: "did not accept" → "was not accepted".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 470, qtype: 'active-passive', question: 'Change to passive voice: "The police arrested the thief."', options: ['The thief has been arrested by the police.', 'The thief was arrested by the police.', 'The thief is arrested by the police.', 'The thief was being arrested by the police.'], answer: 'The thief was arrested by the police.', explanation: 'Simple Past: "arrested" → "was arrested".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Present Continuous —
  { id: 471, qtype: 'active-passive', question: 'Change to passive voice: "She is singing a song."', options: ['A song is being sung by her.', 'A song was being sung by her.', 'A song is sung by her.', 'A song has been sung by her.'], answer: 'A song is being sung by her.', explanation: 'Present Continuous: "is singing" → "is being sung" (is + being + V3).', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 472, qtype: 'active-passive', question: 'Change to passive voice: "They are building a new school."', options: ['A new school is built by them.', 'A new school is being built by them.', 'A new school was being built by them.', 'A new school has been built by them.'], answer: 'A new school is being built by them.', explanation: 'Present Continuous: "are building" → "is being built".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 473, qtype: 'active-passive', question: 'Change to passive voice: "The mechanic is repairing the car."', options: ['The car is being repaired by the mechanic.', 'The car was being repaired by the mechanic.', 'The car is repaired by the mechanic.', 'The car has been repaired by the mechanic.'], answer: 'The car is being repaired by the mechanic.', explanation: 'Present Continuous: "is repairing" → "is being repaired".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Past Continuous —
  { id: 474, qtype: 'active-passive', question: 'Change to passive voice: "She was reading a novel."', options: ['A novel was read by her.', 'A novel was being read by her.', 'A novel is being read by her.', 'A novel had been read by her.'], answer: 'A novel was being read by her.', explanation: 'Past Continuous: "was reading" → "was being read" (was + being + V3).', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 475, qtype: 'active-passive', question: 'Change to passive voice: "The children were playing cricket."', options: ['Cricket was being played by the children.', 'Cricket is being played by the children.', 'Cricket was played by the children.', 'Cricket had been played by the children.'], answer: 'Cricket was being played by the children.', explanation: 'Past Continuous: "were playing" → "was being played".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 476, qtype: 'active-passive', question: 'Change to passive voice: "He was writing a report."', options: ['A report was being written by him.', 'A report is being written by him.', 'A report was written by him.', 'A report has been written by him.'], answer: 'A report was being written by him.', explanation: 'Past Continuous: "was writing" → "was being written".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Present Perfect —
  { id: 477, qtype: 'active-passive', question: 'Change to passive voice: "She has completed the assignment."', options: ['The assignment has been completed by her.', 'The assignment was completed by her.', 'The assignment is completed by her.', 'The assignment had been completed by her.'], answer: 'The assignment has been completed by her.', explanation: 'Present Perfect: "has completed" → "has been completed" (has + been + V3).', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 478, qtype: 'active-passive', question: 'Change to passive voice: "They have finished the work."', options: ['The work has been finished by them.', 'The work was finished by them.', 'The work is finished by them.', 'The work had been finished by them.'], answer: 'The work has been finished by them.', explanation: 'Present Perfect: "have finished" → "has been finished". Singular "work" takes "has".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 479, qtype: 'active-passive', question: 'Change to passive voice: "I have not seen the movie."', options: ['The movie has not been seen by me.', 'The movie was not seen by me.', 'The movie is not seen by me.', 'The movie had not been seen by me.'], answer: 'The movie has not been seen by me.', explanation: 'Present Perfect Negative: "have not seen" → "has not been seen".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 480, qtype: 'active-passive', question: 'Change to passive voice: "Someone has stolen my bicycle."', options: ['My bicycle has been stolen.', 'My bicycle was stolen.', 'My bicycle is stolen.', 'My bicycle had been stolen.'], answer: 'My bicycle has been stolen.', explanation: 'Present Perfect: "has stolen" → "has been stolen". Agent ("by someone") is dropped.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Past Perfect —
  { id: 481, qtype: 'active-passive', question: 'Change to passive voice: "He had finished the homework before dinner."', options: ['The homework had been finished by him before dinner.', 'The homework has been finished by him before dinner.', 'The homework was finished by him before dinner.', 'The homework was being finished by him before dinner.'], answer: 'The homework had been finished by him before dinner.', explanation: 'Past Perfect: "had finished" → "had been finished" (had + been + V3).', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 482, qtype: 'active-passive', question: 'Change to passive voice: "They had already sold all the tickets."', options: ['All the tickets had already been sold.', 'All the tickets have already been sold.', 'All the tickets were already sold.', 'All the tickets are already sold.'], answer: 'All the tickets had already been sold.', explanation: 'Past Perfect: "had sold" → "had been sold". Agent omitted.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 483, qtype: 'active-passive', question: 'Change to passive voice: "She had written three letters before noon."', options: ['Three letters had been written by her before noon.', 'Three letters were written by her before noon.', 'Three letters have been written by her before noon.', 'Three letters was written by her before noon.'], answer: 'Three letters had been written by her before noon.', explanation: 'Past Perfect: "had written" → "had been written".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Future Simple —
  { id: 484, qtype: 'active-passive', question: 'Change to passive voice: "She will deliver the parcel tomorrow."', options: ['The parcel will be delivered by her tomorrow.', 'The parcel would be delivered by her tomorrow.', 'The parcel shall be delivered by her tomorrow.', 'The parcel is delivered by her tomorrow.'], answer: 'The parcel will be delivered by her tomorrow.', explanation: 'Future Simple: "will deliver" → "will be delivered" (will + be + V3).', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 485, qtype: 'active-passive', question: 'Change to passive voice: "They will announce the results next week."', options: ['The results will be announced next week.', 'The results would be announced next week.', 'The results shall be announced next week.', 'The results are announced next week.'], answer: 'The results will be announced next week.', explanation: 'Future Simple: "will announce" → "will be announced". Agent omitted.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 486, qtype: 'active-passive', question: 'Change to passive voice: "The government will launch a new scheme."', options: ['A new scheme will be launched by the government.', 'A new scheme would be launched by the government.', 'A new scheme is launched by the government.', 'A new scheme has been launched by the government.'], answer: 'A new scheme will be launched by the government.', explanation: 'Future Simple: "will launch" → "will be launched".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Modal Verbs —
  { id: 487, qtype: 'active-passive', question: 'Change to passive voice: "You must complete this form."', options: ['This form must be completed by you.', 'This form must completed by you.', 'This form must been completed by you.', 'This form must have completed by you.'], answer: 'This form must be completed by you.', explanation: 'Modal + V1 → Modal + be + V3. "must complete" → "must be completed".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 488, qtype: 'active-passive', question: 'Change to passive voice: "She can solve this problem."', options: ['This problem can be solved by her.', 'This problem could be solved by her.', 'This problem can solved by her.', 'This problem is solved by her.'], answer: 'This problem can be solved by her.', explanation: 'Modal: "can solve" → "can be solved" (can + be + V3).', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 489, qtype: 'active-passive', question: 'Change to passive voice: "He should help the needy."', options: ['The needy should be helped by him.', 'The needy should helped by him.', 'The needy should been helped by him.', 'The needy are helped by him.'], answer: 'The needy should be helped by him.', explanation: 'Modal: "should help" → "should be helped" (should + be + V3).', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 490, qtype: 'active-passive', question: 'Change to passive voice: "They may cancel the flight."', options: ['The flight may be cancelled by them.', 'The flight may cancelled by them.', 'The flight might be cancelled by them.', 'The flight is cancelled by them.'], answer: 'The flight may be cancelled by them.', explanation: 'Modal: "may cancel" → "may be cancelled" (may + be + V3).', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Passive to Active (reverse) —
  { id: 491, qtype: 'active-passive', question: 'Change to active voice: "The cake was baked by my mother."', options: ['My mother baked the cake.', 'My mother bakes the cake.', 'My mother has baked the cake.', 'My mother was baking the cake.'], answer: 'My mother baked the cake.', explanation: 'Simple Past Passive → Simple Past Active. "was baked" → "baked" (V2).', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 492, qtype: 'active-passive', question: 'Change to active voice: "The window was broken by the boys."', options: ['The boys broke the window.', 'The boys break the window.', 'The boys have broken the window.', 'The boys were breaking the window.'], answer: 'The boys broke the window.', explanation: 'Simple Past Passive → Active. "was broken" → "broke".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 493, qtype: 'active-passive', question: 'Change to active voice: "A new hospital is being built by the government."', options: ['The government is building a new hospital.', 'The government builds a new hospital.', 'The government was building a new hospital.', 'The government has built a new hospital.'], answer: 'The government is building a new hospital.', explanation: 'Present Continuous Passive → Active. "is being built" → "is building".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 494, qtype: 'active-passive', question: 'Change to active voice: "The letter has been posted by Ravi."', options: ['Ravi has posted the letter.', 'Ravi posted the letter.', 'Ravi posts the letter.', 'Ravi had posted the letter.'], answer: 'Ravi has posted the letter.', explanation: 'Present Perfect Passive → Active. "has been posted" → "has posted".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 495, qtype: 'active-passive', question: 'Change to active voice: "The match will be won by our team."', options: ['Our team will win the match.', 'Our team wins the match.', 'Our team won the match.', 'Our team would win the match.'], answer: 'Our team will win the match.', explanation: 'Future Simple Passive → Active. "will be won" → "will win".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // — Interrogative / Mixed —
  { id: 496, qtype: 'active-passive', question: 'Change to passive voice: "Who wrote this book?"', options: ['By whom was this book written?', 'By whom is this book written?', 'By whom has this book been written?', 'Who was written this book?'], answer: 'By whom was this book written?', explanation: '"Who" (subject) in active becomes "By whom" in passive. Simple Past tense maintained.', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 497, qtype: 'active-passive', question: 'Change to passive voice: "Did the teacher scold you?"', options: ['Were you scolded by the teacher?', 'Was you scolded by the teacher?', 'Are you scolded by the teacher?', 'Have you been scolded by the teacher?'], answer: 'Were you scolded by the teacher?', explanation: 'Simple Past Interrogative: "Did ... scold" → "Were ... scolded". "You" takes "were".', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 498, qtype: 'active-passive', question: 'Change to passive voice: "People speak English all over the world."', options: ['English is spoken all over the world.', 'English was spoken all over the world.', 'English has been spoken all over the world.', 'English is being spoken all over the world.'], answer: 'English is spoken all over the world.', explanation: 'Simple Present: "speak" → "is spoken". Generic agent ("people") is dropped.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 499, qtype: 'active-passive', question: 'Change to passive voice: "The manager had already approved the leave."', options: ['The leave had already been approved by the manager.', 'The leave has already been approved by the manager.', 'The leave was already approved by the manager.', 'The leave already had been approved by the manager.'], answer: 'The leave had already been approved by the manager.', explanation: 'Past Perfect: "had approved" → "had been approved". Adverb "already" placed after "had".', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },
  { id: 500, qtype: 'active-passive', question: 'Change to passive voice: "We could hear the thunder clearly."', options: ['The thunder could be heard clearly.', 'The thunder could been heard clearly.', 'The thunder can be heard clearly.', 'The thunder was heard clearly.'], answer: 'The thunder could be heard clearly.', explanation: 'Modal "could": "could hear" → "could be heard" (could + be + V3).', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Active/Passive Voice' },

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 3 — DIRECT/INDIRECT SPEECH (40 questions, ids 501–540)
  // ═══════════════════════════════════════════════════════════════════════

  // — Statements (Present → Past backshift) —
  { id: 501, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "I am happy."', options: ['He said that he was happy.', 'He said that he is happy.', 'He told that he was happy.', 'He says that he was happy.'], answer: 'He said that he was happy.', explanation: '"am" changes to "was" (present → past). "I" changes to "he". "said" stays. No "told" without an object.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 502, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "I like chocolate."', options: ['She said that she liked chocolate.', 'She said that she likes chocolate.', 'She told that she liked chocolate.', 'She said that she had liked chocolate.'], answer: 'She said that she liked chocolate.', explanation: '"like" (Simple Present) changes to "liked" (Simple Past). "I" → "she".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 503, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "I am going to the market."', options: ['He said that he was going to the market.', 'He said that he is going to the market.', 'He told that he was going to the market.', 'He said that he had been going to the market.'], answer: 'He said that he was going to the market.', explanation: 'Present Continuous "am going" → Past Continuous "was going". "I" → "he".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 504, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "I have finished my work."', options: ['She said that she had finished her work.', 'She said that she has finished her work.', 'She told that she had finished her work.', 'She said that she finished her work.'], answer: 'She said that she had finished her work.', explanation: 'Present Perfect "have finished" → Past Perfect "had finished". "my" → "her".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 505, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "I will come tomorrow."', options: ['He said that he would come the next day.', 'He said that he will come tomorrow.', 'He said that he would come tomorrow.', 'He told that he would come the next day.'], answer: 'He said that he would come the next day.', explanation: '"will" → "would". "tomorrow" → "the next day". "I" → "he". Both tense and time expression change.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 506, qtype: 'direct-indirect', question: 'Change to indirect speech: Ram said, "I was playing cricket."', options: ['Ram said that he had been playing cricket.', 'Ram said that he was playing cricket.', 'Ram told that he had been playing cricket.', 'Ram said that he is playing cricket.'], answer: 'Ram said that he had been playing cricket.', explanation: 'Past Continuous "was playing" → Past Perfect Continuous "had been playing".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 507, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "I had already eaten."', options: ['She said that she had already eaten.', 'She said that she has already eaten.', 'She said that she already ate.', 'She told that she had already eaten.'], answer: 'She said that she had already eaten.', explanation: 'Past Perfect does not change further. "had eaten" stays "had eaten". "I" → "she".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 508, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "I can swim well."', options: ['He said that he could swim well.', 'He said that he can swim well.', 'He told that he could swim well.', 'He said that he was able to swim well.'], answer: 'He said that he could swim well.', explanation: '"can" → "could". Modal verbs shift back one step in reported speech.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 509, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "I may go to Delhi."', options: ['She said that she might go to Delhi.', 'She said that she may go to Delhi.', 'She told that she might go to Delhi.', 'She said that she could go to Delhi.'], answer: 'She said that she might go to Delhi.', explanation: '"may" → "might" in reported speech.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 510, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "I must leave now."', options: ['He said that he had to leave then.', 'He said that he must leave now.', 'He said that he must leave then.', 'He told that he had to leave then.'], answer: 'He said that he had to leave then.', explanation: '"must" → "had to". "now" → "then". Both modal and time expression change.', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },

  // — Statements with time/place changes —
  { id: 511, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "I bought this dress yesterday."', options: ['She said that she had bought that dress the previous day.', 'She said that she bought that dress yesterday.', 'She said that she had bought this dress yesterday.', 'She told that she had bought that dress the day before.'], answer: 'She said that she had bought that dress the previous day.', explanation: '"bought" → "had bought". "this" → "that". "yesterday" → "the previous day".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 512, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "I live here."', options: ['He said that he lived there.', 'He said that he lives here.', 'He said that he lived here.', 'He told that he lived there.'], answer: 'He said that he lived there.', explanation: '"live" → "lived". "here" → "there". Both tense and place change.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 513, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "I shall come today."', options: ['She said that she would come that day.', 'She said that she shall come today.', 'She said that she would come today.', 'She told that she would come that day.'], answer: 'She said that she would come that day.', explanation: '"shall" → "would". "today" → "that day". "I" → "she".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },

  // — Questions (Yes/No) —
  { id: 514, qtype: 'direct-indirect', question: 'Change to indirect speech: He said to me, "Are you coming?"', options: ['He asked me if I was coming.', 'He asked me that I was coming.', 'He asked me whether am I coming.', 'He told me if I was coming.'], answer: 'He asked me if I was coming.', explanation: 'Yes/No question: "said to" → "asked". Use "if/whether". No question mark. "are" → "was". "you" → "I".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 515, qtype: 'direct-indirect', question: 'Change to indirect speech: She said to him, "Do you like tea?"', options: ['She asked him if he liked tea.', 'She asked him that he liked tea.', 'She asked him did he like tea.', 'She told him if he liked tea.'], answer: 'She asked him if he liked tea.', explanation: 'Yes/No question: "Do you like" → "if he liked". Remove "do/does" and backshift tense.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 516, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "Have you seen my keys?"', options: ['He asked if I had seen his keys.', 'He asked that I had seen his keys.', 'He asked whether have I seen his keys.', 'He told whether I had seen his keys.'], answer: 'He asked if I had seen his keys.', explanation: 'Yes/No question: "Have you seen" → "if I had seen". Present Perfect → Past Perfect. "my" → "his".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 517, qtype: 'direct-indirect', question: 'Change to indirect speech: She said to me, "Will you help me?"', options: ['She asked me if I would help her.', 'She asked me that I would help her.', 'She asked me will I help her.', 'She told me if I would help her.'], answer: 'She asked me if I would help her.', explanation: '"Will you" → "if I would". "will" → "would". "me" (speaker) → "her".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },

  // — Questions (Wh-) —
  { id: 518, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "Where do you live?"', options: ['He asked where I lived.', 'He asked where did I live.', 'He asked that where I lived.', 'He told where I lived.'], answer: 'He asked where I lived.', explanation: 'Wh-question: keep "where" as conjunction. Remove "do". "live" → "lived". No question mark.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 519, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "What are you doing?"', options: ['She asked what I was doing.', 'She asked what was I doing.', 'She asked that what I was doing.', 'She told what I was doing.'], answer: 'She asked what I was doing.', explanation: 'Wh-question: "What are you doing" → "what I was doing". Statement word order in indirect.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 520, qtype: 'direct-indirect', question: 'Change to indirect speech: He asked, "Why did you come late?"', options: ['He asked why I had come late.', 'He asked why did I come late.', 'He asked that why I had come late.', 'He asked why I came late.'], answer: 'He asked why I had come late.', explanation: '"did come" (Simple Past) → "had come" (Past Perfect). Wh-word "why" acts as conjunction.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 521, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "When will you return?"', options: ['She asked when I would return.', 'She asked when would I return.', 'She asked that when I would return.', 'She told when I would return.'], answer: 'She asked when I would return.', explanation: 'Wh-question: "will" → "would". Statement order: "when I would return".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 522, qtype: 'direct-indirect', question: 'Change to indirect speech: He asked, "Who broke the window?"', options: ['He asked who had broken the window.', 'He asked who did break the window.', 'He asked that who had broken the window.', 'He asked who broke the window.'], answer: 'He asked who had broken the window.', explanation: '"broke" (Simple Past) → "had broken" (Past Perfect). "Who" remains as conjunction.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },

  // — Imperatives —
  { id: 523, qtype: 'direct-indirect', question: 'Change to indirect speech: The teacher said, "Open your books."', options: ['The teacher ordered them to open their books.', 'The teacher said to open your books.', 'The teacher told that open their books.', 'The teacher ordered that they opened their books.'], answer: 'The teacher ordered them to open their books.', explanation: 'Imperative (command): "said" → "ordered/told/asked" + object + to + V1. "your" → "their".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 524, qtype: 'direct-indirect', question: 'Change to indirect speech: She said to me, "Please help me."', options: ['She requested me to help her.', 'She told me to please help her.', 'She said that please help her.', 'She requested that I helped her.'], answer: 'She requested me to help her.', explanation: '"Please" indicates a request: use "requested". "me" (speaker) → "her".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 525, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "Do not touch the wire."', options: ['He warned not to touch the wire.', 'He said do not touch the wire.', 'He told that not to touch the wire.', 'He warned to not touched the wire.'], answer: 'He warned not to touch the wire.', explanation: 'Negative imperative (warning): "Do not" → "not to". Use "warned/advised/cautioned".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 526, qtype: 'direct-indirect', question: 'Change to indirect speech: Mother said to me, "Do not go out in the rain."', options: ['Mother advised me not to go out in the rain.', 'Mother told me do not go out in the rain.', 'Mother said that I did not go out in the rain.', 'Mother advised me to not went out in the rain.'], answer: 'Mother advised me not to go out in the rain.', explanation: 'Imperative (advice): "said to" → "advised" + object + not + to + V1.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 527, qtype: 'direct-indirect', question: 'Change to indirect speech: The officer said, "Stand up immediately."', options: ['The officer commanded to stand up immediately.', 'The officer said that stand up immediately.', 'The officer told that to stand up immediately.', 'The officer commanded that stood up immediately.'], answer: 'The officer commanded to stand up immediately.', explanation: 'Strong imperative (command): use "commanded/ordered" + to + V1.', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },

  // — Exclamations —
  { id: 528, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "What a beautiful painting!"', options: ['She exclaimed that it was a very beautiful painting.', 'She said that what a beautiful painting.', 'She exclaimed that what a beautiful painting it is.', 'She told that it was a beautiful painting.'], answer: 'She exclaimed that it was a very beautiful painting.', explanation: 'Exclamation: "What a" is replaced. Use "exclaimed that" + statement. "very" replaces the exclamatory force.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 529, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "Hurrah! We won the match!"', options: ['He exclaimed with joy that they had won the match.', 'He said hurrah that they won the match.', 'He exclaimed that hurrah they had won the match.', 'He told that they had won the match joyfully.'], answer: 'He exclaimed with joy that they had won the match.', explanation: '"Hurrah" indicates joy: "exclaimed with joy". "won" → "had won". "We" → "they".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 530, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "Alas! I have lost my purse."', options: ['She exclaimed with sorrow that she had lost her purse.', 'She said alas that she lost her purse.', 'She exclaimed that alas she had lost her purse.', 'She told that she had lost her purse sadly.'], answer: 'She exclaimed with sorrow that she had lost her purse.', explanation: '"Alas" indicates grief: "exclaimed with sorrow". "have lost" → "had lost". "my" → "her".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },

  // — Indirect to Direct (reverse) —
  { id: 531, qtype: 'direct-indirect', question: 'Change to direct speech: He told me that he was tired.', options: ['He said to me, "I am tired."', 'He said to me, "He was tired."', 'He said to me, "I was tired."', 'He told me, "I am tired."'], answer: 'He said to me, "I am tired."', explanation: 'Reverse backshift: "was" → "am". "he" → "I". "told me" → "said to me" + quotation marks.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 532, qtype: 'direct-indirect', question: 'Change to direct speech: She asked me if I had seen her book.', options: ['She said to me, "Have you seen my book?"', 'She said to me, "Had you seen my book?"', 'She said to me, "Did you see my book?"', 'She said, "Have you seen her book?"'], answer: 'She said to me, "Have you seen my book?"', explanation: 'Reverse: "had seen" → "Have you seen" (Past Perfect → Present Perfect). "her" → "my". Add question mark.', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 533, qtype: 'direct-indirect', question: 'Change to direct speech: The teacher ordered the students to sit down.', options: ['The teacher said, "Sit down."', 'The teacher said, "You should sit down."', 'The teacher said, "They sat down."', 'The teacher said, "To sit down."'], answer: 'The teacher said, "Sit down."', explanation: 'Imperative reverse: "ordered to sit down" → "Sit down." (imperative form).', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },

  // — said vs told, mixed structures —
  { id: 534, qtype: 'direct-indirect', question: 'Change to indirect speech: He said to her, "I love you."', options: ['He told her that he loved her.', 'He said her that he loved her.', 'He told to her that he loved her.', 'He told her that he loves her.'], answer: 'He told her that he loved her.', explanation: '"said to her" → "told her" (told always needs an object). "love" → "loved". "you" → "her".', level: 'Easy', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 535, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "I was cooking dinner."', options: ['She said that she had been cooking dinner.', 'She said that she was cooking dinner.', 'She told that she had been cooking dinner.', 'She said that she is cooking dinner.'], answer: 'She said that she had been cooking dinner.', explanation: 'Past Continuous → Past Perfect Continuous: "was cooking" → "had been cooking".', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 536, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "I shall not go there."', options: ['He said that he would not go there.', 'He said that he shall not go there.', 'He told that he would not go there.', 'He said that he should not go there.'], answer: 'He said that he would not go there.', explanation: '"shall" → "would" in reported speech. "not" stays. "there" remains unchanged.', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 537, qtype: 'direct-indirect', question: 'Change to indirect speech: The doctor said, "You should take rest."', options: ['The doctor advised that I should take rest.', 'The doctor told me that I should take rest.', 'The doctor advised me to take rest.', 'The doctor said that you should take rest.'], answer: 'The doctor advised me to take rest.', explanation: 'Advice with "should": reporting verb changes to "advised" + object + to + V1.', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 538, qtype: 'direct-indirect', question: 'Change to indirect speech: He said, "How clever you are!"', options: ['He exclaimed that I was very clever.', 'He said that how clever I was.', 'He exclaimed that how clever I am.', 'He told that I was very clever.'], answer: 'He exclaimed that I was very clever.', explanation: 'Exclamation with "How": use "exclaimed that" + statement. "How clever" → "very clever".', level: 'Medium', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 539, qtype: 'direct-indirect', question: 'Change to indirect speech: She said, "Let us go for a walk."', options: ['She suggested that they should go for a walk.', 'She said that let them go for a walk.', 'She told to go for a walk.', 'She suggested that they go for walk.'], answer: 'She suggested that they should go for a walk.', explanation: '"Let us" (proposal) → "suggested that they should". Use "suggested" for proposals.', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },
  { id: 540, qtype: 'direct-indirect', question: 'Change to indirect speech: He said to me, "Where have you been since morning?"', options: ['He asked me where I had been since morning.', 'He asked me where had I been since morning.', 'He asked me that where I had been since morning.', 'He told me where I had been since morning.'], answer: 'He asked me where I had been since morning.', explanation: 'Wh-question: "Where have you been" → "where I had been". Present Perfect → Past Perfect. Statement order.', level: 'Hard', tier: 'both', examProb: 'Hot', grammarTopic: 'Direct/Indirect Speech' },

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 4 — PARA JUMBLE (30 questions, ids 541–570)
  // ═══════════════════════════════════════════════════════════════════════

  { id: 541, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He went to the market.\nQ. He bought some vegetables.\nR. He left home early in the morning.\nS. He returned home by noon.', options: ['RPQS', 'PRQS', 'RPSQ', 'QRPS'], answer: 'RPQS', explanation: 'Logical sequence: Left home (R) → went to market (P) → bought vegetables (Q) → returned home (S).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 542, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The interviewer asked him several questions.\nQ. He was selected for the post.\nR. He applied for the job.\nS. He appeared for the interview.', options: ['RSPQ', 'RSQP', 'SPRQ', 'RPQS'], answer: 'RSPQ', explanation: 'Job process: Applied (R) → appeared for interview (S) → was asked questions (P) → selected (Q).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 543, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He was admitted to the hospital.\nQ. He met with a serious accident.\nR. He was driving fast on the highway.\nS. The doctors operated on him immediately.', options: ['RQPS', 'QRPS', 'RPQS', 'RQSP'], answer: 'RQPS', explanation: 'Sequence: Driving fast (R) → accident (Q) → admitted to hospital (P) → doctors operated (S).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 544, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. But the fox could not reach them.\nQ. A fox once saw some grapes hanging from a vine.\nR. He said, "The grapes are sour."\nS. He jumped again and again to reach them.', options: ['QSPR', 'QPSR', 'SQPR', 'QSRP'], answer: 'QSPR', explanation: 'Story order: Saw grapes (Q) → jumped (S) → could not reach (P) → said "sour" (R). Classic Aesop fable.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 545, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. All the guests praised the food.\nQ. She invited her friends to dinner.\nR. She spent the whole day cooking.\nS. The dinner was a grand success.', options: ['QRPS', 'RQPS', 'QRSP', 'RQSP'], answer: 'QRPS', explanation: 'Sequence: Invited friends (Q) → cooked all day (R) → guests praised food (P) → dinner was success (S).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 546, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The thief was caught by the police.\nQ. The shopkeeper called the police.\nR. A thief broke into a shop at night.\nS. The neighbours heard the alarm and rushed out.', options: ['RSQP', 'RSPQ', 'SQRP', 'RQSP'], answer: 'RSQP', explanation: 'Sequence: Broke in (R) → neighbours heard alarm (S) → called police (Q) → thief caught (P).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 547, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He scored the highest marks in the class.\nQ. He worked hard throughout the year.\nR. His parents were proud of him.\nS. The results were declared last week.', options: ['QSPR', 'SQPR', 'QPSR', 'SPQR'], answer: 'QSPR', explanation: 'Sequence: Worked hard (Q) → results declared (S) → scored highest (P) → parents proud (R).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 548, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. She was rushed to the hospital.\nQ. She slipped on the wet floor.\nR. The doctor applied a plaster to her leg.\nS. She fractured her leg.', options: ['QSPR', 'SQPR', 'QPSR', 'QSRP'], answer: 'QSPR', explanation: 'Cause-effect: Slipped (Q) → fractured leg (S) → rushed to hospital (P) → doctor treated (R).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 549, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He could not clear the exam.\nQ. He decided to try again next year.\nR. He had not prepared well.\nS. He was very disappointed.', options: ['RPQS', 'RPSQ', 'PRQS', 'RPSP'], answer: 'RPSQ', explanation: 'Sequence: Not prepared well (R) → could not clear exam (P) → disappointed (S) → decided to try again (Q).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 550, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The ship began to sink.\nQ. The passengers were rescued by a helicopter.\nR. A violent storm hit the ship.\nS. The captain sent a distress signal.', options: ['RPSQ', 'RPQS', 'PRQS', 'RSPQ'], answer: 'RPSQ', explanation: 'Sequence: Storm hit (R) → ship sinking (P) → distress signal sent (S) → passengers rescued (Q).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 551, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The seeds sprouted within a week.\nQ. She watered the plants daily.\nR. She planted some flower seeds in her garden.\nS. Beautiful flowers bloomed in a month.', options: ['RQPS', 'RPQS', 'RQSP', 'QRPS'], answer: 'RQPS', explanation: 'Garden sequence: Planted seeds (R) → watered daily (Q) → seeds sprouted (P) → flowers bloomed (S).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 552, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He was taken to the nearest hospital.\nQ. A boy fell from the tree.\nR. He climbed a tall mango tree.\nS. He was treated for minor injuries.', options: ['RQPS', 'QRPS', 'RPQS', 'RQSP'], answer: 'RQPS', explanation: 'Sequence: Climbed tree (R) → fell (Q) → taken to hospital (P) → treated (S).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 553, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The lion pounced on the deer.\nQ. A deer was drinking water at the river.\nR. The lion was hiding behind the bushes.\nS. The deer could not escape.', options: ['RQPS', 'QRPS', 'RPQS', 'RQSP'], answer: 'RQPS', explanation: 'Sequence: Lion hiding (R) → deer drinking water (Q) → lion pounced (P) → deer could not escape (S).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 554, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. Finally, the project was completed on time.\nQ. The team worked day and night.\nR. A challenging project was assigned to them.\nS. They divided the work among themselves.', options: ['RSQP', 'RQSP', 'SQRP', 'RSPQ'], answer: 'RSQP', explanation: 'Work sequence: Project assigned (R) → divided work (S) → worked day and night (Q) → completed on time (P).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 555, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. She thanked the old man for his kindness.\nQ. An old man showed her the way.\nR. She had lost her way in the city.\nS. She finally reached her destination.', options: ['RQSP', 'RQPS', 'QRPS', 'RSPQ'], answer: 'RQSP', explanation: 'Sequence: Lost way (R) → old man helped (Q) → reached destination (S) → thanked him (P).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 556, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He became one of the richest men in the world.\nQ. He dropped out of college.\nR. He founded a technology company.\nS. He had a passion for computers since childhood.', options: ['SQRP', 'QSRP', 'SRQP', 'SQPR'], answer: 'SQRP', explanation: 'Biography order: Passion since childhood (S) → dropped out (Q) → founded company (R) → became rich (P).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 557, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The flight was delayed by three hours.\nQ. He reached the airport on time.\nR. He started from home early in the morning.\nS. He was annoyed by the long wait.', options: ['RQPS', 'RQSP', 'QRPS', 'RPQS'], answer: 'RQPS', explanation: 'Sequence: Started from home (R) → reached airport (Q) → flight delayed (P) → annoyed (S).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 558, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He was declared the winner of the competition.\nQ. He practised for months.\nR. He participated in a national singing competition.\nS. The judges were impressed by his performance.', options: ['QRSP', 'RQSP', 'QRPS', 'RQPS'], answer: 'QRSP', explanation: 'Sequence: Practised (Q) → participated (R) → judges impressed (S) → declared winner (P).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 559, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The crops were destroyed.\nQ. The farmers were left in despair.\nR. There was no rain for several months.\nS. The government announced relief measures.', options: ['RPQS', 'RQPS', 'PRQS', 'RPSP'], answer: 'RPQS', explanation: 'Drought sequence: No rain (R) → crops destroyed (P) → farmers in despair (Q) → government relief (S).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 560, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The audience gave him a standing ovation.\nQ. He delivered an inspiring speech.\nR. He was invited as the chief guest.\nS. The event concluded with a vote of thanks.', options: ['RQPS', 'QRPS', 'RPQS', 'RQSP'], answer: 'RQPS', explanation: 'Event order: Invited as chief guest (R) → delivered speech (Q) → standing ovation (P) → event concluded (S).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 561, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. She packed her bags excitedly.\nQ. She had a wonderful time at the beach.\nR. She received a holiday gift from her company.\nS. She flew to Goa the next morning.', options: ['RPSQ', 'RPQS', 'PRQS', 'RSPQ'], answer: 'RPSQ', explanation: 'Sequence: Received gift (R) → packed bags (P) → flew to Goa (S) → wonderful time (Q).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 562, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The villagers celebrated with great joy.\nQ. A new school was inaugurated in the village.\nR. The children could now study without travelling far.\nS. The villagers had demanded a school for years.', options: ['SQRP', 'SQPR', 'QSRP', 'SPRQ'], answer: 'SQRP', explanation: 'Sequence: Demanded school (S) → school inaugurated (Q) → children could study (R) → villagers celebrated (P).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 563, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He apologised for his mistake.\nQ. He realised his error later.\nR. He spoke rudely to his colleague.\nS. His colleague forgave him.', options: ['RQPS', 'RPQS', 'QRPS', 'RQSP'], answer: 'RQPS', explanation: 'Sequence: Spoke rudely (R) → realised error (Q) → apologised (P) → was forgiven (S).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 564, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The cat leaped and caught the mouse.\nQ. It hid behind the refrigerator.\nR. A mouse entered the kitchen.\nS. The cat spotted the mouse immediately.', options: ['RSQP', 'RQSP', 'SRQP', 'RSPQ'], answer: 'RSQP', explanation: 'Sequence: Mouse entered (R) → cat spotted (S) → mouse hid (Q) → cat caught it (P).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 565, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. He finally found the treasure.\nQ. He followed the map carefully.\nR. An old pirate had drawn a treasure map.\nS. He dug at the marked spot.', options: ['RQSP', 'RQPS', 'QRSP', 'RSQP'], answer: 'RQSP', explanation: 'Adventure order: Pirate drew map (R) → followed map (Q) → dug at spot (S) → found treasure (P).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 566, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. She won the gold medal.\nQ. She trained under a famous coach.\nR. She was passionate about athletics from a young age.\nS. She represented India at the Olympics.', options: ['RQSP', 'RQPS', 'QRSP', 'RSQP'], answer: 'RQSP', explanation: 'Career progression: Passionate from youth (R) → trained under coach (Q) → represented India (S) → won gold (P).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 567, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The experiment was a great success.\nQ. He carefully mixed the chemicals.\nR. A young scientist entered the laboratory.\nS. He noted down the observations.', options: ['RQSP', 'RQPS', 'QRSP', 'RSQP'], answer: 'RQSP', explanation: 'Experiment order: Entered lab (R) → mixed chemicals (Q) → noted observations (S) → experiment succeeded (P).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 568, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. They enjoyed a bonfire on the beach.\nQ. They set up tents near the shore.\nR. A group of friends planned a camping trip.\nS. They reached the beach by evening.', options: ['RSQP', 'RSPQ', 'SRQP', 'RSQP'], answer: 'RSQP', explanation: 'Trip order: Planned trip (R) → reached beach (S) → set up tents (Q) → enjoyed bonfire (P).', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 569, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The bridge collapsed due to heavy flooding.\nQ. Relief teams were deployed immediately.\nR. Continuous rain lashed the region for a week.\nS. Many families were evacuated to safer areas.', options: ['RPQS', 'RPSQ', 'PRQS', 'RPSP'], answer: 'RPQS', explanation: 'Disaster sequence: Rain for a week (R) → bridge collapsed (P) → relief teams deployed (Q) → families evacuated (S).', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 570, qtype: 'para-jumble', question: 'Arrange in correct order:\nP. The entire nation celebrated the victory.\nQ. India won the final match convincingly.\nR. The Indian team entered the tournament as favourites.\nS. They defeated every opponent in the league stage.', options: ['RSQP', 'RSPQ', 'SQRP', 'RSQP'], answer: 'RSQP', explanation: 'Tournament narrative: Entered as favourites (R) → defeated opponents (S) → won final (Q) → nation celebrated (P).', level: 'Easy', tier: 'both', examProb: 'Hot' },

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 5 — SENTENCE REARRANGEMENT (30 questions, ids 571–600)
  // ═══════════════════════════════════════════════════════════════════════

  { id: 571, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. the book\n2. on the table\n3. I found\n4. that was kept', options: ['3142', '1342', '3124', '1234'], answer: '3142', explanation: '"I found the book that was kept on the table." Subject + Verb + Object + Relative clause + Prepositional phrase.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 572, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. very important\n2. for good health\n3. regular exercise\n4. is', options: ['3412', '1234', '3142', '2341'], answer: '3412', explanation: '"Regular exercise is very important for good health." Subject + Verb + Complement + Purpose.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 573, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. in the garden\n2. are playing\n3. the children\n4. happily', options: ['3241', '3214', '1324', '2314'], answer: '3241', explanation: '"The children are playing happily in the garden." Subject + Verb + Adverb + Place.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 574, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. the teacher\n2. with attention\n3. the students\n4. listened to', options: ['3412', '1342', '3142', '1234'], answer: '3412', explanation: '"The students listened to the teacher with attention." Subject + Verb + Object + Manner.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 575, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. at the station\n2. the train\n3. arrived late\n4. due to heavy rain', options: ['2314', '2134', '1234', '2341'], answer: '2314', explanation: '"The train arrived late at the station due to heavy rain." Subject + Verb + Place + Reason.', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 576, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. every morning\n2. my grandmother\n3. in the park\n4. takes a walk', options: ['2413', '2143', '1234', '2431'], answer: '2413', explanation: '"My grandmother takes a walk in the park every morning." Subject + Verb + Place + Time.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 577, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. has been selected\n2. for the national team\n3. the young cricketer\n4. from our village', options: ['3412', '3142', '3124', '1234'], answer: '3412', explanation: '"The young cricketer from our village has been selected for the national team." Subject + Origin + Verb + Purpose.', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 578, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. on the hill\n2. an old temple\n3. there is\n4. surrounded by trees', options: ['3214', '3241', '2134', '3124'], answer: '3214', explanation: '"There is an old temple on the hill surrounded by trees." Existential + Subject + Place + Description.', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 579, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. should be respected\n2. of every individual\n3. the fundamental rights\n4. in a democracy', options: ['3214', '3241', '2314', '3124'], answer: '3214', explanation: '"The fundamental rights of every individual should be respected in a democracy."', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 580, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. cannot be achieved\n2. without hard work\n3. in life\n4. success', options: ['4132', '4312', '1234', '4123'], answer: '4132', explanation: '"Success cannot be achieved without hard work in life." Subject + Verb + Condition + Context.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 581, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. a wonderful speech\n2. at the conference\n3. the prime minister\n4. delivered', options: ['3412', '3142', '1342', '3421'], answer: '3412', explanation: '"The prime minister delivered a wonderful speech at the conference."', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 582, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. since childhood\n2. painting\n3. she has been fond of\n4. and music', options: ['3241', '3214', '1324', '2341'], answer: '3241', explanation: '"She has been fond of painting and music since childhood."', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 583, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. to finish\n2. the project\n3. worked overtime\n4. the employees', options: ['4312', '4321', '4132', '1234'], answer: '4312', explanation: '"The employees worked overtime to finish the project." Subject + Verb + Purpose + Object.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 584, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. an interesting documentary\n2. on wildlife conservation\n3. we watched\n4. last night', options: ['3124', '3142', '3214', '1234'], answer: '3124', explanation: '"We watched an interesting documentary on wildlife conservation last night."', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 585, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. the best way\n2. to learn\n3. a new language\n4. is through practice', options: ['1234', '1243', '2134', '1324'], answer: '1234', explanation: '"The best way to learn a new language is through practice."', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 586, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. despite the heavy rain\n2. reached the office\n3. on time\n4. she', options: ['4231', '1423', '4213', '4123'], answer: '4231', explanation: '"She reached the office on time despite the heavy rain." Subject + Verb + Place + Time + Contrast.', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 587, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. will be held\n2. next month\n3. the annual sports day\n4. at the school ground', options: ['3142', '3124', '3412', '1234'], answer: '3142', explanation: '"The annual sports day will be held next month at the school ground."', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 588, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. plays a vital role\n2. in the development\n3. education\n4. of a nation', options: ['3124', '3142', '3214', '1234'], answer: '3124', explanation: '"Education plays a vital role in the development of a nation."', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 589, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. by the police\n2. was caught\n3. red-handed\n4. the smuggler', options: ['4213', '4231', '4123', '1234'], answer: '4213', explanation: '"The smuggler was caught red-handed by the police." Subject + Verb + Manner + Agent.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 590, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. to his parents\n2. the good news\n3. he immediately\n4. conveyed', options: ['3421', '3412', '3241', '3142'], answer: '3421', explanation: '"He immediately conveyed the good news to his parents."', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 591, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. with great enthusiasm\n2. the cultural programme\n3. was organised\n4. by the students', options: ['2314', '2341', '2134', '2413'], answer: '2314', explanation: '"The cultural programme was organised with great enthusiasm by the students."', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 592, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. after a long discussion\n2. the committee\n3. reached a decision\n4. finally', options: ['2431', '2413', '2143', '2341'], answer: '2431', explanation: '"The committee finally reached a decision after a long discussion."', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 593, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. are found\n2. in tropical regions\n3. many species of birds\n4. around the world', options: ['3124', '3142', '3214', '1234'], answer: '3124', explanation: '"Many species of birds are found in tropical regions around the world."', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 594, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. the old man\n2. a cup of tea\n3. asked for\n4. politely', options: ['1342', '1432', '1324', '1234'], answer: '1432', explanation: '"The old man politely asked for a cup of tea." Subject + Adverb + Verb + Object.', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 595, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. is considered\n2. the backbone of\n3. agriculture\n4. the Indian economy', options: ['3124', '3142', '3214', '3412'], answer: '3124', explanation: '"Agriculture is considered the backbone of the Indian economy."', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 596, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. before the deadline\n2. submitted the report\n3. the manager\n4. to the director', options: ['3241', '3214', '3421', '3142'], answer: '3241', explanation: '"The manager submitted the report to the director before the deadline."', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 597, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. a great scientist\n2. who contributed\n3. to the field of physics\n4. Einstein was', options: ['4123', '4132', '4213', '1234'], answer: '4123', explanation: '"Einstein was a great scientist who contributed to the field of physics."', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 598, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. not only improves health\n2. yoga\n3. but also reduces stress\n4. and increases flexibility', options: ['2134', '2143', '2314', '2413'], answer: '2134', explanation: '"Yoga not only improves health but also reduces stress and increases flexibility."', level: 'Medium', tier: 'both', examProb: 'Hot' },
  { id: 599, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. must follow\n2. the rules and regulations\n3. every citizen\n4. of the country', options: ['3124', '3142', '3214', '1234'], answer: '3124', explanation: '"Every citizen must follow the rules and regulations of the country."', level: 'Easy', tier: 'both', examProb: 'Hot' },
  { id: 600, qtype: 'sentence-rearrangement', question: 'Rearrange to form a meaningful sentence:\n1. has been growing\n2. the demand for\n3. renewable energy\n4. rapidly in recent years', options: ['2314', '2134', '2341', '2413'], answer: '2314', explanation: '"The demand for renewable energy has been growing rapidly in recent years."', level: 'Medium', tier: 'both', examProb: 'Hot' },
]
