import { MULTI_STATEMENT_OPTIONS as MULTI_STATEMENT_2_OPTIONS, ASSERTION_REASON_OPTIONS, type QuestionType } from '../../engine/types'

export type MICategory =
  | 'String Instruments (Tata)'
  | 'Wind Instruments (Sushira)'
  | 'Percussion - Membranous (Avanaddha)'
  | 'Percussion - Solid (Ghana)'
  | 'Hindustani Classical'
  | 'Carnatic Classical'
  | 'Famous Musicians & Awards'
  | 'Current Affairs & Awards'
  | 'Folk Music'

export type ExamProb = 'Hot' | 'High' | 'Confirmed' | 'Recurring'

export interface MIEntry {
  id: number
  category: MICategory
  topic: string
  questionType?: QuestionType
  question: string
  options: [string, string, string, string]
  answer: string
  shortcut?: string
  detail: string
  context: string
  examProb: ExamProb
  place?: string
  lat?: number
  lng?: number
  statements?: string[]
  assertion?: string
  reason?: string
  matchLeft?: string[]
  matchRight?: string[]
}

export interface MIPYQEntry {
  date: string
  shift: string
  question: string
  answer: string
  category: MICategory
}

// =====================================================================
// MAIN DATA — 85 entries
// =====================================================================

export const miData: MIEntry[] = [

  // ─── STRING INSTRUMENTS (TATA VADYA) ──────────────────────────────────

  {
    id: 1, category: 'String Instruments (Tata)', topic: 'Sitar',
    question: 'Who is the legendary sitarist who popularized Sitar globally and received Bharat Ratna in 1999?',
    answer: 'Pandit Ravi Shankar',
    options: ['Pandit Ravi Shankar', 'Ustad Vilayat Khan', 'Ustad Amjad Ali Khan', 'Pandit Nikhil Banerjee'],
    shortcut: 'Ravi Shankar = Sitar + Bharat Ratna 1999 + Grammy + Beatle George Harrison connection',
    detail: 'Pandit Ravi Shankar (1920-2012) was the most internationally acclaimed Indian musician. He received the Bharat Ratna in 1999, won Grammy Awards, and collaborated with George Harrison of The Beatles. Sitar is a Tata Vadya (stringed instrument) with 18-21 strings and moveable frets.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    place: 'Varanasi', lat: 25.32, lng: 82.99,
  },
  {
    id: 2, category: 'String Instruments (Tata)', topic: 'Sarod',
    question: 'Sarod is a stringed instrument famously associated with which musician?',
    answer: 'Ustad Amjad Ali Khan',
    options: ['Ustad Amjad Ali Khan', 'Pandit Ravi Shankar', 'Ustad Bismillah Khan', 'Pandit Hariprasad Chaurasia'],
    shortcut: 'Amjad Ali Khan = Sarod maestro | Padma Vibhushan | Bangash gharana',
    detail: 'Ustad Amjad Ali Khan belongs to the Bangash lineage of Sarod players. The Sarod is a fretless stringed instrument with a metal fingerboard, producing a deep, weighty sound. It evolved from the Afghan Rabab. His sons Amaan and Ayaan Ali Bangash also play Sarod.',
    context: 'SSC CGL 2020 Confirmed', examProb: 'Confirmed',
    place: 'Delhi', lat: 28.61, lng: 77.21,
  },
  {
    id: 3, category: 'String Instruments (Tata)', topic: 'Veena (Saraswati Veena)',
    question: 'The Saraswati Veena is the principal instrument of which classical music tradition?',
    answer: 'Carnatic Classical Music',
    options: ['Carnatic Classical Music', 'Hindustani Classical Music', 'Dhrupad tradition', 'Baul tradition'],
    shortcut: 'Saraswati Veena = Carnatic music | South India | Goddess Saraswati holds it',
    detail: 'The Saraswati Veena (also called simply Veena in the South) is the principal stringed instrument of Carnatic music. It has 4 main strings and 3 drone strings. The instrument is associated with Goddess Saraswati. Notable players include S. Balachander and Chitti Babu.',
    context: 'SSC CGL 2021 High', examProb: 'High',
    place: 'Chennai', lat: 13.08, lng: 80.27,
  },
  {
    id: 4, category: 'String Instruments (Tata)', topic: 'Santoor',
    question: 'The Santoor, a hammered dulcimer, is primarily associated with the music of which Indian state?',
    answer: 'Jammu & Kashmir',
    options: ['Jammu & Kashmir', 'Rajasthan', 'Gujarat', 'Himachal Pradesh'],
    shortcut: 'Santoor = Kashmir + Shivkumar Sharma = Tata Vadya (struck strings)',
    detail: 'The Santoor is a trapezoid-shaped hammered dulcimer originating from Kashmir. Pandit Shivkumar Sharma popularized it in Hindustani classical music. It has 100 strings arranged in groups of 3-4 and is played with light wooden mallets. Traditionally used in Kashmiri Sufi music (Sufiana Mausiqi).',
    context: 'SSC CGL 2022 Confirmed', examProb: 'Confirmed',
    place: 'Srinagar', lat: 34.08, lng: 74.80,
  },
  {
    id: 5, category: 'String Instruments (Tata)', topic: 'Sarangi',
    question: 'The Sarangi, a bowed string instrument, is traditionally associated with which Indian state?',
    answer: 'Rajasthan',
    options: ['Rajasthan', 'Punjab', 'Gujarat', 'Madhya Pradesh'],
    shortcut: 'Sarangi = Bowed + Rajasthan + Ram Narayan = "Instrument closest to human voice"',
    detail: 'The Sarangi is a bowed (played with a bow) stringed instrument from Rajasthan. It has 3 main strings and up to 36 sympathetic strings. Pandit Ram Narayan elevated it from folk/accompaniment to solo classical status. Called "the instrument closest to the human voice" due to its tonal quality.',
    context: 'SSC CGL 2020 High', examProb: 'High',
    place: 'Jaisalmer', lat: 26.92, lng: 70.90,
  },
  {
    id: 6, category: 'String Instruments (Tata)', topic: 'Ektara',
    question: 'Ektara, a single-stringed drone instrument, is traditionally used by which folk singer tradition of Bengal?',
    answer: 'Baul singers',
    options: ['Baul singers', 'Bhatiali singers', 'Bihu singers', 'Lavani singers'],
    shortcut: 'Ektara = 1 string + Baul singers + Bengal folk + devotional music',
    detail: 'The Ektara is a one-stringed instrument used by Baul singers of Bengal for their mystical folk songs. Made from a gourd and a bamboo stick with a single string, it produces a droning sound. Baul music is recognized by UNESCO as an Intangible Cultural Heritage.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Kolkata', lat: 22.57, lng: 88.36,
  },
  {
    id: 7, category: 'String Instruments (Tata)', topic: 'Dilruba',
    question: 'The Dilruba is a stringed instrument primarily associated with the music of which religious tradition?',
    answer: 'Sikh devotional music',
    options: ['Sikh devotional music', 'Sufi music', 'Buddhist chanting', 'Vaishnavite kirtan'],
    shortcut: 'Dilruba = Sikh Gurbani + Punjab + bowed instrument + Guru Gobind Singh era',
    detail: 'The Dilruba is a bowed stringed instrument popular in Punjab and closely associated with Sikh Gurbani (devotional) music. It combines features of the Sitar and Sarangi. Believed to have been developed during the time of Guru Gobind Singh Ji. The name means "heart-stealer".',
    context: 'SSC CGL 2021 Recurring', examProb: 'Recurring',
    place: 'Amritsar', lat: 31.63, lng: 74.87,
  },
  {
    id: 8, category: 'String Instruments (Tata)', topic: 'Mohan Veena',
    question: 'The Mohan Veena (Indian Slide Guitar) was modified and popularized by which musician?',
    answer: 'Vishwa Mohan Bhatt',
    options: ['Vishwa Mohan Bhatt', 'Brij Bhushan Kabra', 'Debashish Bhattacharya', 'Barun Kumar Pal'],
    shortcut: 'Mohan Veena = Vishwa Mohan Bhatt + Grammy 1994 (A Meeting by the River) + slide guitar',
    detail: 'Vishwa Mohan Bhatt modified the Western slide guitar into the Mohan Veena, adding sympathetic strings. He won the Grammy Award in 1994 for the album "A Meeting by the River" with Ry Cooder. The instrument blends Indian classical music with the Hawaiian slide guitar technique.',
    context: 'SSC CGL 2022 High', examProb: 'High',
    place: 'Jaipur', lat: 26.91, lng: 75.79,
  },
  {
    id: 9, category: 'String Instruments (Tata)', topic: 'Tanpura/Tambura',
    question: 'The Tanpura/Tambura is primarily used for which musical function in Indian classical music?',
    answer: 'Providing a continuous drone',
    options: ['Providing a continuous drone', 'Playing the main melody', 'Keeping rhythmic time', 'Improvising alaaps'],
    shortcut: 'Tanpura = Drone instrument + 4-5 strings + foundation of raga + no melody',
    detail: 'The Tanpura (Tambura) is a long-necked plucked drone instrument essential in Indian classical music. It provides the harmonic base (shruti) for vocalists and instrumentalists. It typically has 4-5 strings tuned to the tonic and fifth. Every classical performance begins with the Tanpura drone.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Miraj', lat: 16.82, lng: 74.65,
  },
  {
    id: 10, category: 'String Instruments (Tata)', topic: 'Rabab',
    question: 'The Rabab, from which the Sarod evolved, has origins in which region?',
    answer: 'Afghanistan/Central Asia',
    options: ['Afghanistan/Central Asia', 'South India', 'Northeast India', 'Tibet'],
    shortcut: 'Rabab = Afghanistan origin + ancestor of Sarod + Tansen played Rabab + plucked',
    detail: 'The Rabab is a plucked stringed instrument that originated in Afghanistan and Central Asia. It was introduced to India through Mughal courts. Tansen, the legendary musician in Akbar\'s court, was known to play the Rabab. The Sarod evolved from the Rabab with modifications to suit Indian classical music.',
    context: 'SSC CGL 2020 High', examProb: 'High',
    lat: 34.52, lng: 69.17,
  },
  {
    id: 11, category: 'String Instruments (Tata)', topic: 'Esraj',
    question: 'The Esraj is a bowed stringed instrument associated with which region of India?',
    answer: 'Bengal and eastern India',
    options: ['Bengal and eastern India', 'Rajasthan', 'Kashmir', 'Tamil Nadu'],
    shortcut: 'Esraj = Bengal + bowed + Rabindra Sangeet accompaniment + similar to Dilruba',
    detail: 'The Esraj is a bowed stringed instrument popular in Bengal and eastern India. It is commonly used to accompany Rabindra Sangeet (songs of Rabindranath Tagore) and devotional music. Similar to the Dilruba but slightly different in construction, with sympathetic strings.',
    context: 'SSC CGL 2021 Recurring', examProb: 'Recurring',
    place: 'Kolkata', lat: 22.57, lng: 88.36,
  },
  {
    id: 12, category: 'String Instruments (Tata)', topic: 'Gopichand',
    question: 'The Gopichand (Gopiyantra) is a folk string instrument associated with which region?',
    answer: 'Bengal',
    options: ['Bengal', 'Rajasthan', 'Kerala', 'Punjab'],
    shortcut: 'Gopichand = Bengal folk + single string + bamboo + Baul/fakir singers',
    detail: 'The Gopichand (also called Gopiyantra or Ananda Lahari) is a one-stringed folk instrument from Bengal. Made from bamboo and a gourd resonator, it is played by Baul and fakir singers. The pitch can be varied by squeezing the bamboo arms to change string tension.',
    context: 'SSC CGL 2022 Recurring', examProb: 'Recurring',
    place: 'Kolkata', lat: 22.57, lng: 88.36,
  },

  // ─── WIND INSTRUMENTS (SUSHIRA VADYA) ─────────────────────────────────

  {
    id: 13, category: 'Wind Instruments (Sushira)', topic: 'Bansuri (Bamboo Flute)',
    question: 'Which renowned flautist is most famous for elevating the Bansuri to a solo concert instrument?',
    answer: 'Pandit Hariprasad Chaurasia',
    options: ['Pandit Hariprasad Chaurasia', 'Pannalal Ghosh', 'Ronu Majumdar', 'Rakesh Chaurasia'],
    shortcut: 'Hariprasad Chaurasia = Bansuri maestro + Silsila/Chandni film music + Padma Vibhushan',
    detail: 'Pandit Hariprasad Chaurasia is the foremost Bansuri (bamboo flute) player in India. While Pannalal Ghosh first introduced the large concert flute to classical music, Chaurasia popularized it globally. The Bansuri is a Sushira Vadya (wind instrument) made from bamboo with six or seven holes. It is associated with Lord Krishna.',
    context: 'SSC CGL 2020-2024 Hot', examProb: 'Hot',
    place: 'Allahabad', lat: 25.43, lng: 81.85,
  },
  {
    id: 14, category: 'Wind Instruments (Sushira)', topic: 'Shehnai',
    question: 'Ustad Bismillah Khan, the legendary Shehnai maestro, was awarded Bharat Ratna in which year?',
    answer: '2001',
    options: ['2001', '1999', '1998', '2003'],
    shortcut: 'Bismillah Khan = Shehnai + Bharat Ratna 2001 + played at Red Fort on Independence Day 1947',
    detail: 'Ustad Bismillah Khan (1916-2006) was the greatest Shehnai player in Indian history. He received the Bharat Ratna in 2001. He played the Shehnai at the Red Fort on India\'s first Independence Day (August 15, 1947). The Shehnai is a double-reed wind instrument, classified as Sushira Vadya, traditionally played at weddings and auspicious occasions.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    place: 'Varanasi', lat: 25.32, lng: 82.99,
  },
  {
    id: 15, category: 'Wind Instruments (Sushira)', topic: 'Nadaswaram',
    question: 'The Nadaswaram is the South Indian counterpart of which North Indian instrument?',
    answer: 'Shehnai',
    options: ['Shehnai', 'Bansuri', 'Algoza', 'Been'],
    shortcut: 'Nadaswaram = South Indian Shehnai + Carnatic music + temple instrument + loudest acoustic',
    detail: 'The Nadaswaram is a double-reed wind instrument of Carnatic music, considered the South Indian equivalent of the Shehnai. It is one of the loudest non-brass acoustic instruments. Used extensively in temples and auspicious occasions in Tamil Nadu and other South Indian states. Notable players include T.N. Rajarathinam Pillai and Sheik Chinna Moulana.',
    context: 'SSC CGL 2022 Confirmed', examProb: 'Confirmed',
    place: 'Tiruchirappalli', lat: 10.79, lng: 78.70,
  },
  {
    id: 16, category: 'Wind Instruments (Sushira)', topic: 'Algoza',
    question: 'The Algoza, a pair of twin flutes, is a folk instrument of which Indian state?',
    answer: 'Rajasthan',
    options: ['Rajasthan', 'Kerala', 'Assam', 'West Bengal'],
    shortcut: 'Algoza = Twin flutes + Rajasthan + Punjab folk + one melody + one drone',
    detail: 'The Algoza consists of a pair of twin bamboo flutes played simultaneously. One flute plays the melody while the other provides a continuous drone. It is popular in Rajasthan and Punjab folk music. The player uses circular breathing (maintaining airflow without pause) to produce a continuous sound.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Jodhpur', lat: 26.24, lng: 73.02,
  },
  {
    id: 17, category: 'Wind Instruments (Sushira)', topic: 'Been/Pungi',
    question: 'The Been (Pungi), used by snake charmers, belongs to which instrument classification?',
    answer: 'Sushira Vadya (Wind)',
    options: ['Sushira Vadya (Wind)', 'Tata Vadya (String)', 'Avanaddha Vadya (Percussion)', 'Ghana Vadya (Solid)'],
    shortcut: 'Been/Pungi = Snake charmer + wind instrument + gourd + Rajasthan + Sapera community',
    detail: 'The Been (also called Pungi or Murli) is a wind instrument made from a gourd with two bamboo pipes. Traditionally used by the Sapera (snake charmer) community of Rajasthan. It is classified as Sushira Vadya. Snake charming is now banned under the Wildlife Protection Act 1972, but the instrument survives in folk performances.',
    context: 'SSC CGL 2021 Recurring', examProb: 'Recurring',
    place: 'Pushkar', lat: 26.49, lng: 74.55,
  },
  {
    id: 18, category: 'Wind Instruments (Sushira)', topic: 'Sundari',
    question: 'The Sundari is a folk wind instrument associated with which part of India?',
    answer: 'Northeast India',
    options: ['Northeast India', 'South India', 'Western India', 'North India'],
    shortcut: 'Sundari = Northeast folk flute + bamboo + tribal music + Assam/Nagaland region',
    detail: 'The Sundari is a folk wind instrument found in Northeast India, particularly among tribal communities of Assam and neighboring states. It is a type of bamboo flute used in traditional folk and ceremonial music. Northeast India has a rich tradition of bamboo-based wind instruments.',
    context: 'SSC CGL 2022 Recurring', examProb: 'Recurring',
    place: 'Guwahati', lat: 26.14, lng: 91.74,
  },

  // ─── PERCUSSION - MEMBRANOUS (AVANADDHA VADYA) ────────────────────────

  {
    id: 19, category: 'Percussion - Membranous (Avanaddha)', topic: 'Tabla',
    question: 'Which world-famous tabla player won three Grammy Awards in 2024?',
    answer: 'Ustad Zakir Hussain',
    options: ['Ustad Zakir Hussain', 'Pandit Kishan Maharaj', 'Ustad Alla Rakha', 'Pandit Anindo Chatterjee'],
    shortcut: 'Zakir Hussain = Tabla + 3 Grammys 2024 + son of Alla Rakha + Padma Shri 1988 + Padma Bhushan 2002',
    detail: 'Ustad Zakir Hussain (1951-2024) was the world\'s most famous tabla player. He won three Grammy Awards in 2024 (66th ceremony). Son of legendary tabla maestro Ustad Alla Rakha. He received Padma Shri in 1988 and Padma Bhushan in 2002. Tabla is a pair of drums (Dayan + Bayan) and is Avanaddha Vadya.',
    context: 'SSC CGL 2024-2025 Hot', examProb: 'Hot',
    place: 'Mumbai', lat: 19.08, lng: 72.88,
  },
  {
    id: 20, category: 'Percussion - Membranous (Avanaddha)', topic: 'Mridangam',
    question: 'The Mridangam is the primary percussion instrument of which classical music system?',
    answer: 'Carnatic Classical Music',
    options: ['Carnatic Classical Music', 'Hindustani Classical Music', 'Dhrupad tradition', 'Sufi Music'],
    shortcut: 'Mridangam = Carnatic percussion + barrel-shaped + two heads + Palghat Mani Iyer',
    detail: 'The Mridangam is the primary percussion instrument of Carnatic (South Indian) classical music. It is a barrel-shaped, two-headed drum made of jackwood. Notable players include Palghat Mani Iyer, Palghat Raghu, and Umayalpuram K. Sivaraman. It is classified as Avanaddha Vadya.',
    context: 'SSC CGL 2021 Confirmed', examProb: 'Confirmed',
    place: 'Chennai', lat: 13.08, lng: 80.27,
  },
  {
    id: 21, category: 'Percussion - Membranous (Avanaddha)', topic: 'Pakhawaj',
    question: 'The Pakhawaj is the traditional accompaniment for which form of Hindustani vocal music?',
    answer: 'Dhrupad',
    options: ['Dhrupad', 'Khayal', 'Thumri', 'Ghazal'],
    shortcut: 'Pakhawaj = Dhrupad accompaniment + barrel drum + oldest Hindustani percussion + deep bass',
    detail: 'The Pakhawaj is a barrel-shaped, two-headed drum and the oldest form of percussion in Hindustani classical music. It is the traditional accompaniment for Dhrupad (the oldest form of Hindustani vocal music). The Tabla eventually replaced the Pakhawaj for Khayal and lighter forms.',
    context: 'SSC CGL 2022 High', examProb: 'High',
    place: 'Delhi', lat: 28.61, lng: 77.21,
  },
  {
    id: 22, category: 'Percussion - Membranous (Avanaddha)', topic: 'Dholak',
    question: 'The Dholak is a two-headed drum primarily used in which type of music?',
    answer: 'Folk and devotional music',
    options: ['Folk and devotional music', 'Carnatic classical music', 'Hindustani classical music', 'Western orchestral music'],
    shortcut: 'Dholak = Folk drum + weddings + qawwali + Bollywood + widespread across India',
    detail: 'The Dholak is a two-headed hand drum widely used in folk, devotional, and film music across India. It is played on both sides with hands or sticks. Commonly used in qawwali, bhajan, kirtan, and Bollywood music. It is one of the most widespread percussion instruments in Indian folk traditions.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
  },
  {
    id: 23, category: 'Percussion - Membranous (Avanaddha)', topic: 'Chenda',
    question: 'The Chenda is a cylindrical drum integral to the temple festivals and art forms of which state?',
    answer: 'Kerala',
    options: ['Kerala', 'Tamil Nadu', 'Karnataka', 'Andhra Pradesh'],
    shortcut: 'Chenda = Kerala + Kathakali + temple festivals + cylindrical drum + played with sticks',
    detail: 'The Chenda is a cylindrical drum from Kerala, played with curved sticks. It is integral to Kathakali performances, temple festivals (Pooram), and other Kerala art forms like Koodiyattam. Thrissur Pooram features massive Chenda ensembles (Chenda Melam). It is classified as Avanaddha Vadya.',
    context: 'SSC CGL 2020 Confirmed', examProb: 'Confirmed',
    place: 'Thrissur', lat: 10.52, lng: 76.21,
  },
  {
    id: 24, category: 'Percussion - Membranous (Avanaddha)', topic: 'Damaru',
    question: 'The Damaru is a small two-headed drum associated with which Hindu deity?',
    answer: 'Lord Shiva (Nataraja)',
    options: ['Lord Shiva (Nataraja)', 'Lord Krishna', 'Lord Ganesha', 'Lord Vishnu'],
    shortcut: 'Damaru = Shiva/Nataraja + hourglass shape + cosmic dance + Tandava + smallest drum',
    detail: 'The Damaru is a small hourglass-shaped two-headed drum associated with Lord Shiva in his Nataraja (cosmic dancer) form. According to mythology, the sounds from Shiva\'s Damaru created the Sanskrit alphabet (Maheshwara Sutras). It is one of the oldest known musical instruments in India.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    lat: 30.73, lng: 79.07,
  },
  {
    id: 25, category: 'Percussion - Membranous (Avanaddha)', topic: 'Dhol',
    question: 'The Dhol is a large double-headed drum most prominently associated with which state?',
    answer: 'Punjab',
    options: ['Punjab', 'Tamil Nadu', 'Odisha', 'Assam'],
    shortcut: 'Dhol = Punjab + Bhangra dance + weddings + played with sticks + festival drum',
    detail: 'The Dhol is a large barrel-shaped double-headed drum played with two sticks. It is central to Bhangra dance and Punjabi celebrations. Classified as Avanaddha Vadya. The bigger face (bass) is hit with a heavy stick (dagga) and the smaller face (treble) with a thin stick (tilli).',
    context: 'SSC CGL 2022 High', examProb: 'High',
    place: 'Chandigarh', lat: 30.73, lng: 76.78,
  },
  {
    id: 26, category: 'Percussion - Membranous (Avanaddha)', topic: 'Khol',
    question: 'The Khol (Mridanga) is a clay drum used in the Kirtan music tradition of which region?',
    answer: 'Bengal (Vaishnavite tradition)',
    options: ['Bengal (Vaishnavite tradition)', 'Rajasthan (Sufi tradition)', 'Kashmir (Sufiana)', 'Punjab (Sikh Gurbani)'],
    shortcut: 'Khol = Bengal + Kirtan + Chaitanya Mahaprabhu + Vaishnavite devotional + clay body',
    detail: 'The Khol is a terracotta (clay) barrel drum used in Bengali Kirtan music and ISKCON devotional singing. It is associated with the Vaishnavite tradition popularized by Chaitanya Mahaprabhu in Bengal. It is similar in shape to the Mridangam but made of clay instead of wood.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Nabadwip', lat: 23.41, lng: 88.38,
  },
  {
    id: 27, category: 'Percussion - Membranous (Avanaddha)', topic: 'Nagara/Naqqara',
    question: 'The Nagara (Naqqara) is a pair of kettledrums traditionally associated with which type of performance?',
    answer: 'Royal courts and temple announcements',
    options: ['Royal courts and temple announcements', 'Classical vocal recitals', 'Folk dance accompaniment', 'Cinema background scores'],
    shortcut: 'Nagara/Naqqara = Kettledrums + royal courts + Rajasthan + temple entrance + played in pairs',
    detail: 'The Nagara (Naqqara) are large kettledrums played in pairs, traditionally placed at the entrance of temples, forts, and palaces. They were used for royal announcements and time-keeping in Mughal and Rajput courts. Found prominently in Rajasthan. The Naubat tradition involves ensemble playing including Naqqara.',
    context: 'SSC CGL 2021 Recurring', examProb: 'Recurring',
    place: 'Jaipur', lat: 26.91, lng: 75.79,
  },

  // ─── PERCUSSION - SOLID (GHANA VADYA) ─────────────────────────────────

  {
    id: 28, category: 'Percussion - Solid (Ghana)', topic: 'Ghatam',
    question: 'The Ghatam, a clay pot percussion instrument, is primarily used in which music system?',
    answer: 'Carnatic Classical Music',
    options: ['Carnatic Classical Music', 'Hindustani Classical Music', 'Film Music', 'Western Classical'],
    shortcut: 'Ghatam = Clay pot + Carnatic + Ghana Vadya + T.H. Vinayakram + mouth of pot technique',
    detail: 'The Ghatam is a clay pot percussion instrument used in Carnatic music. It is classified as Ghana Vadya (solid percussion). T.H. Vinayakram ("Vikku") is the most famous Ghatam player who brought it international fame through Shakti band with John McLaughlin. Played by striking with palms, fingers, and using the pot\'s mouth against the stomach.',
    context: 'SSC CGL 2022 Confirmed', examProb: 'Confirmed',
    place: 'Madurai', lat: 9.93, lng: 78.12,
  },
  {
    id: 29, category: 'Percussion - Solid (Ghana)', topic: 'Jaltarang',
    question: 'The Jaltarang produces music by striking which objects?',
    answer: 'Water-filled porcelain cups',
    options: ['Water-filled porcelain cups', 'Metal plates', 'Wooden blocks', 'Glass tubes'],
    shortcut: 'Jaltarang = Water-filled cups + Ghana Vadya + different water levels = different pitches',
    detail: 'The Jaltarang consists of a set of porcelain or ceramic cups filled with varying amounts of water. Different water levels produce different pitches when struck with light wooden sticks. It is classified as Ghana Vadya. Mentioned in Sangeet Parijat (17th century). One of the most unique instruments in Indian music.',
    context: 'SSC CGL 2020 High', examProb: 'High',
  },
  {
    id: 30, category: 'Percussion - Solid (Ghana)', topic: 'Kartal',
    question: 'Kartal (wooden clappers) is a rhythmic instrument commonly used in devotional music of which state?',
    answer: 'Rajasthan',
    options: ['Rajasthan', 'Kerala', 'Assam', 'Tamil Nadu'],
    shortcut: 'Kartal = Wooden clappers + Rajasthan + bhajan + kirtan + Ghana Vadya',
    detail: 'Kartal are pairs of wooden clappers or castanets used in devotional music, especially in Rajasthan. Made from teak wood with brass jingles embedded. Used extensively in bhajan and kirtan singing. The name comes from "kar" (hand) and "taal" (rhythm). Classified as Ghana Vadya.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Ajmer', lat: 26.45, lng: 74.64,
  },
  {
    id: 31, category: 'Percussion - Solid (Ghana)', topic: 'Chimta',
    question: 'The Chimta (fire tongs with jingles) is a percussion instrument from which state?',
    answer: 'Punjab',
    options: ['Punjab', 'Karnataka', 'Odisha', 'Meghalaya'],
    shortcut: 'Chimta = Punjab + fire tongs + jingles/bells + Sufi music + Bhangra',
    detail: 'The Chimta is a pair of long metal tongs with small brass jingles or bells. Originating from Punjab, it is used in Sufi music, Bhangra, and folk performances. The player strikes the two arms together rhythmically, producing a jingling sound. Classified as Ghana Vadya (solid idiophone).',
    context: 'SSC CGL 2022 Recurring', examProb: 'Recurring',
    place: 'Chandigarh', lat: 30.73, lng: 76.78,
  },
  {
    id: 32, category: 'Percussion - Solid (Ghana)', topic: 'Manjira/Jhanj',
    question: 'Manjira (also called Jhanj) are a pair of small metallic objects used as what?',
    answer: 'Cymbals for devotional music',
    options: ['Cymbals for devotional music', 'Gongs for temple rituals', 'Bells for dance', 'Trumpets for processions'],
    shortcut: 'Manjira = Small cymbals + bhajan/kirtan + brass/bronze + Ghana Vadya + widespread',
    detail: 'Manjira (Jhanj, Taal) are small metallic cymbals made of brass or bronze. They are among the most common percussion instruments in Indian devotional music. Used in bhajans, kirtans, and aartis across India. Classified as Ghana Vadya. They come in various sizes producing different pitches.',
    context: 'SSC CGL 2021 Recurring', examProb: 'Recurring',
  },
  {
    id: 33, category: 'Percussion - Solid (Ghana)', topic: 'Kanjira',
    question: 'The Kanjira is a frame drum used in which classical music tradition?',
    answer: 'Carnatic Classical Music',
    options: ['Carnatic Classical Music', 'Hindustani Classical Music', 'Western Rock', 'Jazz'],
    shortcut: 'Kanjira = Frame drum + Carnatic + lizard skin membrane + South India + G. Harishankar',
    detail: 'The Kanjira is a small frame drum used in Carnatic music, made with a lizard skin membrane. It was introduced to classical music by Manpoondia Pillai. Notable players include G. Harishankar. Though it is technically membranous, it is sometimes grouped with Ghana Vadya due to its small frame construction. Popular in South Indian percussion ensembles (thani avarthanam).',
    context: 'SSC CGL 2023 High', examProb: 'High',
    place: 'Chennai', lat: 13.08, lng: 80.27,
  },
  {
    id: 34, category: 'Percussion - Solid (Ghana)', topic: 'Noot',
    question: 'The Noot is a tribal percussion instrument found in which part of India?',
    answer: 'Northeast India',
    options: ['Northeast India', 'Western India', 'Central India', 'Southern India'],
    shortcut: 'Noot = Northeast tribal + clay pot type + Manipur/Nagaland + Ghana Vadya',
    detail: 'The Noot is a traditional tribal percussion instrument found among communities in Northeast India, particularly in Manipur and Nagaland. Various tribal communities in the region have unique percussion instruments made from local materials like bamboo, clay, and wood.',
    context: 'SSC CGL 2022 Recurring', examProb: 'Recurring',
    place: 'Imphal', lat: 24.82, lng: 93.95,
  },

  // ─── HINDUSTANI CLASSICAL MUSIC ───────────────────────────────────────

  {
    id: 35, category: 'Hindustani Classical', topic: 'Tansen',
    question: 'Tansen, one of the greatest musicians in Indian history, was a court musician of which Mughal Emperor?',
    answer: 'Akbar',
    options: ['Akbar', 'Shah Jahan', 'Jahangir', 'Humayun'],
    shortcut: 'Tansen = Akbar\'s court + Navaratna + Raga Deepak (fire) + Raga Megh Malhar (rain)',
    detail: 'Tansen (Miyan Tansen, c. 1500-1586) was one of the Navaratnas (nine gems) in Emperor Akbar\'s court. He is regarded as the greatest musician in Hindustani classical music. Legends say he could light lamps with Raga Deepak and bring rain with Raga Megh Malhar. He was trained by Swami Haridas. The Gwalior music festival (Tansen Samaroh) is held in his honor.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    place: 'Gwalior', lat: 26.22, lng: 78.18,
  },
  {
    id: 36, category: 'Hindustani Classical', topic: 'Amir Khusrau',
    question: 'Amir Khusrau is traditionally credited with the invention of which musical forms?',
    answer: 'Sitar, Tabla, Qawwali, and Khayal',
    options: ['Sitar, Tabla, Qawwali, and Khayal', 'Veena, Mridangam, and Dhrupad', 'Sarod, Pakhawaj, and Thumri', 'Santoor, Shehnai, and Ghazal'],
    shortcut: 'Amir Khusrau = Sitar + Tabla + Qawwali + Khayal inventor (tradition) + "Parrot of India"',
    detail: 'Amir Khusrau (1253-1325) was a Sufi poet and musician in the Delhi Sultanate. He is traditionally credited with inventing the Sitar, Tabla, and introducing Qawwali and Khayal forms. Called "Tuti-e-Hind" (Parrot of India). He was a disciple of Sufi saint Nizamuddin Auliya. He fused Persian and Indian musical traditions. Historical attribution is debated by scholars.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    place: 'Delhi', lat: 28.61, lng: 77.21,
  },
  {
    id: 37, category: 'Hindustani Classical', topic: 'Gharana System',
    question: 'Which is the oldest Gharana (school) of Hindustani classical music?',
    answer: 'Gwalior Gharana',
    options: ['Gwalior Gharana', 'Agra Gharana', 'Kirana Gharana', 'Jaipur-Atrauli Gharana'],
    shortcut: 'Gwalior Gharana = Oldest + founded by Nath Pir Baksh + Man Singh Tomar patronage + khayal singing',
    detail: 'The Gwalior Gharana is considered the oldest and most fundamental school of Hindustani classical vocal music. It was patronized by Raja Man Singh Tomar of Gwalior (15th century). Key features: open voice production, balanced approach to raga and taal, khayal singing. Notable exponents include Vishnu Digambar Paluskar and Veena Sahasrabuddhe.',
    context: 'SSC CGL 2021-2024 Hot', examProb: 'Hot',
    place: 'Gwalior', lat: 26.22, lng: 78.18,
  },
  {
    id: 38, category: 'Hindustani Classical', topic: 'Dhrupad',
    question: 'Dhrupad is the oldest surviving form of Hindustani classical vocal music. Which family is most famous for preserving it?',
    answer: 'Dagar family (Dagar Gharana)',
    options: ['Dagar family (Dagar Gharana)', 'Khan family (Agra Gharana)', 'Mishra family (Banaras Gharana)', 'Hussain family (Lucknow Gharana)'],
    shortcut: 'Dhrupad = Oldest vocal form + Dagar family (19 generations) + serious/austere + Pakhawaj accompaniment',
    detail: 'Dhrupad is the oldest form of Hindustani classical vocal music, originating from Vedic chanting. The Dagar family has preserved this tradition for about 19 generations. Dhrupad is characterised by austere, meditative alap without fast taan patterns. It uses Pakhawaj (not Tabla) as rhythmic accompaniment. The four styles (vanis) are Dagarvani, Khandarvani, Naubharvani, and Gaubharvani.',
    context: 'SSC CGL 2022 Confirmed', examProb: 'Confirmed',
    place: 'Jaipur', lat: 26.91, lng: 75.79,
  },
  {
    id: 39, category: 'Hindustani Classical', topic: 'Khayal',
    question: 'Which vocal form is the most widely performed in Hindustani classical music today?',
    answer: 'Khayal',
    options: ['Khayal', 'Dhrupad', 'Thumri', 'Tarana'],
    shortcut: 'Khayal = Most popular Hindustani vocal + "imagination" (Arabic) + Amir Khusrau credited + Bada + Chhota',
    detail: 'Khayal is the most popular and widely performed form of Hindustani classical vocal music. The word comes from Arabic meaning "imagination." It allows more creative freedom than Dhrupad, with elaborate taan (fast melodic patterns). It has two parts: Bada Khayal (slow) and Chhota Khayal (fast). Accompanied by Tabla, Harmonium, and Tanpura.',
    context: 'SSC CGL 2020 High', examProb: 'High',
  },
  {
    id: 40, category: 'Hindustani Classical', topic: 'Qawwali',
    question: 'Qawwali is a form of Sufi devotional music. Which famous Qawwali singer was known as "Shahenshah-e-Qawwali"?',
    answer: 'Nusrat Fateh Ali Khan',
    options: ['Nusrat Fateh Ali Khan', 'Sabri Brothers', 'Abida Parveen', 'Aziz Mian'],
    shortcut: 'Nusrat Fateh Ali Khan = "King of Qawwali" + Pakistani + global fame + Amir Khusrau invented form',
    detail: 'Nusrat Fateh Ali Khan (1948-1997) was called "Shahenshah-e-Qawwali" (King of Qawwali). Although Pakistani, he brought Qawwali to global audiences. Qawwali originated from the Chishti Sufi order, traditionally credited to Amir Khusrau. It features group singing with clapping and harmonium. In India, the Sabri Brothers and Javed Ali are notable Qawwali performers.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
  },
  {
    id: 41, category: 'Hindustani Classical', topic: 'Raga System',
    question: 'In Hindustani classical music, what is the minimum number of notes (swaras) required to form a Raga?',
    answer: 'Five (Audav raga)',
    options: ['Five (Audav raga)', 'Three', 'Seven (Sampurna raga)', 'Four'],
    shortcut: 'Raga = Min 5 notes (Audav) | 6 notes = Shadav | 7 notes = Sampurna | Must have Sa',
    detail: 'A Raga must have a minimum of 5 notes (Audav raga). Ragas with 6 notes are called Shadav and those with all 7 notes are Sampurna. The note Sa (shadja) is mandatory in every raga. Ragas are classified by time of performance (morning/evening/night) and mood (rasa). The raga concept is central to both Hindustani and Carnatic systems.',
    context: 'SSC CGL 2022 High', examProb: 'High',
  },
  {
    id: 42, category: 'Hindustani Classical', topic: 'Thumri',
    question: 'Thumri is a light classical vocal form of Hindustani music associated with which city?',
    answer: 'Lucknow',
    options: ['Lucknow', 'Delhi', 'Kolkata', 'Pune'],
    shortcut: 'Thumri = Lucknow + light classical + romantic/devotional + Nawabi culture + Girija Devi',
    detail: 'Thumri is a semi-classical vocal form that originated in the Nawabi culture of Lucknow and Varanasi. It emphasizes emotional expression (bhav) over technical rigour. Themes are usually romantic or devotional (often Krishna-related). Notable Thumri singers include Girija Devi ("Thumri Queen"), Begum Akhtar, and Siddheshwari Devi.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Lucknow', lat: 26.85, lng: 80.95,
  },
  {
    id: 43, category: 'Hindustani Classical', topic: 'Swami Haridas',
    question: 'Swami Haridas, the guru of Tansen, is associated with which place?',
    answer: 'Vrindavan',
    options: ['Vrindavan', 'Mathura', 'Gwalior', 'Agra'],
    shortcut: 'Swami Haridas = Guru of Tansen + Vrindavan + devotional singer + Vishnupad tradition',
    detail: 'Swami Haridas (c. 1480-1575) was a classical musician and poet-saint based in Vrindavan. He is best known as the guru of Tansen. He composed devotional songs in the Vishnupad style dedicated to Lord Krishna. The Swami Haridas Sangeet Samaroh is an annual music festival held in his memory in Vrindavan.',
    context: 'SSC CGL 2020 High', examProb: 'High',
    place: 'Vrindavan', lat: 27.58, lng: 77.70,
  },

  // ─── CARNATIC CLASSICAL MUSIC ─────────────────────────────────────────

  {
    id: 44, category: 'Carnatic Classical', topic: 'Carnatic Trinity',
    question: 'Who are the three composers known as the "Trinity of Carnatic Music"?',
    answer: 'Tyagaraja, Muthuswami Dikshitar, Syama Sastri',
    options: ['Tyagaraja, Muthuswami Dikshitar, Syama Sastri', 'Purandara Dasa, Kanakadasa, Tyagaraja', 'M.S. Subbulakshmi, D.K. Pattammal, M.L. Vasanthakumari', 'Annamacharya, Bhadrachala Ramadasu, Kshetrayya'],
    shortcut: 'Carnatic Trinity = Tyagaraja + Dikshitar + Syama Sastri | All from Tiruvarur | 18th-19th century',
    detail: 'The Trinity of Carnatic Music comprises Tyagaraja (1767-1847), Muthuswami Dikshitar (1775-1835), and Syama Sastri (1762-1827). All three were born in Tiruvarur, Tamil Nadu, and were contemporaries. Tyagaraja composed Pancharatna Kritis; Dikshitar composed in Sanskrit; Syama Sastri was known for swarajati compositions. They defined the Carnatic kriti form.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    place: 'Tiruvarur', lat: 10.77, lng: 79.64,
  },
  {
    id: 45, category: 'Carnatic Classical', topic: 'Purandara Dasa',
    question: 'Who is known as the "Pitamaha (Father) of Carnatic Music"?',
    answer: 'Purandara Dasa',
    options: ['Purandara Dasa', 'Tyagaraja', 'Muthuswami Dikshitar', 'Annamacharya'],
    shortcut: 'Purandara Dasa = "Father of Carnatic Music" + systematized teaching + 16th century + Karnataka',
    detail: 'Purandara Dasa (1484-1564) is called the "Pitamaha" (Father/Grandfather) of Carnatic music. He systematized the method of teaching Carnatic music by creating graded lessons (sarali varisai, janta varisai, etc.). Born in Karnataka, he was originally a wealthy merchant named Srinivasa Nayaka who renounced wealth for devotion. He composed lakhs of songs in Kannada and Sanskrit.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    place: 'Hampi', lat: 15.34, lng: 76.46,
  },
  {
    id: 46, category: 'Carnatic Classical', topic: '72 Melakarta Raga System',
    question: 'How many Melakarta (parent) ragas are there in the Carnatic music system?',
    answer: '72',
    options: ['72', '64', '36', '108'],
    shortcut: '72 Melakarta = Parent ragas of Carnatic | Venkatamakhi systematized | Each has all 7 swaras',
    detail: 'The Carnatic system has 72 Melakarta (parent/janaka) ragas, systematized by Venkatamakhi in the 17th century. Each Melakarta raga has all 7 swaras (notes) in both ascending and descending scales. All other ragas (janya ragas) are derived from these 72 parent ragas. This systematic classification is a unique feature of Carnatic music.',
    context: 'SSC CGL 2021 Confirmed', examProb: 'Confirmed',
  },
  {
    id: 47, category: 'Carnatic Classical', topic: 'M.S. Subbulakshmi',
    question: 'M.S. Subbulakshmi, the first musician to receive the Bharat Ratna, got the award in which year?',
    answer: '1998',
    options: ['1998', '1999', '2001', '1997'],
    shortcut: 'M.S. Subbulakshmi = Bharat Ratna 1998 + FIRST musician + Carnatic vocalist + UN concert 1966',
    detail: 'M.S. Subbulakshmi (1916-2004) was the first musician to receive the Bharat Ratna (1998). She was a legendary Carnatic vocalist known for her rendition of "Suprabhatam" and "Kurai Onrum Illai." She performed at the United Nations General Assembly in 1966. Also received Padma Bhushan (1954), Padma Vibhushan (1975), Ramon Magsaysay Award (1974).',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    place: 'Madurai', lat: 9.93, lng: 78.12,
  },
  {
    id: 48, category: 'Carnatic Classical', topic: 'Annamacharya',
    question: 'Annamacharya, who composed thousands of kirtanas to Lord Venkateswara, is from which state?',
    answer: 'Andhra Pradesh',
    options: ['Andhra Pradesh', 'Tamil Nadu', 'Karnataka', 'Kerala'],
    shortcut: 'Annamacharya = Andhra Pradesh + Tirumala/Tirupati + 32,000 kirtanas + 15th century + "Pada Kavita Pitamaha"',
    detail: 'Annamacharya (Tallapaka Annamacharya, 1408-1503) was a Telugu saint-composer from Andhra Pradesh who composed about 32,000 sankirtanas (devotional songs) dedicated to Lord Venkateswara of Tirupati. Known as "Pada Kavita Pitamaha" (Grandfather of Telugu Song). Only about 12,000 of his compositions survive, inscribed on copper plates at Tirumala.',
    context: 'SSC CGL 2022 High', examProb: 'High',
    place: 'Tirupati', lat: 13.63, lng: 79.42,
  },

  // ─── FAMOUS MUSICIANS & AWARDS ────────────────────────────────────────

  {
    id: 49, category: 'Famous Musicians & Awards', topic: 'Lata Mangeshkar',
    question: 'Lata Mangeshkar, the "Nightingale of India," received the Bharat Ratna in which year?',
    answer: '2001',
    options: ['2001', '1999', '1998', '2003'],
    shortcut: 'Lata Mangeshkar = Bharat Ratna 2001 + "Nightingale of India" + playback legend + 36 languages',
    detail: 'Lata Mangeshkar (1929-2022) was one of the most celebrated playback singers in Indian cinema. She received the Bharat Ratna in 2001. Known as the "Nightingale of India" and "Queen of Melody," she recorded songs in over 36 languages. Also received Padma Bhushan (1969), Padma Vibhushan (1999), Dadasaheb Phalke Award (1989).',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
    place: 'Indore', lat: 22.72, lng: 75.86,
  },
  {
    id: 50, category: 'Famous Musicians & Awards', topic: 'A.R. Rahman',
    question: 'A.R. Rahman won the Academy Award (Oscar) for which film?',
    answer: 'Slumdog Millionaire (2009)',
    options: ['Slumdog Millionaire (2009)', 'Lagaan (2001)', 'Roja (1992)', 'Bombay (1995)'],
    shortcut: 'A.R. Rahman = 2 Oscars (Slumdog) + 2 Grammys + Padma Bhushan + "Mozart of Madras"',
    detail: 'A.R. Rahman won two Academy Awards in 2009 for Slumdog Millionaire (Best Original Score and Best Original Song "Jai Ho"). Also called "Mozart of Madras," he has won 2 Grammy Awards, BAFTA, Golden Globe, and National Film Awards. He received Padma Bhushan (2010). His real name is A.S. Dileep Kumar.',
    context: 'SSC CGL 2020-2024 Hot', examProb: 'Hot',
    place: 'Chennai', lat: 13.08, lng: 80.27,
  },
  {
    id: 51, category: 'Famous Musicians & Awards', topic: 'Bharat Ratna in Music',
    question: 'Which of the following musicians received the Bharat Ratna FIRST?',
    answer: 'M.S. Subbulakshmi (1998)',
    options: ['M.S. Subbulakshmi (1998)', 'Bismillah Khan (2001)', 'Ravi Shankar (1999)', 'Lata Mangeshkar (2001)'],
    shortcut: 'Bharat Ratna order: M.S. Subbulakshmi 1998 > Ravi Shankar 1999 > Bismillah Khan + Lata 2001',
    detail: 'Order of Bharat Ratna to musicians: M.S. Subbulakshmi (1998, first musician), Pandit Ravi Shankar (1999), Ustad Bismillah Khan (2001), Lata Mangeshkar (2001). Subbulakshmi was the first musician and first woman from the performing arts to receive Bharat Ratna.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
  },
  {
    id: 52, category: 'Famous Musicians & Awards', topic: 'Pandit Bhimsen Joshi',
    question: 'Pandit Bhimsen Joshi, a Hindustani classical vocalist of the Kirana Gharana, received the Bharat Ratna in which year?',
    answer: '2009',
    options: ['2009', '2008', '2001', '2005'],
    shortcut: 'Bhimsen Joshi = Bharat Ratna 2009 + Kirana Gharana + Abhang singing + "Mile Sur Mera Tumhara"',
    detail: 'Pandit Bhimsen Joshi (1922-2011) was a legendary vocalist of the Kirana Gharana. He received the Bharat Ratna in 2009. Known for his Khayal and Abhang singing, he also featured in the iconic doordarshan song "Mile Sur Mera Tumhara." He received Padma Shri (1972), Padma Bhushan (1985), Padma Vibhushan (1999).',
    context: 'SSC CGL 2020 Confirmed', examProb: 'Confirmed',
    place: 'Dharwad', lat: 15.46, lng: 75.01,
  },
  {
    id: 53, category: 'Famous Musicians & Awards', topic: 'Pt. Jasraj',
    question: 'Pandit Jasraj was a renowned vocalist belonging to which Gharana?',
    answer: 'Mewati Gharana',
    options: ['Mewati Gharana', 'Kirana Gharana', 'Gwalior Gharana', 'Agra Gharana'],
    shortcut: 'Pandit Jasraj = Mewati Gharana + Haveli Sangeet + devotional + Padma Vibhushan 2000',
    detail: 'Pandit Jasraj (1930-2020) was a legendary Hindustani classical vocalist of the Mewati Gharana. He was known for devotional singing (Haveli Sangeet) and created the Jasrangi style of jugalbandi. He received Padma Shri (1975), Padma Bhushan (1990), and Padma Vibhushan (2000). A minor planet (asteroid) was named "Panditjasraj" (2006) in his honor.',
    context: 'SSC CGL 2021 High', examProb: 'High',
  },
  {
    id: 54, category: 'Famous Musicians & Awards', topic: 'Bade Ghulam Ali Khan',
    question: 'Ustad Bade Ghulam Ali Khan was a legendary vocalist of which Gharana?',
    answer: 'Patiala Gharana',
    options: ['Patiala Gharana', 'Gwalior Gharana', 'Agra Gharana', 'Rampur-Sahaswan Gharana'],
    shortcut: 'Bade Ghulam Ali Khan = Patiala Gharana + Khayal + taan mastery + "Voice of the century"',
    detail: 'Ustad Bade Ghulam Ali Khan (1902-1968) was one of the greatest Khayal singers of the Patiala Gharana. Known for his powerful voice and extraordinary taan execution. He received Padma Bhushan in 1962. The Patiala Gharana is known for its emphasis on voice culture, fast taans, and emotional depth.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Patiala', lat: 30.34, lng: 76.39,
  },

  // ─── CURRENT AFFAIRS & AWARDS ─────────────────────────────────────────

  {
    id: 55, category: 'Current Affairs & Awards', topic: 'Zakir Hussain Grammy 2024',
    question: 'How many Grammy Awards did Ustad Zakir Hussain win at the 66th Grammy Awards (2024)?',
    answer: 'Three',
    options: ['Three', 'Two', 'One', 'Four'],
    shortcut: 'Zakir Hussain = 3 Grammys 2024 + Pashto + As We Speak + Best Global Music Album + died Dec 2024',
    detail: 'Ustad Zakir Hussain won 3 Grammy Awards at the 66th ceremony in February 2024. He won Best Global Music Album (This Moment), Best Global Music Performance (Pashto), and Best Contemporary Instrumental Album (As We Speak). He passed away in December 2024 in San Francisco.',
    context: 'SSC CGL 2025-2026 Hot', examProb: 'Hot',
  },
  {
    id: 56, category: 'Current Affairs & Awards', topic: 'Sankirtana UNESCO',
    question: 'Sankirtana of Manipur was inscribed in UNESCO\'s Intangible Cultural Heritage list in which year?',
    answer: '2013',
    options: ['2013', '2010', '2015', '2018'],
    shortcut: 'Sankirtana = Manipur + UNESCO ICH 2013 + Vaishnavite ritual singing + pung + cymbals',
    detail: 'Sankirtana is a ritual singing, drumming, and dancing art form of Manipur, inscribed on UNESCO\'s Representative List of the Intangible Cultural Heritage of Humanity in 2013. It involves devotional performances related to Krishna. The Pung (Manipuri drum) and cymbals are integral instruments. Performed in temples and homes in Manipur.',
    context: 'SSC CGL 2022 Confirmed', examProb: 'Confirmed',
    place: 'Imphal', lat: 24.82, lng: 93.95,
  },
  {
    id: 57, category: 'Current Affairs & Awards', topic: 'SaMaPa Award',
    question: 'The SaMaPa (Saptak Music and Performing Arts) Vitasta Award is given in which field?',
    answer: 'Indian classical music',
    options: ['Indian classical music', 'Western classical music', 'Film music', 'Folk dance'],
    shortcut: 'SaMaPa = Saptak Music & Performing Arts + lifetime achievement + classical musicians',
    detail: 'SaMaPa (formerly known as Sur Singar Samsad) awards are prestigious honors given to outstanding Indian classical musicians. The awards recognize lifetime achievements in vocal music, instrumental music, and dance. Recent recipients include notable Hindustani and Carnatic musicians.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
  },
  {
    id: 58, category: 'Current Affairs & Awards', topic: 'Padma Awards Musicians 2024',
    question: 'Which of the following is true about the Padma Awards given to musicians in recent years (2023-2025)?',
    answer: 'Zakir Hussain received Padma Vibhushan (2023)',
    options: ['Zakir Hussain received Padma Vibhushan (2023)', 'A.R. Rahman received Padma Vibhushan (2024)', 'Shankar Mahadevan received Bharat Ratna (2024)', 'Lata Mangeshkar received Padma Vibhushan (2024)'],
    shortcut: 'Padma Vibhushan 2023 musicians: Zakir Hussain + S.M. Krishna | Padma Bhushan list growing',
    detail: 'Ustad Zakir Hussain was honored with the Padma Vibhushan in 2023. Recent Padma awardees in music include musicians across classical, folk, and contemporary genres. The Padma awards (Padma Shri, Padma Bhushan, Padma Vibhushan) are India\'s highest civilian honors after the Bharat Ratna, given annually on Republic Day.',
    context: 'SSC CGL 2024-2025 High', examProb: 'High',
  },
  {
    id: 59, category: 'Current Affairs & Awards', topic: 'National Film Award Music',
    question: 'The National Film Award for Best Music Direction is given by which body?',
    answer: 'Directorate of Film Festivals (Govt of India)',
    options: ['Directorate of Film Festivals (Govt of India)', 'CBFC', 'NFAI', 'Sangeet Natak Akademi'],
    shortcut: 'National Film Awards = DFF + Govt of India + annual + Best Music Director + Best Playback Singer',
    detail: 'National Film Awards are given by the Directorate of Film Festivals under the Ministry of Information and Broadcasting. Categories include Best Music Direction, Best Background Score, and Best Male/Female Playback Singer. These are the most prestigious film awards in India, decided by a jury of experts.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
  },
  {
    id: 60, category: 'Current Affairs & Awards', topic: 'Sangeet Natak Akademi',
    question: 'The Sangeet Natak Akademi is India\'s national academy for which fields?',
    answer: 'Music, Dance, and Drama',
    options: ['Music, Dance, and Drama', 'Music and Literature', 'Dance and Visual Arts', 'Music and Film'],
    shortcut: 'Sangeet Natak Akademi = 1952 + Music/Dance/Drama + Fellowship (highest honour) + annual awards',
    detail: 'The Sangeet Natak Akademi was established in 1952 as India\'s national academy for Music, Dance, and Drama. It confers the Sangeet Natak Akademi Award (Akademi Puraskar) and Sangeet Natak Akademi Fellowship (Akademi Ratna), the latter being the highest honour. Based in New Delhi, it functions under the Ministry of Culture.',
    context: 'SSC CGL 2020 Confirmed', examProb: 'Confirmed',
  },

  // ─── SSC FORMAT QUESTIONS ─────────────────────────────────────────────

  {
    id: 61, category: 'String Instruments (Tata)', topic: 'Instrument Classification',
    questionType: 'multi-statement',
    question: 'Consider the following statements about Indian instrument classification (Natyashastra by Bharata Muni):',
    statements: [
      'Tata Vadya refers to stringed instruments.',
      'Ghana Vadya refers to wind instruments.',
    ],
    options: [...MULTI_STATEMENT_2_OPTIONS],
    answer: 'Only Statement 1 is correct',
    detail: 'Tata Vadya = stringed instruments (correct). Ghana Vadya = solid percussion instruments like cymbals, ghatam (Statement 2 is incorrect; Sushira Vadya refers to wind instruments). The four categories in Natyashastra: Tata (string), Sushira (wind), Avanaddha (membrane percussion), Ghana (solid percussion).',
    context: 'SSC CGL Format', examProb: 'Hot',
  },
  {
    id: 62, category: 'Hindustani Classical', topic: 'Gharana Identification',
    questionType: 'match-following',
    question: 'Match the Gharana with its principal city:',
    matchLeft: ['1. Kirana Gharana', '2. Patiala Gharana', '3. Jaipur-Atrauli Gharana', '4. Gwalior Gharana'],
    matchRight: ['A. Dharwad/Kirana (Karnataka)', 'B. Patiala (Punjab)', 'C. Jaipur (Rajasthan)', 'D. Gwalior (MP)'],
    options: ['1-A, 2-B, 3-C, 4-D', '1-B, 2-A, 3-D, 4-C', '1-C, 2-D, 3-A, 4-B', '1-D, 2-C, 3-B, 4-A'],
    answer: '1-A, 2-B, 3-C, 4-D',
    detail: 'Kirana Gharana from Kirana, Karnataka (later Dharwad). Patiala Gharana from Patiala, Punjab. Jaipur-Atrauli Gharana from Jaipur/Atrauli. Gwalior Gharana from Gwalior, MP (oldest gharana).',
    context: 'SSC CGL Format', examProb: 'Hot',
  },
  {
    id: 63, category: 'Carnatic Classical', topic: 'Carnatic Trinity',
    questionType: 'assertion-reason',
    question: 'Read the Assertion (A) and Reason (R):',
    assertion: 'Tyagaraja, Muthuswami Dikshitar, and Syama Sastri are called the "Trinity of Carnatic Music."',
    reason: 'All three were contemporaries born in Tiruvarur, Tamil Nadu, and made foundational contributions to the Carnatic kriti form.',
    options: [...ASSERTION_REASON_OPTIONS],
    answer: 'Both A and R are true, and R is the correct explanation of A',
    detail: 'Both the assertion and reason are true. The three composers lived in the same era (late 18th-early 19th century), were all born in Tiruvarur, and collectively defined the Carnatic kriti (compositional) form, which is why they are called the Trinity.',
    context: 'SSC CGL Format', examProb: 'Hot',
  },
  {
    id: 64, category: 'Percussion - Membranous (Avanaddha)', topic: 'Instrument-Region Match',
    questionType: 'match-following',
    question: 'Match the percussion instrument with its primary region:',
    matchLeft: ['1. Chenda', '2. Dhol', '3. Khol', '4. Tabla'],
    matchRight: ['A. Kerala', 'B. Punjab', 'C. Bengal', 'D. North India (widespread)'],
    options: ['1-A, 2-B, 3-C, 4-D', '1-B, 2-A, 3-D, 4-C', '1-C, 2-D, 3-A, 4-B', '1-D, 2-C, 3-B, 4-A'],
    answer: '1-A, 2-B, 3-C, 4-D',
    detail: 'Chenda = Kerala (temple festivals, Kathakali). Dhol = Punjab (Bhangra). Khol = Bengal (Vaishnavite kirtan). Tabla = widespread across North India.',
    context: 'SSC CGL Format', examProb: 'High',
  },
  {
    id: 65, category: 'Famous Musicians & Awards', topic: 'Bharat Ratna Sequence',
    questionType: 'sequence',
    question: 'Arrange the following musicians in the order they received the Bharat Ratna:',
    statements: [
      'Bismillah Khan',
      'M.S. Subbulakshmi',
      'Bhimsen Joshi',
      'Ravi Shankar',
    ],
    options: ['2, 4, 1, 3', '1, 2, 4, 3', '4, 2, 1, 3', '2, 1, 4, 3'],
    answer: '2, 4, 1, 3',
    detail: 'Correct chronological order: M.S. Subbulakshmi (1998), Ravi Shankar (1999), Bismillah Khan (2001), Bhimsen Joshi (2009).',
    context: 'SSC CGL Format', examProb: 'Hot',
  },
  {
    id: 66, category: 'Wind Instruments (Sushira)', topic: 'Shehnai Classification',
    questionType: 'assertion-reason',
    question: 'Read the Assertion (A) and Reason (R):',
    assertion: 'Shehnai is classified as Sushira Vadya.',
    reason: 'Sushira Vadya includes instruments that produce sound through the vibration of air in a hollow column.',
    options: [...ASSERTION_REASON_OPTIONS],
    answer: 'Both A and R are true, and R is the correct explanation of A',
    detail: 'Shehnai is indeed a Sushira Vadya (wind instrument) because it produces sound by blowing air through a double reed, which vibrates a column of air. Sushira literally means "hollow" in Sanskrit.',
    context: 'SSC CGL Format', examProb: 'Confirmed',
  },
  {
    id: 67, category: 'Percussion - Solid (Ghana)', topic: 'Ghana Vadya Classification',
    questionType: 'multi-statement',
    question: 'Consider the following statements about Ghana Vadya:',
    statements: [
      'Ghana Vadya instruments produce sound through vibration of their solid body without the need for strings, membranes, or air columns.',
      'Tabla is an example of Ghana Vadya.',
    ],
    options: [...MULTI_STATEMENT_2_OPTIONS],
    answer: 'Only Statement 1 is correct',
    detail: 'Statement 1 is correct: Ghana Vadya (idiophones) produce sound from their solid body. Statement 2 is incorrect: Tabla is Avanaddha Vadya (membranophone), not Ghana Vadya. Examples of Ghana Vadya include Ghatam, Jaltarang, Kartal, Chimta, and Manjira.',
    context: 'SSC CGL Format', examProb: 'High',
  },
  {
    id: 68, category: 'Hindustani Classical', topic: 'Amir Khusrau Contributions',
    questionType: 'multi-statement',
    question: 'Consider the following statements about Amir Khusrau:',
    statements: [
      'He is traditionally credited with introducing Qawwali and Khayal forms.',
      'He was a disciple of Sufi saint Nizamuddin Auliya.',
    ],
    options: [...MULTI_STATEMENT_2_OPTIONS],
    answer: 'Both Statement 1 and Statement 2 are correct',
    detail: 'Both statements are correct. Amir Khusrau (1253-1325) is traditionally credited with inventing Sitar, Tabla, Qawwali, and Khayal (Statement 1). He was a devoted disciple of Hazrat Nizamuddin Auliya, the famous Chishti Sufi saint (Statement 2). He is called "Tuti-e-Hind" (Parrot of India).',
    context: 'SSC CGL Format', examProb: 'Hot',
  },
  {
    id: 69, category: 'Carnatic Classical', topic: 'Purandara Dasa Classification',
    questionType: 'assertion-reason',
    question: 'Read the Assertion (A) and Reason (R):',
    assertion: 'Purandara Dasa is called the "Father of Carnatic Music."',
    reason: 'He systematized the method of teaching Carnatic music and created graded lessons for students.',
    options: [...ASSERTION_REASON_OPTIONS],
    answer: 'Both A and R are true, and R is the correct explanation of A',
    detail: 'Purandara Dasa (1484-1564) is indeed called the Father of Carnatic Music (A is true) because he systematized the teaching methodology with graded lessons (sarali varisai, janta varisai, etc.) that are still used today (R is true and correctly explains A).',
    context: 'SSC CGL Format', examProb: 'Hot',
  },
  {
    id: 70, category: 'String Instruments (Tata)', topic: 'Instrument-Musician Match',
    questionType: 'match-following',
    question: 'Match the instrument with the musician most associated with it:',
    matchLeft: ['1. Sitar', '2. Shehnai', '3. Santoor', '4. Sarod'],
    matchRight: ['A. Ravi Shankar', 'B. Bismillah Khan', 'C. Shivkumar Sharma', 'D. Amjad Ali Khan'],
    options: ['1-A, 2-B, 3-C, 4-D', '1-B, 2-C, 3-D, 4-A', '1-C, 2-A, 3-D, 4-B', '1-D, 2-B, 3-A, 4-C'],
    answer: '1-A, 2-B, 3-C, 4-D',
    detail: 'Sitar = Ravi Shankar. Shehnai = Bismillah Khan. Santoor = Shivkumar Sharma. Sarod = Amjad Ali Khan. These are the most iconic instrument-musician associations in Indian classical music.',
    context: 'SSC CGL Format', examProb: 'Hot',
  },

  // ─── MORE REGULAR QUESTIONS ───────────────────────────────────────────

  {
    id: 71, category: 'Hindustani Classical', topic: 'Taal System',
    question: 'Teentaal, the most commonly used taal in Hindustani music, has how many beats (matras)?',
    answer: '16 beats',
    options: ['16 beats', '12 beats', '10 beats', '14 beats'],
    shortcut: 'Teentaal = 16 matras + 4 vibhags (4+4+4+4) + most common taal + Hindustani',
    detail: 'Teentaal (Trital) has 16 beats divided into 4 vibhags of 4 beats each. It is the most commonly used taal in Hindustani music. The pattern is: Dha Dhin Dhin Dha | Dha Dhin Dhin Dha | Na Tin Tin Ta | Ta Dhin Dhin Dha. The third vibhag is khali (empty/no emphasis).',
    context: 'SSC CGL 2022 High', examProb: 'High',
  },
  {
    id: 72, category: 'Famous Musicians & Awards', topic: 'Ustad Alla Rakha',
    question: 'Ustad Alla Rakha, father of Zakir Hussain, was a legendary player of which instrument?',
    answer: 'Tabla',
    options: ['Tabla', 'Sitar', 'Sarangi', 'Pakhawaj'],
    shortcut: 'Alla Rakha = Tabla + father of Zakir Hussain + Ravi Shankar\'s accompanist + Punjab Gharana',
    detail: 'Ustad Alla Rakha (1919-2000) was one of the greatest tabla players in history. He was the father and guru of Zakir Hussain. He was the primary accompanist of Ravi Shankar for decades. He received Padma Shri (1977) and Sangeet Natak Akademi Award.',
    context: 'SSC CGL 2021 Recurring', examProb: 'Recurring',
  },
  {
    id: 73, category: 'Carnatic Classical', topic: 'Violin in Carnatic Music',
    question: 'Though Western in origin, the Violin became a standard instrument in Carnatic music. Who popularized it in the South Indian tradition?',
    answer: 'Baluswami Dikshitar',
    options: ['Baluswami Dikshitar', 'Yehudi Menuhin', 'L. Subramaniam', 'Lalgudi Jayaraman'],
    shortcut: 'Baluswami Dikshitar = brother of Muthuswami Dikshitar + introduced violin to Carnatic + 18th century',
    detail: 'Baluswami Dikshitar (1786-1859), younger brother of Muthuswami Dikshitar (of the Carnatic Trinity), is credited with introducing and popularizing the violin in Carnatic music. The violin is now the most important melodic accompaniment instrument in Carnatic concerts. Notable violinists include Lalgudi Jayaraman, M.S. Gopalakrishnan, and L. Subramaniam.',
    context: 'SSC CGL 2022 High', examProb: 'High',
  },
  {
    id: 74, category: 'Current Affairs & Awards', topic: 'UNESCO Music Heritage',
    question: 'Which Indian musical tradition is included in the UNESCO Intangible Cultural Heritage list?',
    answer: 'Sankirtana of Manipur',
    options: ['Sankirtana of Manipur', 'Dhrupad of Gwalior', 'Khayal of Lucknow', 'Carnatic Kriti of Tiruvarur'],
    shortcut: 'UNESCO ICH India music = Sankirtana (Manipur, 2013) + Vedic chanting (2008)',
    detail: 'Sankirtana of Manipur was inscribed in UNESCO\'s Intangible Cultural Heritage list in 2013. It is a ritual art of singing, drumming, and dancing performed in temples and homes. Additionally, the tradition of Vedic Chanting was proclaimed an ICH in 2008. Chhau dance (2010) also has musical components.',
    context: 'SSC CGL 2023 Confirmed', examProb: 'Confirmed',
  },
  {
    id: 75, category: 'Hindustani Classical', topic: 'Natyashastra',
    question: 'The Natyashastra, which classifies Indian musical instruments into four categories, was authored by whom?',
    answer: 'Bharata Muni',
    options: ['Bharata Muni', 'Sarangadeva', 'Venkatamakhi', 'Matanga'],
    shortcut: 'Natyashastra = Bharata Muni + 4 instrument types + Tata/Sushira/Avanaddha/Ghana + ~200 BCE',
    detail: 'The Natyashastra was composed by Bharata Muni (approximately 200 BCE to 200 CE). It is the foundational text on performing arts in India, covering music, dance, and drama. It classifies instruments into Tata (string), Sushira (wind), Avanaddha (membrane percussion), and Ghana (solid percussion). It also describes ragas, talas, and rasas.',
    context: 'SSC CGL 2019-2024 Hot', examProb: 'Hot',
  },
  {
    id: 76, category: 'Famous Musicians & Awards', topic: 'Kumar Gandharva',
    question: 'Kumar Gandharva was an innovative Hindustani vocalist known for blending classical music with which tradition?',
    answer: 'Malwa folk music',
    options: ['Malwa folk music', 'Rajasthani folk music', 'Bengali Baul music', 'Kashmiri Sufiana'],
    shortcut: 'Kumar Gandharva = Malwa folk + innovative classical + Dewas (MP) + Padma Vibhushan 1990',
    detail: 'Kumar Gandharva (1924-1992) was a revolutionary Hindustani classical vocalist based in Dewas, Madhya Pradesh. He uniquely integrated Malwa folk music elements into classical singing. Despite losing a lung to tuberculosis, he reinvented his singing technique. Received Padma Vibhushan (1990) and Sangeet Natak Akademi Award.',
    context: 'SSC CGL 2022 Recurring', examProb: 'Recurring',
    place: 'Dewas', lat: 22.96, lng: 76.05,
  },
  {
    id: 77, category: 'String Instruments (Tata)', topic: 'Rudra Veena',
    question: 'The Rudra Veena (Been) is associated with which Hindustani classical form?',
    answer: 'Dhrupad',
    options: ['Dhrupad', 'Khayal', 'Thumri', 'Ghazal'],
    shortcut: 'Rudra Veena = Dhrupad instrument + oldest veena + Ustad Asad Ali Khan + Lord Shiva',
    detail: 'The Rudra Veena (also called Been) is one of the oldest stringed instruments in India, primarily used in Dhrupad music. It is associated with Lord Shiva (Rudra). Ustad Asad Ali Khan and Ustad Zia Mohiuddin Dagar were notable Rudra Veena players. It has two large gourd resonators and a bamboo/teak tube.',
    context: 'SSC CGL 2021 High', examProb: 'High',
  },
  {
    id: 78, category: 'Percussion - Membranous (Avanaddha)', topic: 'Tavil',
    question: 'The Tavil is a drum that accompanies the Nadaswaram in which music tradition?',
    answer: 'Carnatic Classical Music',
    options: ['Carnatic Classical Music', 'Hindustani Classical Music', 'Film Music', 'Sufi Music'],
    shortcut: 'Tavil = Nadaswaram accompaniment + Carnatic + South India + temple festivals + barrel drum',
    detail: 'The Tavil is a barrel-shaped drum that traditionally accompanies the Nadaswaram in Carnatic music and South Indian temple festivals. The combination of Nadaswaram and Tavil is considered the most auspicious ensemble for temple ceremonies. One side is played with the right hand (using thimbles) and the other with the left hand (using a stick).',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Thanjavur', lat: 10.79, lng: 79.14,
  },
  {
    id: 79, category: 'Current Affairs & Awards', topic: 'Indian Music Abroad',
    question: 'Ravi Shankar\'s collaboration with which Beatle popularized Indian classical music in the West?',
    answer: 'George Harrison',
    options: ['George Harrison', 'John Lennon', 'Paul McCartney', 'Ringo Starr'],
    shortcut: 'Ravi Shankar + George Harrison = Sitar in Western rock + Concert for Bangladesh 1971',
    detail: 'Ravi Shankar\'s friendship with George Harrison of The Beatles was pivotal in popularizing Indian classical music in the West during the 1960s. Harrison learned Sitar from Shankar and used it in songs like "Norwegian Wood." They co-organized the Concert for Bangladesh in 1971, one of the first major charity concerts.',
    context: 'SSC CGL 2020 Recurring', examProb: 'Recurring',
  },
  {
    id: 80, category: 'Hindustani Classical', topic: 'Agra Gharana',
    question: 'The Agra Gharana is primarily known for its emphasis on which aspect of vocal music?',
    answer: 'Bol-baant (rhythmic word play) and powerful voice',
    options: ['Bol-baant (rhythmic word play) and powerful voice', 'Sweet melodious alap', 'Tappa and thumri', 'Only devotional singing'],
    shortcut: 'Agra Gharana = Bol-baant + powerful voice + Faiyaz Khan + rhythmic mastery + nom-tom alap',
    detail: 'The Agra Gharana emphasizes bol-baant (rhythmic play with lyrics), powerful voice projection, and nom-tom alap. It is known for its weighty and grand style of Khayal singing. Notable exponents include Ustad Faiyaz Khan, Latafat Hussain Khan, and Khadim Hussain Khan.',
    context: 'SSC CGL 2023 Recurring', examProb: 'Recurring',
    place: 'Agra', lat: 27.18, lng: 78.02,
  },
  {
    id: 81, category: 'Current Affairs & Awards', topic: 'Grammys Indian Winners',
    questionType: 'match-following',
    question: 'Match the Indian Grammy winner with their winning work:',
    matchLeft: ['1. Ravi Shankar', '2. A.R. Rahman', '3. Zakir Hussain (2024)', '4. Vishwa Mohan Bhatt'],
    matchRight: ['A. Multiple albums including West Meets East', 'B. Slumdog Millionaire', 'C. Three awards for Best Global Music', 'D. A Meeting by the River'],
    options: ['1-A, 2-B, 3-C, 4-D', '1-B, 2-A, 3-D, 4-C', '1-C, 2-D, 3-A, 4-B', '1-D, 2-C, 3-B, 4-A'],
    answer: '1-A, 2-B, 3-C, 4-D',
    detail: 'Ravi Shankar won multiple Grammys over decades including for West Meets East. A.R. Rahman won for Slumdog Millionaire. Zakir Hussain won 3 Grammys in 2024. Vishwa Mohan Bhatt won for A Meeting by the River (1994).',
    context: 'SSC CGL Format', examProb: 'Hot',
  },
  {
    id: 82, category: 'Famous Musicians & Awards', topic: 'Begum Akhtar',
    question: 'Begum Akhtar, known as the "Queen of Ghazal," was also a celebrated singer of which other form?',
    answer: 'Thumri and Dadra',
    options: ['Thumri and Dadra', 'Dhrupad and Dhamar', 'Khayal and Tarana', 'Qawwali and Bhajan'],
    shortcut: 'Begum Akhtar = Queen of Ghazal + Thumri + Dadra + Lucknow + Padma Shri 1968 + Padma Bhushan 1975',
    detail: 'Begum Akhtar (1914-1974), born in Faizabad (now Ayodhya), UP, was called "Mallika-e-Ghazal" (Queen of Ghazal). She was equally celebrated for Thumri and Dadra singing. She received Padma Shri (1968) and Padma Bhushan (1975, posthumous). She is considered one of the greatest female vocalists of Hindustani music.',
    context: 'SSC CGL 2021 High', examProb: 'High',
    place: 'Lucknow', lat: 26.85, lng: 80.95,
  },
  {
    id: 83, category: 'Carnatic Classical', topic: 'Tyagaraja Aradhana',
    question: 'The Tyagaraja Aradhana, an annual music festival, is held at which place in Tamil Nadu?',
    answer: 'Thiruvaiyaru',
    options: ['Thiruvaiyaru', 'Tiruvarur', 'Srirangam', 'Chidambaram'],
    shortcut: 'Tyagaraja Aradhana = Thiruvaiyaru + January + Pancharatna Kritis + group singing',
    detail: 'The Tyagaraja Aradhana is held annually in January at Thiruvaiyaru near Thanjavur, Tamil Nadu, commemorating the death anniversary of composer Tyagaraja. Hundreds of musicians gather to sing his Pancharatna Kritis (five gems) in unison. It is one of the most important events in the Carnatic music calendar.',
    context: 'SSC CGL 2022 Confirmed', examProb: 'Confirmed',
    place: 'Thiruvaiyaru', lat: 10.88, lng: 79.10,
  },
  {
    id: 84, category: 'Current Affairs & Awards', topic: 'Dadasaheb Phalke Award Music',
    question: 'Which of the following playback singers received the Dadasaheb Phalke Award in 2023?',
    answer: 'Asha Bhosle',
    options: ['Asha Bhosle', 'S.P. Balasubrahmanyam', 'Shreya Ghoshal', 'Sonu Nigam'],
    shortcut: 'Asha Bhosle = Dadasaheb Phalke 2023 + Guinness record + sister of Lata Mangeshkar + playback legend',
    detail: 'Asha Bhosle received the Dadasaheb Phalke Award in 2023 (69th National Film Awards). She holds a Guinness World Record for recording the most songs. She is the sister of Lata Mangeshkar. She also received Padma Vibhushan (2008). Previous music-related Dadasaheb Phalke awardees include Lata Mangeshkar (1989) and Asha\'s achievement spans over 7 decades.',
    context: 'SSC CGL 2025 Hot', examProb: 'Hot',
  },
  {
    id: 85, category: 'Percussion - Solid (Ghana)', topic: 'Four-fold Classification',
    questionType: 'match-following',
    question: 'Match the instrument classification (Natyashastra) with the correct example:',
    matchLeft: ['1. Tata Vadya', '2. Sushira Vadya', '3. Avanaddha Vadya', '4. Ghana Vadya'],
    matchRight: ['A. Sitar', 'B. Shehnai', 'C. Tabla', 'D. Ghatam'],
    options: ['1-A, 2-B, 3-C, 4-D', '1-B, 2-C, 3-D, 4-A', '1-C, 2-D, 3-A, 4-B', '1-D, 2-A, 3-B, 4-C'],
    answer: '1-A, 2-B, 3-C, 4-D',
    detail: 'Tata Vadya (string) = Sitar. Sushira Vadya (wind) = Shehnai. Avanaddha Vadya (membrane percussion) = Tabla. Ghana Vadya (solid percussion) = Ghatam. This classification from Bharata Muni\'s Natyashastra is one of the most frequently asked topics.',
    context: 'SSC CGL Format', examProb: 'Hot',
  },

  // ─── WIND INSTRUMENTS (SUSHIRA) — NEW ─────────────────────────────────────
  {
    id: 86, category: 'Wind Instruments (Sushira)', topic: 'Shehnai & Bismillah Khan',
    question: 'Ustad Bismillah Khan, the legendary Shehnai player, received the Bharat Ratna in which year?',
    answer: '2001',
    options: ['2001', '1999', '2008', '1998'],
    shortcut: 'Bismillah Khan = Shehnai = Bharat Ratna 2001 | Played at Red Fort on Independence Day | Varanasi',
    detail: 'Ustad Bismillah Khan (1916-2006) received the Bharat Ratna in 2001 for his mastery of the Shehnai. He played Shehnai at the Red Fort on India\'s first Independence Day (1947). The Shehnai is a double-reed wind instrument considered auspicious in Indian weddings and temples.',
    context: 'SSC CGL 2019-2024 Recurring', examProb: 'Hot',
    place: 'Varanasi', lat: 25.32, lng: 82.99,
  },
  {
    id: 87, category: 'Wind Instruments (Sushira)', topic: 'Nadaswaram',
    question: 'Nadaswaram is the South Indian counterpart of which North Indian instrument?',
    answer: 'Shehnai',
    options: ['Shehnai', 'Bansuri', 'Been', 'Harmonium'],
    shortcut: 'Nadaswaram = South Indian Shehnai | Tamil Nadu temples | Mangala Vadyam (auspicious instrument)',
    detail: 'The Nadaswaram is a large double-reed wind instrument used extensively in South Indian temple music and ceremonies. It is considered the South Indian equivalent of the Shehnai. Tiruvavaduthurai T.N. Rajarathinam Pillai is among the most famous Nadaswaram players.',
    context: 'SSC CGL 2021 Recurring', examProb: 'Recurring',
    place: 'Tamil Nadu', lat: 10.79, lng: 78.70,
  },
  {
    id: 88, category: 'Wind Instruments (Sushira)', topic: 'Alghoza',
    question: 'Alghoza, a pair of double flutes played simultaneously, is associated with which region?',
    answer: 'Rajasthan and Punjab',
    options: ['Rajasthan and Punjab', 'Gujarat and Maharashtra', 'Kerala and Tamil Nadu', 'Assam and West Bengal'],
    shortcut: 'Alghoza = Double flute | Rajasthan + Punjab + Sindh | One drone + one melody | Folk music staple',
    detail: 'The Alghoza (also Algoza) consists of two flutes played simultaneously — one provides the melody while the other provides the drone. It is popular in Rajasthan, Punjab, and Sindh regions. Players use a continuous breathing technique similar to circular breathing.',
    context: 'SSC CGL Folk instruments', examProb: 'High',
    place: 'Rajasthan', lat: 26.92, lng: 70.90,
  },
  {
    id: 89, category: 'Wind Instruments (Sushira)', topic: 'Pepa',
    question: 'Pepa, a hornpipe instrument made from buffalo horn, is associated with which festival?',
    answer: 'Bihu festival of Assam',
    options: ['Bihu festival of Assam', 'Pongal festival of Tamil Nadu', 'Onam festival of Kerala', 'Durga Puja of West Bengal'],
    shortcut: 'Pepa = Buffalo horn pipe | Assam | Bihu festival essential | Played with Dhol and Taal',
    detail: 'Pepa is a hornpipe instrument made from buffalo horn, primarily associated with the Bihu festival of Assam. It is an essential instrument in Bihu dance performances. The instrument produces a high-pitched sound and is played by blowing into the narrow end.',
    context: 'SSC CGL NE India instruments', examProb: 'High',
    place: 'Assam', lat: 26.14, lng: 91.74,
  },
  {
    id: 90, category: 'Wind Instruments (Sushira)', topic: 'Harmonium',
    question: 'The Harmonium originated in which continent before being widely adopted in Indian music?',
    answer: 'Europe',
    options: ['Europe', 'Asia', 'Africa', 'North America'],
    shortcut: 'Harmonium = European origin | Adapted in India 19th century | Free reed + bellows | Keyboard instrument',
    detail: 'The Harmonium originated in Europe (France/Germany) in the early 19th century and was brought to India during British colonial rule. It was widely adopted in Indian music, especially in devotional (bhajan/kirtan), semi-classical, and folk genres. Some purists initially resisted it as a non-Indian instrument.',
    context: 'SSC CGL instruments origin', examProb: 'High',
  },

  // ─── CURRENT AFFAIRS & AWARDS — NEW ───────────────────────────────────────
  {
    id: 91, category: 'Current Affairs & Awards', topic: 'Padma Awards Musicians 2025',
    question: 'Which renowned Hindustani classical vocalist received the Padma Vibhushan in 2025?',
    answer: 'Prabha Atre',
    options: ['Prabha Atre', 'Ashwini Bhide', 'Kishori Amonkar', 'Gangubai Hangal'],
    shortcut: 'Prabha Atre = Padma Vibhushan 2025 | Kirana Gharana | Hindustani vocalist | 4 doctorates',
    detail: 'Dr. Prabha Atre, the renowned Hindustani classical vocalist of the Kirana Gharana, received the Padma Vibhushan in 2025. She is known for her mastery of Khayal, Thumri, and other forms. She holds 4 doctorates and has published extensively on Indian music.',
    context: 'SSC CGL 2025-26 Hot', examProb: 'Hot',
  },
  {
    id: 92, category: 'Current Affairs & Awards', topic: 'Grammy Indian Nominees 2025',
    question: 'Shankar Mahadevan was nominated for the Grammy Awards in 2025 for which collaborative album?',
    answer: 'This Moment (with Zakir Hussain)',
    options: ['This Moment (with Zakir Hussain)', 'Breathless (Solo)', 'Shakti (with John McLaughlin)', 'Saathiya (Film Soundtrack)'],
    shortcut: 'Shankar Mahadevan + Zakir Hussain = Grammy nominee 2025 | "This Moment" | Cross-cultural fusion',
    detail: 'Shankar Mahadevan was part of the Grammy-nominated album "This Moment" alongside the late Zakir Hussain, who won 3 Grammys in 2024. The album represents the fusion of Indian classical and world music traditions.',
    context: 'SSC CGL 2025-26', examProb: 'High',
  },
  {
    id: 93, category: 'Current Affairs & Awards', topic: 'National Film Award Music 2024',
    question: 'The 70th National Film Awards (2024) Best Music Director award was given for which film?',
    answer: 'Ponniyin Selvan-I (A.R. Rahman)',
    options: ['Ponniyin Selvan-I (A.R. Rahman)', 'RRR (M.M. Keeravani)', 'Brahmastra (Pritam)', 'Animal (Vishal-Shekhar)'],
    shortcut: 'A.R. Rahman = National Film Award 2024 (70th) | Ponniyin Selvan-I | PS-1 Chola dynasty film',
    detail: 'A.R. Rahman won the National Film Award for Best Music Director at the 70th National Film Awards (2024) for the Tamil epic film Ponniyin Selvan-I (PS-1), based on Kalki Krishnamurthy\'s novel about the Chola dynasty.',
    context: 'SSC CGL 2025', examProb: 'High',
  },
  {
    id: 94, category: 'Current Affairs & Awards', topic: 'Zakir Hussain Grammy Triple 2024',
    question: 'Ustad Zakir Hussain won how many Grammy Awards in 2024, making history as an Indian musician?',
    answer: '3 Grammy Awards',
    options: ['3 Grammy Awards', '2 Grammy Awards', '1 Grammy Award', '4 Grammy Awards'],
    shortcut: 'Zakir Hussain = 3 Grammys 2024 | Tabla maestro | Passed away Dec 2024 | Son of Alla Rakha',
    detail: 'Ustad Zakir Hussain won 3 Grammy Awards in 2024, making him the most decorated Indian musician at the Grammys. He passed away in December 2024. He was the son of legendary tabla player Ustad Alla Rakha and a Padma Shri, Padma Bhushan, and Padma Vibhushan recipient.',
    context: 'SSC CGL 2025-26 Hot', examProb: 'Hot',
  },
  {
    id: 95, category: 'Current Affairs & Awards', topic: 'Cultural Festivals 2025',
    question: 'The Saptak Music Festival, one of India\'s longest classical music festivals, is held annually in which city?',
    answer: 'Ahmedabad',
    options: ['Ahmedabad', 'Mumbai', 'Varanasi', 'Kolkata'],
    shortcut: 'Saptak = Ahmedabad | January every year | Hindustani classical | 12-day festival | Est. 1980',
    detail: 'The Saptak Music Festival is held annually in Ahmedabad, Gujarat, every January. Established in 1980, it is one of India\'s longest running and most prestigious Hindustani classical music festivals, lasting 12 days.',
    context: 'SSC CGL cultural events', examProb: 'High',
    place: 'Ahmedabad', lat: 23.02, lng: 72.57,
  },

  // ─── CARNATIC CLASSICAL — NEW ─────────────────────────────────────────────
  {
    id: 96, category: 'Carnatic Classical', topic: 'Tyagaraja Contributions',
    question: 'Tyagaraja, one of the Carnatic Trinity, composed most of his kritis in praise of which deity?',
    answer: 'Lord Rama',
    options: ['Lord Rama', 'Lord Krishna', 'Lord Shiva', 'Goddess Saraswati'],
    shortcut: 'Tyagaraja = Carnatic Trinity | Telugu kritis for Lord Rama | Pancharatna Kritis (5 gems) | Thiruvaiyaru',
    detail: 'Tyagaraja (1767-1847) composed thousands of kritis primarily in Telugu, devoted to Lord Rama. His Pancharatna Kritis (5 gems) are the most celebrated compositions in Carnatic music. The annual Tyagaraja Aradhana festival is held at Thiruvaiyaru, Tamil Nadu.',
    context: 'SSC CGL Carnatic Trinity', examProb: 'Recurring',
    place: 'Thiruvaiyaru', lat: 10.88, lng: 79.10,
  },
  {
    id: 97, category: 'Carnatic Classical', topic: 'Muthuswami Dikshitar',
    question: 'Muthuswami Dikshitar, of the Carnatic Trinity, composed primarily in which language?',
    answer: 'Sanskrit',
    options: ['Sanskrit', 'Telugu', 'Tamil', 'Kannada'],
    shortcut: 'Dikshitar = Carnatic Trinity | Sanskrit compositions | Influence of Hindustani ragas | Veena player',
    detail: 'Muthuswami Dikshitar (1775-1835) composed primarily in Sanskrit. His compositions uniquely blend Carnatic and Hindustani musical elements. He was also an accomplished Veena player. Unlike Tyagaraja (Telugu) and Syama Sastri (Telugu), Dikshitar preferred Sanskrit.',
    context: 'SSC CGL Carnatic Trinity details', examProb: 'High',
  },
  {
    id: 98, category: 'Carnatic Classical', topic: 'Syama Sastri',
    question: 'Syama Sastri, the third member of the Carnatic Trinity, was a devotee of which goddess?',
    answer: 'Goddess Kamakshi',
    options: ['Goddess Kamakshi', 'Goddess Saraswati', 'Goddess Meenakshi', 'Goddess Lakshmi'],
    shortcut: 'Syama Sastri = Carnatic Trinity | Devoted to Kamakshi | Telugu compositions | Tala expertise',
    detail: 'Syama Sastri (1762-1827) was the eldest of the Carnatic Trinity. He was devoted to Goddess Kamakshi of Kanchipuram. He composed primarily in Telugu and was known for his mastery of tala (rhythm). His compositions have complex rhythmic patterns.',
    context: 'SSC CGL Carnatic Trinity', examProb: 'High',
  },
  {
    id: 99, category: 'Carnatic Classical', topic: 'Tala System Carnatic',
    question: 'How many basic talas (Suladi Sapta Tala) are there in the Carnatic music system?',
    answer: '7',
    options: ['7', '5', '12', '10'],
    shortcut: '7 Suladi Sapta Talas | Dhruva, Matya, Rupaka, Jhampa, Triputa, Ata, Eka | 175 total with jati combinations',
    detail: 'The Carnatic tala system has 7 basic talas (Suladi Sapta Tala): Dhruva, Matya, Rupaka, Jhampa, Triputa, Ata, and Eka. Combined with 5 jati variations (Chatusra, Tisra, Misra, Khanda, Sankirna), they produce 35 talas, further yielding 175 with gati combinations.',
    context: 'SSC CGL music theory', examProb: 'High',
  },

  // ─── HINDUSTANI CLASSICAL — NEW ───────────────────────────────────────────
  {
    id: 100, category: 'Hindustani Classical', topic: 'Gwalior Gharana',
    question: 'Which is the oldest Gharana in Hindustani classical music?',
    answer: 'Gwalior Gharana',
    options: ['Gwalior Gharana', 'Agra Gharana', 'Jaipur-Atrauli Gharana', 'Patiala Gharana'],
    shortcut: 'Gwalior Gharana = Oldest | Founded by Nathhan Khan/Haddu Khan | Bal-Khayal style | Mother of all Gharanas',
    detail: 'Gwalior Gharana is considered the oldest and most fundamental Gharana in Hindustani classical music, often called the "mother of all Gharanas". Founded in the 16th century, it emphasizes open-throated singing, clarity of notes, and Bal-Khayal style.',
    context: 'SSC CGL 2023 Confirmed', examProb: 'Confirmed',
    place: 'Gwalior', lat: 26.22, lng: 78.18,
  },
  {
    id: 101, category: 'Hindustani Classical', topic: 'Jaipur-Atrauli Gharana',
    question: 'The Jaipur-Atrauli Gharana is known for its emphasis on which aspect of vocal music?',
    answer: 'Raga purity and rare ragas',
    options: ['Raga purity and rare ragas', 'Thumri and romantic compositions', 'Fast rhythmic patterns', 'Dhrupad singing style'],
    shortcut: 'Jaipur-Atrauli = Raga purity | Alladiya Khan (founder) | Rare ragas | Kishori Amonkar, Mallikarjun Mansur',
    detail: 'The Jaipur-Atrauli Gharana, founded by Alladiya Khan, is known for its emphasis on raga purity, use of rare and complex ragas, and meend (gliding between notes). Famous exponents include Kishori Amonkar, Mallikarjun Mansur, and Kesarbai Kerkar.',
    context: 'SSC CGL Gharana system', examProb: 'High',
  },
  {
    id: 102, category: 'Hindustani Classical', topic: 'Patiala Gharana',
    question: 'The Patiala Gharana is famous for which style of vocal delivery?',
    answer: 'Fast taan and powerful voice projection',
    options: ['Fast taan and powerful voice projection', 'Slow meditative alaap', 'Dhrupad-based compositions', 'Light classical Thumri only'],
    shortcut: 'Patiala Gharana = Fast taans | Ali Baksh & Fateh Ali Khan (founders) | Bade Ghulam Ali Khan famous student',
    detail: 'The Patiala Gharana is known for its fast taans (melodic runs), powerful voice projection, and colorful presentation. Founded by Ali Baksh and Fateh Ali Khan. Bade Ghulam Ali Khan was its most famous exponent. The gharana originated in Patiala, Punjab.',
    context: 'SSC CGL Gharana details', examProb: 'High',
    place: 'Patiala', lat: 30.34, lng: 76.39,
  },

  // ─── FAMOUS MUSICIANS & AWARDS — NEW ─────────────────────────────────────
  {
    id: 103, category: 'Famous Musicians & Awards', topic: 'MS Subbulakshmi Bharat Ratna',
    question: 'M.S. Subbulakshmi was the first musician to receive the Bharat Ratna. In which year was she honored?',
    answer: '1998',
    options: ['1998', '2001', '1999', '1990'],
    shortcut: 'MS Subbulakshmi = Bharat Ratna 1998 | First musician | Carnatic vocalist | "Queen of Music" | UN concert',
    detail: 'M.S. Subbulakshmi (1916-2004) received the Bharat Ratna in 1998, becoming the first musician ever to receive India\'s highest civilian honor. She performed at the United Nations General Assembly in 1966. She was known for her rendition of Vishnu Sahasranamam and Suprabhatam.',
    context: 'SSC CGL 2023 Confirmed', examProb: 'Confirmed',
  },
  {
    id: 104, category: 'Famous Musicians & Awards', topic: 'Lata Mangeshkar Bharat Ratna',
    question: 'Lata Mangeshkar received the Bharat Ratna in which year?',
    answer: '2001',
    options: ['2001', '1999', '1998', '2008'],
    shortcut: 'Lata Mangeshkar = Bharat Ratna 2001 | "Nightingale of India" | Playback legend | 25,000+ songs',
    detail: 'Lata Mangeshkar (1929-2022) received the Bharat Ratna in 2001 along with Bismillah Khan. Known as the "Nightingale of India", she recorded over 25,000 songs in 36 languages. She received the Dadasaheb Phalke Award in 1989. Her career spanned over 7 decades.',
    context: 'SSC CGL 2021 Confirmed', examProb: 'Confirmed',
  },
  {
    id: 105, category: 'Famous Musicians & Awards', topic: 'Bharat Ratna Music Chronology',
    question: 'Which musician received the Bharat Ratna in 1999 for contributions to Sitar?',
    answer: 'Pandit Ravi Shankar',
    options: ['Pandit Ravi Shankar', 'Ustad Bismillah Khan', 'M.S. Subbulakshmi', 'Pandit Bhimsen Joshi'],
    shortcut: 'Bharat Ratna Music = MS Subbulakshmi (1998) > Ravi Shankar (1999) > Lata + Bismillah (2001) > Bhimsen Joshi (2009)',
    detail: 'Bharat Ratna in Music chronology: M.S. Subbulakshmi (1998, first musician), Pandit Ravi Shankar (1999, Sitar), Lata Mangeshkar & Bismillah Khan (both 2001), Pandit Bhimsen Joshi (2009, Hindustani Khayal).',
    context: 'SSC CGL Recurring', examProb: 'Recurring',
  },

  // ─── FOLK MUSIC — NEW CATEGORY ────────────────────────────────────────────
  {
    id: 106, category: 'Folk Music', topic: 'Baul Music',
    question: 'Baul music, recognized by UNESCO as Intangible Cultural Heritage, originates from which region?',
    answer: 'Bengal (West Bengal & Bangladesh)',
    options: ['Bengal (West Bengal & Bangladesh)', 'Rajasthan', 'Punjab', 'Assam'],
    shortcut: 'Baul = Bengal | UNESCO 2005 | Mystic folk songs | Ektara + Dotara | Lalon Fakir most famous Baul',
    detail: 'Baul is a mystical folk music tradition from Bengal (West Bengal and Bangladesh), recognized by UNESCO as Intangible Cultural Heritage in 2005. Baul singers are wandering minstrels who sing about divine love and the soul. They use Ektara, Dotara, and Duggi drums. Lalon Fakir is the most celebrated Baul.',
    context: 'SSC CGL UNESCO + Folk music', examProb: 'Hot',
    place: 'West Bengal', lat: 23.81, lng: 87.98,
  },
  {
    id: 107, category: 'Folk Music', topic: 'Lavani Music',
    question: 'Lavani, a combination of folk song and dance, is the traditional art form of which state?',
    answer: 'Maharashtra',
    options: ['Maharashtra', 'Karnataka', 'Gujarat', 'Rajasthan'],
    shortcut: 'Lavani = Maharashtra | Dholki beat | Romantic/social themes | Tamasha tradition | Marathi folk',
    detail: 'Lavani is a traditional folk art form of Maharashtra combining energetic song and dance. It is performed to the beats of the Dholki. Lavani has two forms: Nirguni (philosophical) and Shringari (romantic). It is closely associated with the Tamasha folk theater tradition.',
    context: 'SSC CGL Maharashtra folk arts', examProb: 'Recurring',
    place: 'Maharashtra', lat: 18.52, lng: 73.86,
  },
  {
    id: 108, category: 'Folk Music', topic: 'Pandavani',
    question: 'Pandavani, a folk singing tradition narrating tales from the Mahabharata, is from which state?',
    answer: 'Chhattisgarh',
    options: ['Chhattisgarh', 'Madhya Pradesh', 'Jharkhand', 'Odisha'],
    shortcut: 'Pandavani = Chhattisgarh | Mahabharata recitation | Teejan Bai (Padma Vibhushan) | Tambura + singing',
    detail: 'Pandavani is a folk singing tradition from Chhattisgarh that narrates stories from the Mahabharata. Teejan Bai is the most famous Pandavani artist, receiving the Padma Vibhushan (2019). The performer narrates stories using dramatic voice modulation and plays the Tambura.',
    context: 'SSC CGL folk traditions + Teejan Bai', examProb: 'Hot',
    place: 'Chhattisgarh', lat: 21.27, lng: 81.87,
  },

  // ─── STRING INSTRUMENTS — FILL GAP ────────────────────────────────────────
  {
    id: 109, category: 'String Instruments (Tata)', topic: 'Swarabat',
    question: 'The Swarabat, a precursor to the modern Sitar, was a stringed instrument popularized during which period?',
    answer: 'Mughal period',
    options: ['Mughal period', 'Gupta period', 'British colonial period', 'Mauryan period'],
    shortcut: 'Swarabat = Precursor of Sitar | Mughal era | Plucked string | Evolved into modern Sitar',
    detail: 'The Swarabat was a plucked stringed instrument from the Mughal period, considered an evolutionary precursor to the modern Sitar. It had a long neck and gourd resonator. The instrument gradually evolved, with Amir Khusrau often credited with contributing to its development.',
    context: 'SSC CGL instrument history', examProb: 'High',
  },

  // ─── PERCUSSION - SOLID — FILL GAP ───────────────────────────────────────
  {
    id: 110, category: 'Percussion - Solid (Ghana)', topic: 'Morsing',
    question: 'The Morsing (jaw harp) is commonly used as an accompaniment in which music tradition?',
    answer: 'Carnatic classical music',
    options: ['Carnatic classical music', 'Hindustani classical music', 'Baul folk music', 'Qawwali'],
    shortcut: 'Morsing = Jew\'s harp / mouth harp | Carnatic percussion | Ghana Vadya | Held between teeth, plucked',
    detail: 'The Morsing is a small jaw harp (Ghana Vadya) used primarily in Carnatic classical music as a percussion accompaniment alongside the Mridangam and Ghatam. The player holds it between the teeth and plucks the metal tongue to produce rhythmic patterns.',
    context: 'SSC CGL instrument classification', examProb: 'High',
  },
]

// =====================================================================
// PYQ DATA — 28 entries
// =====================================================================

export const miPYQHistory: MIPYQEntry[] = [
  { date: '2025-03-15', shift: 'Shift 1', question: 'Zakir Hussain won how many Grammy Awards in 2024?', answer: '3', category: 'Current Affairs & Awards' },
  { date: '2025-03-14', shift: 'Shift 2', question: 'Pandavani folk tradition is from which state?', answer: 'Chhattisgarh', category: 'Folk Music' },
  { date: '2025-01-10', shift: 'Shift 1', question: 'Baul music is a UNESCO heritage from which region?', answer: 'Bengal', category: 'Folk Music' },
  { date: '2025-01-09', shift: 'Shift 2', question: 'Alghoza double flute is played in which region?', answer: 'Rajasthan and Punjab', category: 'Wind Instruments (Sushira)' },
  { date: '2024-09-13', shift: 'Shift 1', question: 'Shehnai is associated with which musician?', answer: 'Ustad Bismillah Khan', category: 'Wind Instruments (Sushira)' },
  { date: '2024-09-12', shift: 'Shift 2', question: 'Which instrument did Pandit Ravi Shankar play?', answer: 'Sitar', category: 'String Instruments (Tata)' },
  { date: '2024-06-20', shift: 'Shift 1', question: 'Santoor belongs to which state?', answer: 'Jammu & Kashmir', category: 'String Instruments (Tata)' },
  { date: '2024-03-14', shift: 'Shift 2', question: 'Who is known as the Father of Carnatic Music?', answer: 'Purandara Dasa', category: 'Carnatic Classical' },
  { date: '2024-03-13', shift: 'Shift 1', question: 'The Carnatic Trinity includes Tyagaraja, Dikshitar and...?', answer: 'Syama Sastri', category: 'Carnatic Classical' },
  { date: '2023-10-05', shift: 'Shift 3', question: 'Tansen was a court musician of which Mughal emperor?', answer: 'Akbar', category: 'Hindustani Classical' },
  { date: '2023-10-03', shift: 'Shift 1', question: 'Amir Khusrau is credited with inventing which instruments?', answer: 'Sitar and Tabla', category: 'Hindustani Classical' },
  { date: '2023-07-17', shift: 'Shift 2', question: 'M.S. Subbulakshmi received Bharat Ratna in which year?', answer: '1998', category: 'Famous Musicians & Awards' },
  { date: '2023-07-14', shift: 'Shift 1', question: 'Which instrument is classified as Avanaddha Vadya?', answer: 'Tabla', category: 'Percussion - Membranous (Avanaddha)' },
  { date: '2023-04-18', shift: 'Shift 2', question: 'Natyashastra was written by whom?', answer: 'Bharata Muni', category: 'Hindustani Classical' },
  { date: '2023-04-17', shift: 'Shift 1', question: 'Ghatam is used in which music tradition?', answer: 'Carnatic Classical Music', category: 'Percussion - Solid (Ghana)' },
  { date: '2023-03-07', shift: 'Shift 3', question: 'Which Gharana is the oldest in Hindustani music?', answer: 'Gwalior Gharana', category: 'Hindustani Classical' },
  { date: '2022-12-06', shift: 'Shift 2', question: 'Sarod is associated with which musician?', answer: 'Ustad Amjad Ali Khan', category: 'String Instruments (Tata)' },
  { date: '2022-12-05', shift: 'Shift 1', question: 'Damaru is associated with which deity?', answer: 'Lord Shiva', category: 'Percussion - Membranous (Avanaddha)' },
  { date: '2022-08-11', shift: 'Shift 2', question: 'Bismillah Khan received Bharat Ratna in which year?', answer: '2001', category: 'Famous Musicians & Awards' },
  { date: '2022-08-10', shift: 'Shift 1', question: 'Sitar belongs to which category of instruments?', answer: 'Tata Vadya (String)', category: 'String Instruments (Tata)' },
  { date: '2022-04-21', shift: 'Shift 2', question: 'Sarangi is a bowed instrument from which state?', answer: 'Rajasthan', category: 'String Instruments (Tata)' },
  { date: '2022-04-20', shift: 'Shift 1', question: 'Mridangam is used in which classical music system?', answer: 'Carnatic', category: 'Carnatic Classical' },
  { date: '2021-11-16', shift: 'Shift 3', question: 'Lata Mangeshkar received Bharat Ratna in which year?', answer: '2001', category: 'Famous Musicians & Awards' },
  { date: '2021-11-15', shift: 'Shift 1', question: 'A.R. Rahman won the Oscar for which film?', answer: 'Slumdog Millionaire', category: 'Famous Musicians & Awards' },
  { date: '2021-08-13', shift: 'Shift 2', question: 'Nadaswaram is the South Indian equivalent of which instrument?', answer: 'Shehnai', category: 'Wind Instruments (Sushira)' },
  { date: '2021-08-12', shift: 'Shift 1', question: 'Dhrupad is the oldest form of which music?', answer: 'Hindustani Classical', category: 'Hindustani Classical' },
  { date: '2020-08-07', shift: 'Shift 2', question: 'Chenda is a drum from which Indian state?', answer: 'Kerala', category: 'Percussion - Membranous (Avanaddha)' },
  { date: '2020-03-06', shift: 'Shift 1', question: 'Pakhawaj accompanies which vocal form?', answer: 'Dhrupad', category: 'Percussion - Membranous (Avanaddha)' },
  { date: '2020-03-04', shift: 'Shift 2', question: 'How many Melakarta ragas exist in Carnatic music?', answer: '72', category: 'Carnatic Classical' },
  { date: '2019-06-13', shift: 'Shift 1', question: 'Jaltarang produces music by striking what?', answer: 'Water-filled cups', category: 'Percussion - Solid (Ghana)' },
  { date: '2019-06-07', shift: 'Shift 3', question: 'Ravi Shankar received Bharat Ratna in which year?', answer: '1999', category: 'Famous Musicians & Awards' },
  { date: '2019-03-08', shift: 'Shift 2', question: 'Khayal is the most popular form of which classical tradition?', answer: 'Hindustani Classical Music', category: 'Hindustani Classical' },
]
